#ingress:
#  enabled: true
#  className: "traefik"
#  hosts:
#    - host: "jellyfin.home.example.com"
#      paths:
#        - path: /
#          pathType: Prefix
persistence:
  config:
    enabled: true
    existingClaim: jellyfin-config-pvc
  media:
    enabled: true
    existingClaim: media-nfs-pvc
  cache:
    enabled: true
    existingClaim: jellyfin-cache-pvc
