---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: readarr
spec:
  encryptedData:
    API_KEY: AgC64VUPAc8YtaCnxO84Tu3cDLDIFEjlXhzcGqLFc4qvifaVg3P3iSgqcjDBE/xUtW0c1NSe8eIGd5cMIecSsRRYmi75w1Pv++hx+vbTsPM85ePltLoXKj/Y6xmHxjbOUy3i/b5gdiltqLhcRf+To1vtiNXWlLrzuJ5l/N4g7ECRys2uCXQXv99f03ZPGqfWPT7PqeLlxIyeFhmRGJHqgIxM4V1zbuTAl1JRgZzsQtfSoqeLAMq+YzzPCUdBQEazPpQXU4wZQ/H8aH1YvqjFqMAvOtwd+sX802cOlUADdoCVzHSk2P77ODJSER53rzks82qUIEfXDo80VJLOlaAIyzwALLuIE0HD1qF++bmcCD1MlzMwAVvMl7I+VPWaFEAL7cV1f3UfTGZ0EN8ISO4Rvdofru2CfIGArYMWu6QkpMz0itOH67Wx6o1XiqxAGlELOMz1ckLny2p6TEAf0ElXH8emPYnMg692MWXUdL20YTD7E17EAs7QNUj76t01rmVwb0kExk8Vk46CwNwQAZrnNhQtD5ebEgFV+cAnIyxQBvLxNbk0TK9puKA8WU436GiF0wd+u3r8DbJQWVTTv25Yry8cwUgr8/QKGGPvyKY0FWTg0Cq0Ym6eUEBU3zgP9d9WlIwSZJIIe5wfIb3+zhgr00eaePGFeg7D1yBUKE8bEo8HpQuIysztljwkhEaOj566g3ghmTgxgegRNIeJKpCgHJyg3bcXRK0vpYKHNw7yfp0L/81QgZbW8J9rai+3ptnjIdurlVE0y700n5qc1/DBuT3y
  template:
    metadata:
      name: arr-api-key
      namespace: readarr
