---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: readarr
spec:
  encryptedData:
    API_KEY: AgBZJyfYO5wE06rCn8Mh+XfygdsAhuLrLq+NaYPc9H5XiKwaa0rnTayFksVc7Wy53bZuMVNHZPvUs9XxWDhuaAP7b7QIbjCABJJGesI16Rs+Fm9tZPt0yO7FyAIyYInhu7VugQZ5f7fS5p+Pmo4z1dKuLq4V4hxdRyQCJMdTGzf3BnIh0YOa6y4tSvV76usXhYinFCg0bh7HiwTIhMPTXCtZfWPjgyp52TFP92HVLVtoZOhh2bNWUYw9Sz8FNlXOrdj15iXB9YJdvJ5mQ0BKSR2Lo16EScdt7M4Dsug9Qlzup5Dcqinf4KY/11mwG0k/C2ELVCgbV5Os2bMafKCxRrJzbpCX/NfC9sa8r8TeAJb94xb2fHvAayZFJWxWaRh0MpditH4mzmvDjFrQgSLCyZUpemZI2VG2mWHK4EGvWCaMpxB1PryHEE08Ma7Q5cwhsa5pik7g7rdVqi2S20Du4UeXR2bC6SDrymr577vuryb9VdBLK673o7PBMPimQDorKt11ENY2LXBYdGoYrR2FQvUhrcmZCtJ4eG+Q6bmEfT003mcYnidwYOvfgt7tbn8gk5XfqCtEYMupv0voBrQb2tCrkY/uxylYY8Az8VUWgnsW1aimKifoSPlqaY6BtBP/Gt/Hy7EKIkwZ8MZlOWi0gAYjvdqZtYkfrjuFJmt17Xzf6qF1rZgckN+9rEwFjOcxUZ3vvE2yn9i7pwLDIBg+CYE47CC1Zx0cG4WfdlxnLrXrIQ==
  template:
    metadata:
      name: arr-api-key
      namespace: readarr
