---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: readarr
spec:
  encryptedData:
    API_KEY: AgCPwoCzhJCvQjS51pMWOffnM50SjGBqCuAEOZSGeRiYI79WG5kIsnXJT07uZ1jHJOs9lQfrr6MNssOR0rPKODMtJ+V/OB+MfitvZLFP4GYXqhqj/aGxqotm+eQ8rfPri3hAz8ArVdsxnloWHQeEyzg3EEYvckc51N2cM8zPRnhGoLNO6iK3fnXauZiH5o8SSq/CcDu1xv+N4++RwabGQWjp7RWbPDWMbKsOw1CzA4/dcqI5vV20C1X1ywyMHk+A3eGmsLpnVpvIoiZ6ztmg+Y8GF9KjJZNkvmntNNHGWf4tMlenpL2yOkEm46e0nLvtO6wnyLS0LmKTOX/fHrrD0eBlmsGk/taOJ/rQDPPgHzjt0pNoV7FqnjHAcRkM3wtvnMuxdvV2rNqffXgyDKzV2OkcupSxNbr5l1jwB00AMXZZQYBDr1SAA85Lmou7UnqbamxSUD0RyhRYWSqNb6ob2bMDJFf00KBSrvSeHhCRtQrVAyCv2EfNIbs+2i95Is71uRI2f4/+XbJIoX2MntigmE0dA6CotFzEeJAyoEuJPjfCFsIwkkIbtWUb+EGT2kMN9GP8Vik0RUYQvZT1N3Yk01ez+YomXATUx3xx2hkYbI1rC5A1PMdLojCfUDGY3++GSUYubNSy8sYVuxuTB++sHNg3wv0PuwUKfxV0a/Lo0MffPdDceuHQPpxMTYYQUJD7rtwXy90rxunyD67rKp4qVPr6weM5ko+2UA==
  template:
    metadata:
      name: arr-api-key
      namespace: readarr
