ingress:
  main:
    enabled: true
    className: traefik
    hosts:
      - host: readarr.rostor.local
        paths:
          - path: /
            pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
    tls:
      - hosts:
          - readarr.rostor.local
        secretName: readarr-tls

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/linuxserver/readarr
          tag: develop-0.4.18.2805-ls157
        env:
          TZ: Etc/UTC
          PUID: "1000"
          PGID: "1000"

service:
  main:
    controller: main
    ports:
      http:
        port: 8787

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 1Gi
    globalMounts:
      - path: /config
  media:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 1Gi
    globalMounts:
      - path: /data
