---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCATDSHwCl4a5nPZX0MnDUQozJdqLXqowDteZLbFpu8Dbe5bKCI4EmN6DAOXkPXXiW4ZXaqAbsYATPglmxS/m+SV2GwnSsMA9yFjaaKZAESCy1JTzUF9VC1jDZkEg6zKw3jWxRy7SvB3xzQu/xR22lTOC4obU/XFf6/Wce7g4BJsRaZ3gvpCPaz/Og4mzUkyBSje4BKtNY2kMUGfZbg2dCjIo5hQ4CUkOsDpzIAPkHaXAAtv8DuznCFXi1XCtVod37c6WL59DkfbWzXYcdNtd0WsuEfyBnM0dE3rHHrcGaBTX7SUsq0MFX5zBtucflV3mBF53xIcdUkDXbsdEZKM1dU4saleXVV53t2XJjrsyz+JpscXZwB1PxGl8wxAJLJAvEZjrghKqZQhyJIbrfS03Vl10WLnnMbe9aMMZAYmuHb7E/Ht7FVuwMYsPxO0EaKNA65opeuIR4McE0aWgydB28dPSZm4SWt6KDeHEP4G7u2Jctpkmk6RnEd5Qifw8h0ONxjysaUKxNFl2WtGJ+PnWDmE1adgKsE8/Rs879kNBGPRCU5bF3vTDeU2XqGtVGKUfBunALX/GAG5IOKygmV4nyXF8nHnPFeT0LAYiPc/819Qa2PEEytFpvrU+TyAHoWtVuVXV1drwxG/68oeYBgjJByt4p/R6/jA0T16lxgep1CvswsXqQ7zuTNiHZuXS5aO9M+Z4jX5x8kwSD0HAAjJ4vWpw==
    client_secret: AgBQ5OtKAkwvNpWfi8Twer122f0VKIjwMIaJnFDUwdAYg7jxM1zKzR/68XlWTG0ReVW9dFPcGN8aqAQevtp3aiPZJivYI1sIH3LFSVenqKxHPIWdl34toYrN8usa519S0TUW5NSqT3N4jV81VDmODUbZaeKsEIFg+VhH68f/fD27hzn3OLfdcXIvABJ0s9kQaWj46aYf9Pt66CGuLzAfwoV8xLr3fyOf9r7aVF/faPqIcDl2vraOFm/UatmXM+WUBhd8v4H97AuxmrY0TsI7kUiyFsCxF9dHAY3sbYE6If4AzsaI68dB30BsyKV/QEg8aFnoNk9ixm7W0EIbO9WEhEoaP2s3kP8PyA9fuADeszwlw1I7L2giP7pG6OQ9Dc3We7rt/iGU7LgUSKROPj/XSXWODaJpeiVqY7uK4r50/osOi7VgNVjfbqJLeYCBeyNR8AR/zB22orq0b868EJWEkorWbjyiO+s2h9QKEc4sPQrxVtKoeBENsJ8sNLXAqZfKRh1Q4BfFPLhPzx1rRJxTPkHxlJ0U0FDK1PylnbIZhWDE2AE2bN61/vUFv58e8h+JwhGA2Cdqnj7cPUE9yO0NAhmd6DbKa3lPW12ZEjWbVPnUaRIq5GIZlZ/sNFKfBvlxnpW70eaEok7ZFyVd5eAjTQrtbAEaBOcB39gdHF1h5I9C/hoqACkVlCc+omjA5dCAuaNGLqoSJRUZNF0w2fcvxKLWuOWbcYojinHyU0G3xxuOnkek2xMn9E7wPB7R51JPIogfluPJ9lkQhsc2ZU2AbW4=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
