apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nextcloud
spec:
  capacity:
    storage: 1500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.3.164
    path: /volume1/k8s/nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  volumeName: nfs-nextcloud
  resources:
    requests:
      storage: 1500Gi
