apiVersion: ENC[AES256_GCM,data:xWs=,iv:2iHUuQtnWgzMMIU1iFj/2tsg7TtHX03brff8J1mnRKk=,tag:C1F1LumNojH7DhdK05rDoA==,type:str]
kind: ENC[AES256_GCM,data:EqQnrci9,iv:zwd+ROHWiWXMK7kPDQWRP2upxiaH6VyHloIUYUewxM4=,tag:v0NrjnfsOVTGhJinsToFPA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mZiym1kseqMKrcRuGp50mgA=,iv:E03sRkUOBe6aK0UawnmhN2MtL59v2dJtYnMeUSUPgcQ=,tag:2nmtk4SgPYyP7SlsU+v2fA==,type:str]
    namespace: ENC[AES256_GCM,data:GncrXR7sd02c,iv:3OzVYNamGy4wyAjMSTSJ0AYXvVFEmtxZt3ie/HBa6ZI=,tag:dSuCtymfNpDsT1MkKjldag==,type:str]
type: ENC[AES256_GCM,data:srHbbPpg,iv:umGMuM6BF3lF+HXMf4ghDP8jZ/CH/H27OafjfRo7PsY=,tag:QMJ6QKagGADnSAe/AFF9Lw==,type:str]
stringData:
    nextcloud-username: ENC[AES256_GCM,data:fnkvrf4=,iv:F8OWfWiY6vZCe19jBEE3dmmqG3zOr6T+FWDKYX+Wv+k=,tag:ZNk4kesWIFw7vk7PJyv2PQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:FJMQ0pPEhM/hjbw6nzFE0oiPMwA=,iv:tibToyHsaPsJNN8r4gGECSTlpLODF6ppb0GaWJf5CjY=,tag:WUgNABG4yMn294HRV1YaJQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:lhg+5iMc+LJ7TxMZWkt0LCmUltU=,iv:a396+t7fIujpyLzLQYaOZOJkPTWtomIuDwCjJUxXXr0=,tag:iZIEBoDX7sEaQMVhCenz7Q==,type:str]
    redis-password: ENC[AES256_GCM,data:CJ2ncM+HnqEadFOJiscip25dnCQ=,iv:OrOnvHB7NYydEi+wVIrbEIPGLzlowAEcse9oPgJUIiU=,tag:ICbvWySJe+uzdFeoZ8eSBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NVlaemxFa05lSVdmSHdE
            b21DRTdKODZ1S0NzbEczdkpqdE8vbjAvNG1vCitOVWRFQ1RNNEoxWXUxRWd6YW1M
            WGQvbTFxMW9TY2RBS29uWkRpck0ybnMKLS0tIFYrVnBjK3VKZnRiNDVTdStxZ1A1
            V04yaHJCRm90UlN0S2dVYXdQbXZpSmcKkvrgTnfBTmrBPAAQgCth5jSm7+zLaUvX
            j6PMzrgx3haOwCSieFAg7EW+2RsWw0BRKaZaX3stOnZ4LMRLJQozLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrmavzfl5aarr7hs9y5yzvxn80szfjhs4xk63d6wsz8v88fcudaqsrpnnj
    lastmodified: "2026-06-09T21:34:52Z"
    mac: ENC[AES256_GCM,data:ZZVccW9KnLqpTDLik2ES6+Cu298AZ8Wq2sQtk2UTQmKtaBtWZL9CSLU8j+esxzrGlaFIC8mB+NYUI5FLwRMTn2gqhqB69OSMjwMo5qzgiuJE/8woDDJ2YhSnlpm0tMu88OWx0HXsQjHjCLkk7Q9rRhoj4IedtV9m7b5WkLSg1EE=,iv:8OhAuoa4/T0fAfGiuukHGIxzlRy91eKBAU/SCML8sVw=,tag:vIVdYWGgD0h2qYgLxZrzhg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
