---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-user-secret
  namespace: ghost
spec:
  encryptedData:
    ghost-password: AgA6KRtZLks9YSdqAqe7lq52txKV4wbc9Yy3wHJUmI+R9v4qGSC4LskIIUE4JikoRjbBSMi+NaSEPj0fsc3eapatNVezybF/gJZ01XN5c/jzJkzppp5O3FEzz8tfj14qe1+ats85iX2RwO5joLHWcaYFQ1DbDdWNjfy3kjMU2hWEgmq9rb5ZLpZQljDNfz5hfoDNM/obykEeMQ33Zk4YxLLB59M10uHz6OvKWc5JIBJMYbTZzoRzFT/yLwHL/3bNFvW2c6xcOjKBI+0wvhOhJHrFhEG97QQ/BCzeNPrSwt3ngVDxM5HhheL/zVvVncLTegVQS5lciwJQZe9D3Yd2xUpLlzwxdSkc4D96HEUTVUK2m60HNkQkhAyxp0MxdquBxvyaDtGdTJvElcNYYFoEQha9xySjrIh9KxAoU539bRqTczmZOAwCuMOI/TH8dwKudHd68zBjR0tcmJmWE5fROIYSfdW5fu3m9c+vxfByHYu+CZ2j6bghWcYlBvzGGWW2sBOHXB74G7Ikbo0ICBa2XUqqOfrEwJViKhYLzQR00zNCKDIY9rxHJMg2rSohpko41tHPzFQ2qu0DYZTGOXQ/qJPvt2PhTl1IUfxzWQykemtADDCdVgDusBOHfDAERl8yjlLFabii+0xr/0r0AkMY7JJdNE66YVoj28CASWsFI41rdXeXEWcQ0EdB3m1AmzhhwKxSl4cfnsfKASZhmfhh0YrOpTfgvQ==
  template:
    metadata:
      name: ghost-user-secret
      namespace: ghost
