---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-user-secret
  namespace: ghost
spec:
  encryptedData:
    ghost-password: AgAhnCFPSfdquBHGHnR5frME3M2Echn9i+F8yn/LEn4U7Oe331hemJ3XGqGu5u/M5O9Gf7/qf0RGyu/gjWQ49yYon/EFoaFit2wIxiJiATIuQmCPZhZVrKIQaRj4Ehj6OhG5RMdtPySOcF80GH8ePqtvpNFojb7JA60l5+prc1nDSqekyziaDgHRU7GVU7qAELCSzxRrViBwuKmy0mCiXv0tdVAY0iLkrWJVoAq7RnrFL7bitwUPis5GwTcPQp7ccBMaADvQl1DjwW/mrQS7TweEqTNqd75fwOXpt4RFg0J9wM0EF+67Nidm79DFsa4Zku/FlfO/6mF97aHUCAo3v8GsZKmbgko1zJSevGZqU+hEW4eytr3nMERkFUPgoZ76P6rJSK0bkpq0Qrg1iKXDtImwkajF5B78byFzc9RfAk2NVIdTA3NQm72toUGo8E08suPv/tBiEoJh1/t3xYx6x4DcHvOYw37ynu0Ou5AWc15+kxE8w/epwLn8iAiw4bX4mzNaDrP+MktQMlyLnErc/4Eg7/YYRcbdXexNpJGr6CNwD9YbjLX2dmM30FRkWxWHBzhTDFo3teaMH//zcjftHcAI+LHQdlh6SymbBO6oar0swayXNSBwrHCrxggBFLtjTSEgq77c8S8mfC7Cy/xF+ENjmKaXNx9xiskRUUewzW8dvg0diX2ArGmIpFh6U+rkSp+0I5Ss6ncTM5pVVNmNnp2lokQXrnbwf4Uar3NxqYYvt0FJxU2XED4V+l9VaA==
  template:
    metadata:
      name: ghost-user-secret
      namespace: ghost
