apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames:
    - argocd.rostor.local
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: argocd-transport
  namespace: argocd
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.rostor.local`)
      services:
        - name: argo-cd-argocd-server
          port: 443
          serversTransport: argocd-transport
  tls:
    secretName: argocd-tls
