---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ollama-api-key
  namespace: open-webui
spec:
  encryptedData:
    OLLAMA_API_KEY: AgBMspdXfXMoH9yEO8HRvxM8unztHAa6f90XbQZDr5WYINqSJBaGwzUkP4vJx1zGzsrGPgAQLgmaAE7csCMozQkwx9Jnu7bH2dwpemQgmMH0FWlnc7vtOGYSU0tYeXxC4X3ulBVT/Jj8qVlronZ1aXGMAS+i7JOXXRGHMkSOtaEyQPWPbwaVhSSTAjHNuD30Xwb89xSy4T9narn8VAXTD85aMCYVzpKy9E+Ja0cYnNOb0vNDLD8zMYwKxtR8czZ5XkdafLWqekgl806lY1Zl2TXiIwVqIqlN1X/Kh4RlcSmIQJwWApgyNyYW6toNXuHzavk09jNDDpx6r86+n4rV+x2UuF0lPHFHjMlsseWAW2AcjkcOPPXtVEdQAotbZYBTK+8Wlwr52z3grKERGoZWUChc8Oc9GVLnlpgOPcQQDnzZZRV/9xjoPhezV/EjqKhCQRGZCbdQevjvbNaYx+ehk9IE9T247O7oIdYY9RinncrYP6nTC276c6BWxz5vONp6/LqTeLTarTyxZhniqhLEaCcPs5xOipA2jKXVqpqp2CfLLZAoytE8UWKbuegVb6KafeSyJHmieDeoxXS+acrAmSsEfab9aA4QftMtclJ9J+abahNZst9vYAHK54rwz183/Zm/yMW0FXipySToZPTqoFhoJtHKs6y0nokwr0WcMPGqjPfgTPiXenY6DJes+x5N+bNl7hLz00UinZrRRSuz6/Q3Qrf4890fMCrc5zCcrc/IWlbD/IUly+C84c2a9Zur5vrCiIF9c41l6iVoiAemmPcg
  template:
    metadata:
      name: ollama-api-key
      namespace: open-webui
