---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secrets
  namespace: open-webui
spec:
  encryptedData:
    WEBUI_ADMIN_PASSWORD: AgCoDuHFW/1b+gPcHW9vUQwuNo1MVHwfk/uQZJs7qhFpQhkOTcXIyd3E9e9lJZo5jHB/yVwEeyx7yudBOcCrZzNX9Fo2b5gxCwwadanKyd5UlkUrKgTX2s0qRJ1bET9N/n67ist790c/nVugghjvDz3gf6a2dCL79oObMw1EhESe73yGJ9vZAHoth6W8gaDomtvW9EjZQB/T5JnyYYJiVoaiuu/KiS4IjreANBk0uxfKYMLF7xPEDZi+/pIOKYc12CTgM0GWeVBxw59lQsCfx6bJ/YKIkknHM8aLWww+Xculf7I5QjaWyqO7Vo5+/N8YrYpxD5KTE2nR/Af7LwegS+gBxTCS7FIXBGpfJ6NzmY0Vumv1vV/raZ8/wSUDvenEE44zb4vaJ8hLXsOIovXTI1WX16t4ubigIjzof+pzdJqx+NIyJevvMlMGL2IVTIxjzOwkyt/a13TXsgD/OXr/hTn6cDpFBC2A1CTXfc6wtuaK+VsYLArjCJ3ez5rSHPRf32eSbpmAe8igWhYsRxDAAf/dY60ygwJDlQJrenYoeiAHjnpEe2yXsgdrpnhcLEdVHATspRVn3kK+eaqL5UwDSRgnViySZV3Md9b88BIKnfszUKfNkLBpS7TF8FBiRWNhBWSG8sJsFCiMS7johWiC3dama4bxfD/3J3NGGYGnHFlayVG0d9Kp7OBJIUHUpWumUbwddj0oek4yQVMJirC7xYH56phXAw==
    WEBUI_SECRET_KEY: AgAQRq5U+PzKiL3mN90KXwZotTAM5mDFdZApvGp9TlRrrcCfeMj/znPL3vqiVQoJlwUDsNosQxbnu3vlG+g5uhMbYk5JQag9bm+Zws6lfkI/mSFPPB//3iLf50dOuo/dVVFuSPpUt389kudJX572bAWfjvNigscGkwS7Ux4/2GQK6dp915aKt/N92NNnbSZvvBFyN9i5BgOms31N+3ft2oJks7V7bj6p+gHQtA2qhO9KAkVuTHnR5KjKy4c0ykaQiwNBdNF3ePCGmdTsSp/zHU369bhXJxy916BWyDzMM+Y0ZAcmsKwQBoF2ZfmfiETKl0wJlVyhm+ImYcqscb8V8gmbNuB5YoAG8OvCpPd4iSgeaGJy1i/rzBqgvJZFGvtdiism1yBdEh+Vx2d756PiTEMxy+fVG25IalTN48Vnh4t3sWTchinVAl9Q7sZgGNW8ZJysC+9VA65ahHQ/fEkS63VlBebIRqnX+7KUcZ2kSQNEBYDx7Ow/vrMS1Qu4nxkF0NKCEHw3/isFpAYBDnlQlV/kS0Il0zHVTlBblU2HR8kte7y1MUIgxpMEqqkMfEJ/8lNWFpoGCo69FrfOnMVKZ6jNPwZUvidtgF89ae2EJst++tW3LYRoWo0GS0gM40yPasUyjdFcgtgS3QhyLmXBpoB4cdp95P35TIxdQnudtEthbQ9/oj1CiaOsaI9suBgi5aOOaOhc6T2v1BACRNPZBR7UFFn0qRLuH2xpAw8LJE5dXw==
  template:
    metadata:
      name: open-webui-secrets
      namespace: open-webui
    type: Opaque
