---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secrets
  namespace: open-webui
spec:
  encryptedData:
    WEBUI_ADMIN_PASSWORD: AgCBcYhkhlCA1R/VR6ctvvN+CzUft8orew0Rahr7oBG565SHudIAv/CCQXA31Mr0BKG/xg38AhX71Sn4ayS18fAgSy0lnj00hK+s5VVhkp84w2dxXsa0x0fKzu6Q/W/uWX/M1v95U/O3sjuOkAxqyWMfU65RFN3tLQIqWXzwIMXsUvZSokhgk+PVxE4OocNzQDCkPax+0YtZSkQAI3q1jP+Lzs8wD1o9hwQz6Ty6wWmbkAdol72cCcUg9slV2pRrxaEIKH+6JImaF9HqP2IHVRAqH7sPbEIoByR3qeq8Ok/wpNknzPvDOlpbbeNbBZBYy0kVc1qwzdtbGAlDG8GBT4ij+KSp+OYf1R91pCeark7uQO+ZYBzSzaVPwG6RiFJZvOdAxP3wnLWVJPb8NTRs2iXHwBSwLh0jaEzdYgeHoqSgJicH9lAqVhLocaXjeOCcxw1Uoi0erbSSPW3ngI1ylKW2x5i5J2OdBou1P7h0Pu4JQfJcMIk1nX/4vhPnjsWL3eATAbKgW3gt+n1YEnGXnZyd1LqWCgf0auOxzKMeJY5QTU3sjYnA215KtCyb85yPdiUXvQb+X4lolSEFyTwU6GM+abQoBdzJED7P52QP5n0AKPkbH5wWv284ceTZ1tbSOlqSwQpzwnG7YhnwAd47s9SOHyAnS34O1bVzjAMgZqFIO9oXUzPtbTuU2tRne+epNqZO4BmKJQevkJ9Eo8whUJ/9zkbp1w==
    WEBUI_SECRET_KEY: AgBdUdapLZ53tZhCP5gcirOfHUv9CbG5PJJ+DIpbqQl1XX2S4cwdoxR+tgk7xq9eX2n0l9HHt5LhfzgYujFq33SXVR9+iVgkKnnt2K6DxWKOeufaBMuU3qwoxH0+108KJeeOkVCb9MagPGttnwBwVSrtMM/9SE2VUknCsuhZQ/vJFDvphdIniZoCFKyf60OnlMNx2/VHLNcYo1XqUfeGmkyGHOw81RzD2R+pu7KQpjOO2wPUDHXElN4omcbueeOcHzPzSYFJ8ie1uUg9g7QImlP4pCsz96wx0fJHTaAWu0HAWV51ooTk4kHEKQRDPbKkxHV+DTKyr1jnrKO7erW1lUT6H2rknufwZvhy5tBSKkiR/armB640V/9szl8qmuCDaV9PqE6t7qmVI3sGGympSTlYaaFuHDEutp6EP8QYBYGe/XvdcFRtpPqr2N0OQmT5+zZBUeC19CKF4Kl2ezEAJS/qdt+jDX/nj1NeZUC5S1rrvPNJXWevSPE/MqVXStZOV/ewK6pLSgUJrMQnNQAx/13hQpgqLPSrb9CZus+Kn5WIDg2zve0lT3ROI2p6vpURkVypPn3pziRH2FfUR9Iqh6R1G2VMUSwePrOZm8NiaT2mMKZYQdvmZ1yVCL9Q4HjR6Jp+m2ke4Xr+krbybafneOpQltreQmXY8nz9IopTAMYMf7TrYzRU89pER4P28cQfR9P/3jTKRAtCtZRDHj9srXseM2pbRA==
  template:
    metadata:
      name: open-webui-secrets
      namespace: open-webui
