apiVersion: ENC[AES256_GCM,data:ze4=,iv:D0WycKj7KMYMa8q10BUsayDKvLwdOu11++dRW0XjFtQ=,tag:f3R3YSgm0SaxtvHnV9KuZA==,type:str]
kind: ENC[AES256_GCM,data:B0a2OtZD,iv:0luuT6gPiveyUGiWBS3ChZxIlJppmH3p3ObEy4RttZo=,tag:oA1/oIY/+BTkvFe68bVyMw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xNdPRnHlzCreOh8V3BCxskbZ,iv:G21GdRz5n9hgf7B7D5QvlDxKIKL/OgmmUCp4w650rls=,tag:sqCTIARbqX4boGtozBUlRw==,type:str]
    namespace: ENC[AES256_GCM,data:zn77BF8UVCz8Yg==,iv:CKEPRfGKVJVWc3X8QzWrsMGe5GKiabStMHU6Sz2GD1A=,tag:Os+Wvfb4j4xF1petotDXHA==,type:str]
type: ENC[AES256_GCM,data:7vk6PnnG,iv:SaVaMSDEvbzYdbas37yjg1ta4EOnj+MAX6OR+LIKaL4=,tag:E0hXmXEHT3b/ke7UbcHS7g==,type:str]
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:W4TZsr/6JnaAX7C4PjYvU8ZtDYl27FBhr593AqM74wo=,iv:OB0rVwLxumZszUtv1d6tqOVvmEpVRif4XB6v2+/zYb4=,tag:Je0sW+ccQ2PNt+6TlU/z6Q==,type:str]
    WEBUI_ADMIN_PASSWORD: ENC[AES256_GCM,data:0f483cekYm6WdjX12JBUvNc+j/4=,iv:wJ8rRNC/8i8IN6ryqDYJE7JJYQ3+QdVfHs1zNDLHciw=,tag:DbseL/bHr12eCRBL5W1hTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bXNhYmJFUmxKUzE0aDhK
            WnljYzZmSytVY0FwVklIQm16ODIveWh5TFJzCkJSenJqNXpoVVdReUNhYVptOWR4
            ZTduYlhSSkdnaHFXVzh1blRKeTFIR2cKLS0tIEsyeVM3aHFvMFd3VWkzYVRCSXBO
            ZnBoT280NE5NbTZRd2JoQzhqbGhFd0UKe1w6Dg2tNpa7XD3CL+eVyX2vTjKF3rnz
            O1XJ6d2L2sWUUzORFahMKdMMgvPrE58PD+mLki8UxVhh9QhK4sevlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrmavzfl5aarr7hs9y5yzvxn80szfjhs4xk63d6wsz8v88fcudaqsrpnnj
    lastmodified: "2026-06-09T21:34:58Z"
    mac: ENC[AES256_GCM,data:VtNTZ8A0NwVLYIMPebje8Ez0ph7jLPtkKuIGO2z26XyFs7/tafdrqqd9IM2gPa5rpDl+35piZj823il2E8mfic1+1J+1vrknvcT5a8r1c9Z3hYg3SSlU206ZkIN/5sBd32JHZBMhpH+NnY6UaGIoiHUvyFecqKzo7is1lh2a40A=,iv:1ubZONdccm+KfD7+1mwutCBBqM+7x0JVWF6VR7/KSRQ=,tag:aooiOeCgc9GMQB+NO6dzOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
