apiVersion: ENC[AES256_GCM,data:+FU=,iv:fWqcIQz7BTqM3zBj8eLUv4e1UkNpjsGuu1oseiQIHac=,tag:J476ZHturd8Lk0s+dGxMIA==,type:str]
kind: ENC[AES256_GCM,data:YgzM6cCj,iv:0iq+MzbB71ME13EICVfhP6ER3Fg3Fnfi6VLP0AxtsJU=,tag:733RmZ8yNBHmrNQWxDJ5XA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JDLS9QhNx7XJDA8gOG2zxv4B,iv:mWSXSIZMPlzJZxf3tizL59+faPeMTbzQbjNkHE2Ks/8=,tag:I6EjWQMUsU3RgZ4P/th/yA==,type:str]
    namespace: ENC[AES256_GCM,data:NG/r7wngNQRTeQ==,iv:tqfIgEAQc7B/26YnckcVcR/psa0nBtJQP3voqyInhM4=,tag:92oOlqvuT6lsBPBLJOtEkw==,type:str]
type: ENC[AES256_GCM,data:3FjIowcs,iv:OCLvGjeDgEvjiUKq4BLfkP5Q8JXPmoIsj/wMr/1VaaI=,tag:Fx46xn3JC80IWdBuajhO1Q==,type:str]
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:o99phlHzGtHPPEaXl0cQKxOKPvfwd36oCJbV,iv:SQRA7OJWBy5boYzO7duJAfGSzhiF4dzRbUFybGhvZ4A=,tag:u2aQNMWhDEN5tPAlov94GA==,type:str]
    WEBUI_ADMIN_PASSWORD: ENC[AES256_GCM,data:uYGYWJzARWo=,iv:uUhBQDtvWhze8tVW2hclMNXYJkzcy7O1RIQzU5QtDaA=,tag:+jytq85YUnMzIX/UWX8G+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS1BlSitjWWVXb2htUW1r
            Z0J0SlkrZ09qNDVhY0R6eHMvR3RXcUlsbERVCkNWM1NOb3Zva05ZRE5HN2FlSVNY
            b3gwR2lNT1VCZ0xrNzNud1d4c0t5dDAKLS0tIERxQmpBamtsbmJrblBlaEpSRFpv
            Y1IvVVVqTEJxYWVCZnlJV0h6Yy9FdFkKS7mI1nbhdlPc4tTkhX5ZwP0I6srkZas+
            bp7kmds1aKBAfcPdeFIFUnE9LBpDUheVxkd/IVz5nam1oKeLO62tKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrmavzfl5aarr7hs9y5yzvxn80szfjhs4xk63d6wsz8v88fcudaqsrpnnj
    lastmodified: "2026-06-09T21:02:58Z"
    mac: ENC[AES256_GCM,data:S2L4xDd8ViCzzQM2I1MyL13jlUxPHlVOav0lXj/fCiKqA2B5jXokfOR+/1zB0IZO0LhkEYVf6a4nzZ+CdroWpBZ7tQVd9LoXAuIzGvIX7OcA5ET1nc588TYjWg9kTH6THdSFbvCeE+Na89iv1ZHkvAGRbUuLVTy1IfzYBSHMT1k=,iv:a6VIO+CVWf8cu8p7/bjbdYbfnHxXd8DdagXlZ9dpdTM=,tag:dHPjfUvzfSJsHUndJv9TGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
