replicaCount: 1

ingress:
  enabled: true
  ingressClassName: traefik
  hosts: 
  - host: openweb.home
    paths: 
      - path: / 
        pathType: Prefix

ollama:
  enabled: false

ollamaUrls:
  - http://ollama.ollama.svc.cluster.local:11434

pipelines:
  enabled: false

websocket:
  enabled: true
  manager: redis
  redis:
    enabled: true

