replicaCount: 1

ingress:
  enabled: true
  class: traefik
  host: openweb.home
  path: /
  pathType: Prefix

ollama:
  enabled: false

ollamaUrls:
  - http://ollama.ollama.svc.cluster.local:11434

pipelines:
  enabled: false

websocket:
  enabled: true
  manager: redis
  redis:
    enabled: true

extraEnvVarsSecret: open-webui-secrets

extraEnvVars:
  - name: ENABLE_INITIAL_ADMIN_SIGNUP
    value: "True"
  - name: WEBUI_ADMIN_EMAIL
    value: "admin@home.local"
  - name: WEBUI_ADMIN_NAME
    value: "Admin"
