replicaCount: 1

ingress:
  enabled: false

services:
  enabled: true

persistence:
  enabled: true
  size: 10Gi
  storageClass: longhorn

ollama:
  enabled: false

ollamaUrls:
  - http://ollama.ollama.svc.cluster.local:11434

pipelines:
  enabled: false

websocket:
  enabled: true
  manager: redis
  redis:
    enabled: true

extraEnvVarsSecret: open-webui-secrets

extraEnvVars:
  - name: ENABLE_INITIAL_ADMIN_SIGNUP
    value: "True"
  - name: WEBUI_ADMIN_EMAIL
    value: "admin@rostor.cloud"
  - name: WEBUI_ADMIN_NAME
    value: "Admin"
  - name: BYPASS_MODEL_ACCESS_CONTROL
    value: "True"

sso:
  enabled: true
  enableSignup: true
  mergeAccountsByEmail: true
  oidc:
    enabled: true
    clientExistingSecret: open-webui-secrets
    clientIdExistingSecretKey: oidc-client-id
    clientExistingSecretKey: oidc-client-secret
    providerUrl: "https://authentik.rostor.cloud/application/o/open-web-ui/.well-known/openid-configuration"
    providerName: "Authentik"
    scopes: "openid email profile"
