apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-postgres-secret
  namespace: n8n
  annotations:
    sealedsecrets.bitnami.com/controller-name: sealed-secrets
    sealedsecrets.bitnami.com/controller-namespace: sealed-secrets
spec:
  encryptedData:
    password: AgAroOhUQg6w9yxflJwCjy0oADMijX7JeTwaOAQ80QJtBYYhbaIaNAbfH5zdJTE0bhVxWWKNSXuDNZr8QPQPy8g5NCfzNcxKcCorkGUJQ5vaDU9HrR+25gCN7cYJX73ZdHGz6Mq3TxyNqfGHf7Dr7Mk8Qt5hGkoZSs5HB+CWP9JRyXZsOCfIlIugpzTLgIKB+3rZJH/nxIS3obqY56ld8nMHudSA+RQ3gzC3pObGLqYBBoA//B5Cu94VcCswtpY8UU5uqjqj+0qwiv9w9Rmz6AbeiTryM8wCEJXPsYJMpRYpNlHccndS4XElq/gOPs2+fQ4DXFvNfMHkfyvwZLX5x6avtAZM4g2EbW4zEcJ+ZysPDQb+C6q2OYm9jfJ/lThrg3+ObYS44vuBavMRODBSguj5RdB0po6h/84rZPkCcDTgXD2w6EgI9/5smCXEIkUJIXjNyicfpWEw/S3rAFLfa3sB8Dsm+Q03QSpVtDH2xMQiTirO1j2oRLPELJ1l0/FIaoZzZOPQbMJZVYsv4GSj96jgG8ACSeBjmB3OtnGJqhh2MZV/YB0mmrq6Gd4OJOI3jL8mUmD4xccd/1ZUWfQvbxMeoFwr8eEzooqw/nbXblAxFRXihpjIpJi6woiO0d0P0t72YKe0+5XfBqph+4NhXKV42Mm0rDr+l+Gp33irwq5nTx1FjPiDD7dA/DtrYYWsg2IG+LHBXCkBIaaHkGqDD2GZxTOYDaDUfWlQJOXqBZuExw==
  template:
    metadata:
      name: n8n-postgres-secret
      namespace: n8n
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-daytona-secret
  namespace: n8n
spec:
  encryptedData:
    DAYTONA_API_KEY: AgBplMG39n6SZzSdDEkgSnoZk1x/buPW/rz8ympo6un0dxOHcDFKXdGYmnEJWoxVsotS4V4UdahGfoTjNsTiWWoxKZ4wJktMdTx0ZuP0oDVWkrbP6OjG0vhpcZ85TLb0k5H31vuyYx8LhoL1GCBbvCNyeTB8LKeVir/qzXILgnlA+vpRX80UnBG3XhWQPiq1UhF/cwDnRwL+SlZzbZuRf5baRbZDLprS/lN7nDGVESdopwECrLjtG9do5Zq8d4a3Ooj/V1OqCM9kM94pbFIl50XId+uCUvXwDzncPQQzbTI/D22yHCO4/Pt5MwI6qOTXKjE4EM1K7DKi8IJK806AxN3ufBbAR3AKUNiByxG002qrBi/aaTdptccXcqAgMFxCbPW6LbkYisfYjd7betxk1kIsk8JEDvZgWSPJqp+2+ze427CpZxnyUShMUE7kKd20Jad/kCnpDUNXQzbuheL8J16hvV56fvL/s7oQ3il8SuAN4LbMQP5VgxFFHRAg2GeOJHH7MzHyYTS7iVwoPi9DyatnrEFDEcFbP+DNRKNiV13o2LKwHcgWkggeY0Chft1jggow/rc19DDBkdqMlyZp+PvhTHhbAdoBFWz1WsiXlxxYgEqMVAVMygiC+7ahyj1tIgBUtLriOuDs7hNJhlOZpGTEb6BstWOFqc3YH9VYToBs1HoKPCEUabjxRV/aaFvLc8sWlXH+3atWwVujhy3vvUl0+dCVWN1DMcARycKIm4o1Ckg17RaEXEZCi48gbattM7OjCKVVPMkObZT+Ru9NOyWLnaV9Gg==
  template:
    metadata:
      name: n8n-daytona-secret
      namespace: n8n
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-ollama-secret
  namespace: n8n
spec:
  encryptedData:
    OLLAMA_API_KEY: AgAi2DUbBpGJ9c3JQx9+/IwaFTdmDL94thJtJnKAAe86nplKVGLFzBwQZn7r01vaOJsv5jXRll9gdmJLdAmaZ9rfeRdlek2uEyDLozmMqwYmUznMQ6kuzzZzrMmntNdqwG/nYK/TEdm8frNuaYR6TTtieu4fCq6dq+FwvxhuRKMUYOUc4VI5Vh+9cNTJoGsfoiUFIY6hhRjCC/jyTesgxkAIbrl70GoxBxNsUnTDbPawo0Qtxr6Tt7zEK8TBNaMFKndSkgIlTvEjl+lq1GgfV9hYKLnOjEL9byTswK/TnBGwdFu+VEWgcM4xeNGT9VrYu7Fh7V6qYAGXwE62qJQSsUiFZgnucRbKugLVVaemz28I6SIeIYVn1KaA2yplyGXJfWrGdVYVhVyyZlhcONTBCKyVMBO+r493FKKBOsy+k2SU1DqyApjnFzg1b2dlApncjYiY0aAHbQxia+tVoMxYugXQoNWQGpv66d1pD2PxCwH+4LVdgwhVJsNzfvfWHDtSL5Ik+fxMIJxKedbIs0mRr6WQu6GGvtlYLIKvFRmEWDM3knzNY86QG+rmNgXGOSPxkpuVqz+KNhPmj634NToMhzQcCiYCtdiDO7z+Bb8ZhTIHytz/5IoBm5EAfpYrGi0XxCir8ln841GAd1Q5LHEU16urZ/7KfkcC7RNeulBaSAgqrkAFkuWDQBF5IGtJ/LxneBAZl6hNUGR/viRIMDd/oauryk9siR5f2B64c2mQbGkRpg5ARNFbJnxcx13ytKYEoRl93BIAS668lgzBSglqr65g
  template:
    metadata:
      name: n8n-ollama-secret
      namespace: n8n
