apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-postgres-secret
  namespace: n8n
  annotations:
    sealedsecrets.bitnami.com/controller-name: sealed-secrets
    sealedsecrets.bitnami.com/controller-namespace: sealed-secrets
spec:
  encryptedData:
    password: AgAroOhUQg6w9yxflJwCjy0oADMijX7JeTwaOAQ80QJtBYYhbaIaNAbfH5zdJTE0bhVxWWKNSXuDNZr8QPQPy8g5NCfzNcxKcCorkGUJQ5vaDU9HrR+25gCN7cYJX73ZdHGz6Mq3TxyNqfGHf7Dr7Mk8Qt5hGkoZSs5HB+CWP9JRyXZsOCfIlIugpzTLgIKB+3rZJH/nxIS3obqY56ld8nMHudSA+RQ3gzC3pObGLqYBBoA//B5Cu94VcCswtpY8UU5uqjqj+0qwiv9w9Rmz6AbeiTryM8wCEJXPsYJMpRYpNlHccndS4XElq/gOPs2+fQ4DXFvNfMHkfyvwZLX5x6avtAZM4g2EbW4zEcJ+ZysPDQb+C6q2OYm9jfJ/lThrg3+ObYS44vuBavMRODBSguj5RdB0po6h/84rZPkCcDTgXD2w6EgI9/5smCXEIkUJIXjNyicfpWEw/S3rAFLfa3sB8Dsm+Q03QSpVtDH2xMQiTirO1j2oRLPELJ1l0/FIaoZzZOPQbMJZVYsv4GSj96jgG8ACSeBjmB3OtnGJqhh2MZV/YB0mmrq6Gd4OJOI3jL8mUmD4xccd/1ZUWfQvbxMeoFwr8eEzooqw/nbXblAxFRXihpjIpJi6woiO0d0P0t72YKe0+5XfBqph+4NhXKV42Mm0rDr+l+Gp33irwq5nTx1FjPiDD7dA/DtrYYWsg2IG+LHBXCkBIaaHkGqDD2GZxTOYDaDUfWlQJOXqBZuExw==
  template:
    metadata:
      name: n8n-postgres-secret
      namespace: n8n
