apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-postgres-secret
  namespace: n8n
  annotations:
    sealedsecrets.bitnami.com/controller-name: sealed-secrets
    sealedsecrets.bitnami.com/controller-namespace: sealed-secrets
spec:
  encryptedData:
    password: AgAroOhUQg6w9yxflJwCjy0oADMijX7JeTwaOAQ80QJtBYYhbaIaNAbfH5zdJTE0bhVxWWKNSXuDNZr8QPQPy8g5NCfzNcxKcCorkGUJQ5vaDU9HrR+25gCN7cYJX73ZdHGz6Mq3TxyNqfGHf7Dr7Mk8Qt5hGkoZSs5HB+CWP9JRyXZsOCfIlIugpzTLgIKB+3rZJH/nxIS3obqY56ld8nMHudSA+RQ3gzC3pObGLqYBBoA//B5Cu94VcCswtpY8UU5uqjqj+0qwiv9w9Rmz6AbeiTryM8wCEJXPsYJMpRYpNlHccndS4XElq/gOPs2+fQ4DXFvNfMHkfyvwZLX5x6avtAZM4g2EbW4zEcJ+ZysPDQb+C6q2OYm9jfJ/lThrg3+ObYS44vuBavMRODBSguj5RdB0po6h/84rZPkCcDTgXD2w6EgI9/5smCXEIkUJIXjNyicfpWEw/S3rAFLfa3sB8Dsm+Q03QSpVtDH2xMQiTirO1j2oRLPELJ1l0/FIaoZzZOPQbMJZVYsv4GSj96jgG8ACSeBjmB3OtnGJqhh2MZV/YB0mmrq6Gd4OJOI3jL8mUmD4xccd/1ZUWfQvbxMeoFwr8eEzooqw/nbXblAxFRXihpjIpJi6woiO0d0P0t72YKe0+5XfBqph+4NhXKV42Mm0rDr+l+Gp33irwq5nTx1FjPiDD7dA/DtrYYWsg2IG+LHBXCkBIaaHkGqDD2GZxTOYDaDUfWlQJOXqBZuExw==
  template:
    metadata:
      name: n8n-postgres-secret
      namespace: n8n
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-oidc-secret
  namespace: n8n
  annotations:
    sealedsecrets.bitnami.com/controller-name: sealed-secrets
    sealedsecrets.bitnami.com/controller-namespace: sealed-secrets
spec:
  encryptedData:
    oidc-client-secret: AgAWGnOLVzJP6Cfud6Yt0KnPCTMzbtuUMzDajaR2xBgkvSSNRGu6RtLjoC+NixIX1ym4m/AZn9riBgZ7pbmUt9WjjQUyUKoozGP9xemAcvu16D/A6sXxBwyxqRsQ0MjjqbJHbOaa16NB28ZcnbciOFEkuGt3gubriSvzpuYlUz2trcjnBcruYbEULjuRvEXPZwA9pbKnA2UYKmvP3dtQRJbJ2xeCf9fRH/QvxlsL5yLoGq1KmV6YQSFW28lhpbATYgNfWAdS0FhAPN6GpV5mUydykqNE7g4DDnrXHPaPlfPL5xbXS65maUbOsEX+jiy/XXEUouue4lk2TNw1urFfBayTbKN4rL8QgpI/AGvg4eeBgC9xQEcZg09svAn7iFL4kKqe7iAEbAE9tYReK+VqLP04r4B9LbZKvz5jyxGGBY4WboPB1d8zQ97EKe17A0zTBi9gv/3XOTNeXQIqP5J9WtSkpl+Fb35I/nCXIe0GaFVeNSK+3SdTN7hHgxIqHJTIM6oqyVRIOQ0x7zGa6atLIsbz5LYQzXnN58Z2Chzh3IRDLl7bO2IhVLW5rnmUDglCdFjl00RQL8iHfdyCT8M5btsFmrla8j1xb7bt3AazGijMlFLDxmkO/BatD+r5P5awYeb3svodDi0ZfLFLSHtoWmAvCwkeZiwF/NO4hwyNgg4mivYP4jxUn7NT7opxyG6gDhueuqXwgtDpGfN2QukUE8SrPNAX2czDtb1GwTYa6hNPip+Lah0BT4UUO+A6ZRxHRFFk74rwubMqa67I9SubL1wWCb3tnx2ifsSrGGkzS6wfVIFfP0YM2sLhegK3GspmZ52Navfnu1omyIcpNkougePGmvTjBgQX8t6UUO3lMYfVvg==
  template:
    metadata:
      name: n8n-oidc-secret
      namespace: n8n
