apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiobookshelf
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://christianhuth.github.io/helm-charts
      chart: audiobookshelf
      targetRevision: 2.3.1
      helm:
        valueFiles:
          - $values/apps/media/audiobookshelf/values.yaml
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      path: apps/media/audiobookshelf
  destination:
    server: https://kubernetes.default.svc
    namespace: audiobookshelf
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/volumeName
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
