apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiobookshelf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://christianhuth.github.io/helm-charts
    chart: audiobookshelf
    targetRevision: 2.3.1
    helm:
      valueFiles:
        - apps/media/audiobookshelf/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
