apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/immich-app/immich-charts/immich
    chart: immich
    targetRevision: 0.12.0
    #helm:
    #valueFiles:
    #  - apps/media/immich/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
