apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/immich-app/immich-charts/immich
      chart: immich
      targetRevision: 0.12.0
      helm:
        valueFiles:
          - $values/apps/media/immich/values.yaml
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      path: apps/media/immich
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideApply=true
