apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jellyfin.github.io/jellyfin-helm
    chart: jellyfin
    targetRevision: 3.2.0
    helm:
      valueFiles:
        - apps/media/jellyfin/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
