apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komga
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://repo.helmforge.dev
      chart: komga
      targetRevision: 1.4.11
      helm:
        valueFiles:
          - $values/apps/media/komga/values.yaml
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: komga
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
