apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komga
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://repo.helmforge.dev
    chart: komga
    targetRevision: 1.4.11
    #helm:
    #valueFiles:
    #  - apps/media/komga/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
