apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  #- arrstack-app.yaml
  - jellyfin-app.yaml
  - immich-app.yaml
  - audiobookshelf-app.yaml
  - navidrome-app.yaml
  - komga-app.yaml
