apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
  labels:
    argocd.argoproj.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: immich
  labels:
    argocd.argoproj.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: audiobookshelf
  labels:
    argocd.argoproj.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: navidrome
  labels:
    argocd.argoproj.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: komga
  labels:
    argocd.argoproj.io/managed-by: argocd
