apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navidrome
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://oci.trueforge.org/truecharts/navidrome
      chart: navidrome
      targetRevision: 23.4.0
      helm:
        valueFiles:
          - $values/apps/media/navidrome/values.yaml
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      path: apps/media/navidrome
  destination:
    server: https://kubernetes.default.svc
    namespace: navidrome
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
