---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgA6yCiB8JExwqo1V2MkKvG/6/DiuEulcDOt83/ssjyL9hsS2P6f5Qn9noqGhp57LLNJjywxu8NqV4dmTppd9dOY96x2hLodqvAOf1/BYvq4q6wT+IwdcTScJABqcsm/gR+ehr+RCE+ZgevD0+1HIOjdR4rx4TkLi32tuSDCEaWIQL/4c/GnLgluWsALMFVjjGJg4HkWZ2ea8aj5vKtVPN1bsHLoOUxfK7KGp1K7BvTgyF5GXp3nFTNeZgsJmw6xJc2+0JXn69QA8EnNu0Ql6GGA3Mh5OfQXV3ud4TX3SZhA2WGdOAu/19tjHCj/o6pXF6jNwHPsWLld7KsK69ibUh/SK7xGDDoDNM+6EO0pTv53+98yyX9eWiRUGpgsGryILPEychW19SgTxJ6oFImJFVMQoEuqHjwE62v58PEfZeDOxJUGJOkg0+yMlPhSv7X4khBNAM1Pn4rgDDlTKqwq3e1sbknAawGALtbtM0hhlFVENWtrfMfFkMm1SxQipQ4zXYtBE1i2G+15/OkOyEN2UY20GfRZlINmr7IDm2lZj9eF5YIAKViwlgwqKB40TC5HIeYzdeHKacE2m4eAlts3JNmbqVm5sy8U6efbHi70NdWltvfOmhVS3kx2Vq4tKvCFVrftO/h9CWDuCbRvcIUwreSi4b5D5v7lR5ppjka6CqfgZLwYh3UKUAQFXgY0IEMlKyOq8j1AXDmiw4/Fhy+Q/f5sBobRkOIYlvhK8HpbhqDoHfQzHAmh6Ok3dE21Xg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
