---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgASsYZKyzUshDof7iJr2gc+dMBsFsJYzwWtl4tR8AnqWWkHQSCxNclvc6vMiLgifaF1uxda2gYgrbXJq/fhUk0VQE4yAqMa4s00RshJa/LD+4W5VKf98IboImZ7Q5AFH57WYor4SCEAMxKkI6dnLsb/k971tQg7YT9iPwhm7bghYgFAL9IGAErek6YP2EAX7DtWeL8RxBfr4LYgbmvytOqihjug8zdnWwLzRiDY9r/b1SoJ5gk2XpNEGRt0LoooEPmM/4OeAEjuJ7erwgRCvmbawjGGtScW6hwMmOzffbd1RPlyBM3n1qpruk/4/UQuKU7hgmcUT9MlLNeRJvY2+3hQuAoeR2VL7qTp7SDzt9r6Ba4KX/T2DDoy7wkab16uAqDwEhboC5vAGnP3wuutjSnkuOdiW4xxsOwDUxp36sx24qGuMobrdP/DGKr62GYY2m7PWyJzS5ULVgUcyFm6QsPqB3xLEEDYqQO9dLsd+4gvKnyzcMXMn8MkGpV+S1kbBWiv3QYTLhBCe9YuzAoNDMzDeUs2w1cljPE6VlFLB2Lx3M5QZZr1mXN5mOY47kmOXCU2+yauuhQtsvw0QIIay7dJMOhdsnsnZmNpgpJPZwrW7DBX8cWyudEk/dTo5yOPNPxIIlbw5HMZLBQMd19wB5j43gqEc5RO6wowrwCydiF59B+ncERC767xZj7yZYrRBWASCK66jBEe3Ufg0Luc3n/OFvEdww==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
