---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAqKMPWrZ5l44SicVRM0kXwsJ0VVpNPHHXzVlH3sSj5YAeZ06DD1QvNewoAoeXkyWKQSpTZO3bBLjPs2nFH2QpY81e3LD+XiVx10CqHGTUBbEC1aPkMGGLZ5VUb1dlE+iSWHpvMYeTLKqMvHYVKwex6sWGrsLGLJSMrtk7hKAOo3lGmMhgTYwvWGZ+dK3mL7VTJu8PHZpx0H0LkY6X5KNHi8qWFdQWRi7/I5i3CU/Pdt9fxqvHBQe1RM+5mBlIxFEWEBOo++7lm11Ij0Rahs0iOp1sUHEp19A4v902evQO187qekY9ESF5qHQ7NuS9A+pSB/LTLxcgMlqwa3USEFLP3WgeMhNQ5dQvDtCtJSN/50kYTnoaleViExHYvDp42UzwqlPApozeOVhE+ZJIHSGi3ofbIvbhfywhd+pn7JZQCVxmTXxTjdeObpVQUG5qehH4gcXF4tVShIEbtfuteVZYGs2MHvBXMdeqGjOb3jPnsYz6VI8o2uxPIiCqlmHtOJizz4e9lmogkyJREMKq0atnU4A6Xvx38xOFpftkp+biBBgWxuKn/bLU/Upk8yMK6semdh0UzhDOzrG2O+nOiaFUQRn7Y50mFamqFX7Uzldg/49ZCxja1DtTC3CSKt+/omTtJiGBYNWGAMlGK42VVy4ypPwFrRxxo0oTUFQ5KDFO4RQItnb0FURjprX2qRtQ8AiyAVKB/5bxbR7b4HX0o+/GKZe8ud8qbM0X7jsq1z+mdiaB4zC/zJEQr
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
