apiVersion: ENC[AES256_GCM,data:yFQ=,iv:lxDwqEQsRDP9o7QlO5Pg5iI+8734CzDnF8KbTvOaPR4=,tag:NAsfndgQx5LNQBWdzyPKJQ==,type:str]
kind: ENC[AES256_GCM,data:qb3JQv63,iv:4Uj8NXi9xzt9PN/wMx8oCe5Dx6xyA+R0vSCv11IXG+k=,tag:eU1vS9Npvvyex6VOcPAFNw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zqC8+0xcrRXjSkGC8Q==,iv:8eOZNkh6A5vUKRFviS5RlRcLxWtSN3s2eVdJRs1Uj8o=,tag:5M9apOCkpT1S7Acyi8UNPQ==,type:str]
    namespace: ENC[AES256_GCM,data:MeZUrZxxzQ==,iv:gjAoZ9rl/XM6IZc6b4smwU96m4lqBmlU56gGUesx10I=,tag:A5Snv6s6Dd6I/CvdakEWGQ==,type:str]
type: ENC[AES256_GCM,data:JuHrrpxb,iv:KyKdpwxKukXiwCypasdO7hKy+u0jAPrxzcALxmLJDcc=,tag:bJpbq+a/aqvOQkeKhdSy2Q==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:AWaHMRI=,iv:hMc/2eiYqOcVJaXJCSVMuhKUd+yY/GTBKzUsqAgi8/8=,tag:EX0h9V0j5mpF/HC5TDWbpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cDFXMzJWeG4wajVOcVcy
            YUhDNDRqQkZRRjlsMU5kVUJielh0RnN5a2w0Cnd4dzA5Z2hUTjdTamEvdEdOT2cv
            WG5GSGh2a0JxTVZLUWFXYWtVL1R0T2sKLS0tIHhXNVJkcEpJVGFXTGxPQ0xPYTVB
            dG1malUxM1lqZ1RNRCthdG9aTzBad3cK7CRqfXf9rH9am+GRb3HGYyrge8CiK8LI
            6SBbegUYXQ4DblFHeBroaQzjPNFB+gQkfudvI8XiB36XB5Dfxh0gLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrmavzfl5aarr7hs9y5yzvxn80szfjhs4xk63d6wsz8v88fcudaqsrpnnj
    lastmodified: "2026-06-09T21:02:59Z"
    mac: ENC[AES256_GCM,data:wSEX8R8wBoI1TYZuichElXlnCJpsMhArPivqumf3nJ939Jy8PyYfRmc7uRK86QdBXWDfE7eUg81cOLBguuwmDJvUXrdU0T5TqAFda8ve56C/6Eg1mF8AYV/24MDIQpiZl1LWlQg9YPOeUBgU1/dHow7R/fKEbfm2/2iciMD7jgU=,iv:ScGmSMDwIHT3ffCoQmoMdhwD04Ssq+3W385tgG3UmJg=,tag:5upoS07YTFwqu6VP/NSJ5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
