apiVersion: ENC[AES256_GCM,data:VVk=,iv:Mr1J4iCFIMJv7wDqTiGD9KrypUVAoiSKCJCFzvZUMmw=,tag:xs+EEBAJv54IrluQzu157Q==,type:str]
kind: ENC[AES256_GCM,data:3ESAKD1M,iv:KmZlJXwRbAn3lNwZJTR+XwCLNIBk1URnDzk4gGzIVZc=,tag:4T0GfNdRMkFZQjDWCssOSA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZLW428jaCItNCF3+FA==,iv:Xxx60x7rCjtHQfVMkX6zIKF8W48sLM2lsjATIu6vVmo=,tag:23YsYxiQtgK2p5JJ7gJUaQ==,type:str]
    namespace: ENC[AES256_GCM,data:yn4hn7D/lA==,iv:KLAV7k6hIGobVsGp4vB0rfe909/4JrVwa1+vpYS42Qk=,tag:FwolMhUF5Lk/yesrFyQNaw==,type:str]
type: ENC[AES256_GCM,data:dvxxbMBt,iv:9HGu3QMTymbRcm4Kqe5xZFnja5wdlCcc8pu5GfPSfZs=,tag:HrYYSKi1g/QIzYaWO+Z1QQ==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:LLOjdGuzB//v/MqhiLgzVqxLpF8=,iv:8d8pqDWEsje3yeg/OZNV/sggQaHw5gZuNwcjl73mBS8=,tag:kVELld98mK2yAd2uBKEEXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPT1JQQmNHQkFFcHNLTFdz
            Tkw0WXVpamlNTHk4RkZzWWR6SnA3MlloV25RCldmcXdBa0tFT0VYcU1qem1qYjhi
            TlZZVW8xazhZZ2hKMEgrb0J1MFZTWU0KLS0tIHU4MlZDb01KUEVHSnpLSUltM2N5
            YmZyWTZ1QkxrV1Q1YXZMcmdrb3JwOUEKHEvgD5K3t5gP7GIbdBsxy/MMXcTxcgXW
            HTSc9JO8LzN/sdGM6LlEa8zsi2661yNDyq2hCvoBk43ki12slKJ5RA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrmavzfl5aarr7hs9y5yzvxn80szfjhs4xk63d6wsz8v88fcudaqsrpnnj
    lastmodified: "2026-06-09T21:34:43Z"
    mac: ENC[AES256_GCM,data:9Ev0KKQvwlmEQTV8WBlPirC8eZsUXPvzCd3Qc4cordnnhFvF1rVUnpSnfnAymot3IPcaUG70tHUwjXp4UPSreYQ9/F6YAsSitKsyP6D96WUj3J9CMF9YySrpJ6kHQ+zC+aYtquQHGzrAHUtMTpyABsv83eaLIFWRLFjUP5FnD5w=,iv:rWnDCRxusNUIg3Ef6O3/WgOuJRjYzJ0k1d1O3Ajem8I=,tag:VHU90dalV7tE/vxea/u+Rw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
