apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-sonarr
spec:
  capacity:
    storage: 4500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.3.164
    path: /volume2/proxmox2/Media
