---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: sonarr
spec:
  encryptedData:
    API_KEY: AgBsdG60IyNedaZ/l0oQq/e3uLEeyT5m/V8c1AUll8uSTPJRcsrIxUydFng0rDT4U+y5V4iezfnjZa3R4Q+ekBum8gCyk3ryNarwtBJ3eDL6ghmMv0uhmivejpzNt4Xvdb4Qzvw6Yt0DYbmsc1/H2j10soEjqKsWoVMRCwxCU2pk8UW8h005hVk+ScZrdnEoCPyoi9lVI7Kpw11xiIkc/fPlX8O2niHP7SyPlVmpCI8YWMIKB2jRBlmlmGhh1m+WtEgDXS5M7CIyYNJ39W1Eck9wk44C0WZ4z9k9jyFHZ0mgg7Ov8Uufg/6YYrfHwmC0kmszcteaEePcYcghjEuS0cJ586FylwijrzxsZtdOBcLBhuFrBS5HVklSXpFmFSj8522RQhqpp5a9cU2aIPjU38wYvQETtK8MAsl8/6nPM5U9GfMXK391s76Po/xN0tH1y9DbqNU11cx+iP3yybYgzkN8sP3zI2uDdqKYkEdOoei4lZvElwAp7DNeozVRrfkNaZYMatTLXg5stGO6hTXUcpyrW70Xz8XokEfw/cIIKRrTT+DGvkcgyLVRa+1Jv7nL68Q3s4sUiNCEZliBlHaNwgGKYst+2mv71y42PkHpzAl0wJzRDsZWwNhgYQh3Icism8tSpnSMfH1B3RjM9IOJRBL216FWoKZK9Q01ryAjyyEsRp1wGOIIcPQhljXTjIH8UYvQub4kDvnb+JbyWBHBEkD39Z6Ogb/iVQ==
  template:
    metadata:
      name: arr-api-key
      namespace: sonarr
