---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: sonarr
spec:
  encryptedData:
    API_KEY: AgBPmxB0QouAieZRJgg0ag1Xi1QnXJyzYyIS9udqz2QmuacxcbBSMjKgG3mO2ra3FdshtpYb8rddofU9lvgxj2H9h3//GST3C7gxQdQG0suWg7jL35B8eIypX4Gbd9rD+AUvhiMbtBU/Z3chsggOEYvzjdfbrzptasEn+EzGtXfWr/i7GxWWGEba4IJNc6JtYic5Ut7/2TwSnWQ2+UI/zoL9+25U+HsYVYGJpSQ371iEN9rTCQe2uB9D4zONS8jhrU///Zj2NnaGZn45HBEY/vTGJsocBt7SXApwA3Wl1RQADerVcZ1/kReH0JYLOyVZvJwlYz4YBR7YZlIT81aa7w7jPB0k75eSX0MK/2FBwYKj10EP1QA0jbELDXXTPEKjsoHl03LLaj7g/QcE4qmD/ElyU9U246lwtDOyGSQ+hDp1bLhg0VnG1ArjGf3JSqYvt6l9UZxBzu5pM8mwGFIksL4g1c9/i0KrzOtwj1UZyW2ooDxf+t62eunR9Yr3fMWUWQkWe1zOANA3GYtveJCsCiF5dd56pY14Ef1Y/H64Zo8iM6L8mLrRAHCD8zBybqHS0X2F5/LtdpbXVXMLnPPpTUy7/5A+qrgUgPQ9bnsrW/Lkm9a7uP5qAwNXUQS5mxJMHoHp4rSOgeAtsBEftmSjpWL8VWPNWskLJ1xv4dGmkLVP+mPtDYpyJ61L3LZ/q5QxenFjVOPrjEg1n9jcjRemIMvGV2BvWHGo+Y7aA891kvzHtg==
  template:
    metadata:
      name: arr-api-key
      namespace: sonarr
