---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: sonarr
spec:
  encryptedData:
    API_KEY: AgA/sRECbVPYGrmITWc+qBW0MiMmRMPn1wkzyKSyad0YSeI5XmJPCJ8oDtZiJW/U8alswiM5DKghjotN5JReAhhOKLhk7O4Vm54rmX8v+OvexZWkf/fpoB5/adng6xPzYWL0W8RQcqe30ZggrjP8e7Tk3gQKC011lWO+rBe7a99jpVl/MyxjCzAJSEJohtq7gExPM5n3wEFOdf1j/gxO2lyTHhq7F58iEOzVkcMhDRlm8rlHWVeHo1ZQMfYKsA4AwQVo8lh2jLnsEwOS/b0FZKezwdsVYiPhZM12FJreJStZi7wCgzUdGGgTaDDzaPd448TqN4xEgfXdGuc/E35YpFlGHRiw9khEiJsxWehuObbTgPyXyv+mWaf6Mr0FpB72DU9WRjXpqkCZTlsMTnNSXSl8VpAp7yQzlEbEKpQr/wC6MsNvyGH6ziKD+qZU7P2XQWMY4KuP/MS7k+MFAdISWyTvqQv52CURUqVlHZgH0tZWY6JppCu5bj61FZGjck1CMGiQu9J1aZlRMgAef8AbXjZjClH8rVBskaNhjn6n3QamzYWYLJSi5tnOe8LxebhlBRLfKvnpHd0Kah9B19AEJqCbTxF7uQ/aCSuk1Iyd37M9Ozy7mNzqCN4YDCq0YNQHR7+z8MiGXDA/tW6m/synDKJxs8YpZbku0c8cSXvghUTEI89+tvFnQUaOPObzsPg3eGZ9Mqq3LszlcF62z0st83DtScJNUPIxEvLNqiUsmWqem1eqFjFofTSBvWHaaE7TsIbTn8OgdBh4PPZPCEVEOaoz
  template:
    metadata:
      name: arr-api-key
      namespace: sonarr
