ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: sonarr.home
        paths:
          - path: /
            pathType: Prefix

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/linuxserver/sonarr
          tag: latest
        env:
          TZ: Etc/UTC
          PUID: "1000"
          PGID: "1000"

service:
  main:
    controller: main
    ports:
      http:
        port: 8989

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: standard
    size: 1Gi
    globalMounts:
      - path: /config
  media:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: standard
    size: 1Gi
    globalMounts:
      - path: /data
