---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sure-oidc-secrets
  namespace: sure
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgDD1n3hn/TZRYpc/A4ZZBUze02Nj0wggKCcn1vxZ7dadm4HlosytdSFci6AwGk7sBkUPNRMZGsQKGndCMVAv7U4VKNR2weA8ZG2VjdPnfaTsrLowZDvcpveoVcs29h5ulBFx1MPyKr4RLegvh8KSw5bibtXQbNS/p60F3DGvy19r5I2G0WB/JSIZveHCQCsK5W4g4JctqxPAEVFtJKM0+CzfjOXUwzmwwHqh0ngL4lHSr7/u2H/4IBYq5rKcFI95l8K94t6MeT4SSrRqNqj9H2ScNGQRzVmXWsiwKH+7pzjB9+DtqHpCkt9zS3s/xjwVhvY6x8mr5+/HzWtvzcMvEpdVyVqjZ7ulGlGzFN03DfE2ubSgQ5/E4rsnF7HR4vGFO/F/EnkdGLi2eiKv1xItKpY6947AEBNiQ6B8Bkz0JEqDYbxjgFvzzFuTrvudmR9dBrLV85weA078aoxucB97lOdeQzZSpjWtwYJbrOTyGZcCFSMI4Gsin4LrBNrpINuRjQybXExeLF9v1FIeKrAKgzG4cro17a90FZPAU95SLQKICWmtEaSLU+CsiRqLdJoaR4Gw4886rvcSSI5uTguxY+2KyAem7+KU7PCWmx4DPtw0rGUp9UUF3YyHnKYM3mF3RVFkR4CES0F+aGimF2hUsLlOvynX1rV3X/fsJoYH7abH4C6EVcjm99e8pDeE4s2JTUkhdJ+1zkWU5o5i66KIMn1hJ5+fLLvfKlsH263ydqwAwe6hgoGhWme9ZR5oVvXjBZYHuZEu1NCKRwUlV/nktpGTF5BelUPmjcL+2Lp/aaDSY4UKH7l//KoguINi7viOJ6y1kGNmPjcbjIb/xxED0wvYxhOIHDCgg6LbAiGCJAhog==
  template:
    metadata:
      name: sure-oidc-secrets
      namespace: sure
