---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ollama-api-key
  namespace: sure
spec:
  encryptedData:
    OLLAMA_API_KEY: AgB01tMl1370poLDYzOIKhdwQHSlduz/3mapKsNWr3t3fCqQooU6KLJaaS1YUp/rZVRWuGKWxucCm97zo8rQnHgZPcLhkcffUR6AUZFbk8mxhEiY5yKP0iXeauaUiySE1h9UIWgj+n0kRBzhPtNNP/sLoMWn0/T1dlvYXEcH4wmMc+lM2Qggq4/6Nme+5jF75OgRXh6x+W9hJWNHBeorvY+QXtlkYpfMEdKv4UjJBfc5Lhv+3vZvICOXDxM7LA0B0q017pYy4dZgFBlrL/WDvjRqErGSb8VXz6DkVUp6yFNJ0sj3MwX6n/YVWKEKEVUG2riTyrG8hAGSa+hqygKrruL6510pIWw7/eyyxXHwJjNN78XP88LBjMfYgXuSD/IHgO8N9HPs3ZmA/TJI5IR2Nv8aCOSrQsmyywX9hhFwGFb34DNCIT1Lkq+jJ33p4a41MhOnkXaRvhzdsfSeyyco8U67De5PCRWybBYpvTMOFFnfR6usasQ+GlIGQyKmym+Z0B2uIxj6419ayRSKqlxTXYhFa7NgieyRwXOMuKxhwv3gd1OZ15zG2Ho9gLtMrFRTayAe7lVxENmMbvhJ/AdyEI5HeS+a4bd297oNYH9YYM23IX3IV1pzKFk3ZgIyzNefI7wsKz9kk2HdOtG9NNm2OB05CVYZ25RPDuSqlao28rFpVWsydjNfaq4Mc5H9G31LMJMP0jqbS35ai7KMqwyo4OU9du/hgycIgTaMKgx7IC/EuACHSFE2x8Qm98ORKuOQyTiNeXtAreMXK2OZ73NiU5Yr
  template:
    metadata:
      name: ollama-api-key
      namespace: sure
