image:
  repository: ghcr.io/we-promise/sure
  tag: "0.7.2-alpha.3"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: finance.rostor.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - finance.rostor.cloud
      secretName: sure-cloud-tls

rails:
  existingSecret: sure-secrets
  encryptionEnv:
    enabled: true
  settings:
    SELF_HOSTED: "true"
    AUTH_LOCAL_LOGIN_ENABLED: "false"
    AUTH_LOCAL_ADMIN_OVERRIDE_ENABLED: "true"
  extraEnvVars:
    - name: OIDC_CLIENT_ID
      value: "jT4h7YIhYonHwGsdDZBWRt9mhIKJVF6icvgMy4CI"
    - name: OIDC_ISSUER
      value: "https://authentik.rostor.cloud/application/o/sure/"
    - name: OIDC_REDIRECT_URI
      value: "https://finance.rostor.cloud/auth/openid_connect/callback"
    - name: OIDC_BUTTON_LABEL
      value: "Sign in with Authentik"
    - name: OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: sure-oidc-secrets
          key: OIDC_CLIENT_SECRET

cnpg:
  enabled: true
  cluster:
    enabled: true
    name: sure-db
    instances: 1
    existingSecret: sure-secrets
    secret:
      enabled: false
      name: ""
    storage:
      size: 8Gi
      storageClassName: longhorn

redisOperator:
  enabled: true
  managed:
    enabled: true
  mode: replication
  sentinel:
    enabled: false
  replicas: 3
  persistence:
    enabled: true
    className: longhorn
    size: 8Gi

migrations:
  strategy: job

simplefin:
  encryption:
    enabled: false
    backfill:
      enabled: true
      dryRun: true
