apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ollama-tls
  namespace: ollama
spec:
  secretName: ollama-tls
  dnsNames:
    - ollama.rostor.local
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: ollama-cloud-tls
#   namespace: ollama
# spec:
#   secretName: ollama-cloud-tls
#   dnsNames:
#     - ollama.rostor.cloud
#   issuerRef:
#     name: letsencrypt-staging
#     kind: ClusterIssuer