apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ollama-api-key
  namespace: ollama
spec:
  encryptedData:
    OLLAMA_API_KEY: AgBv0DUACJDqM/GogCkU9xKPi7Z3Z6rR57V3f7C6G/b+hvzkiX5kSn3g3KEivwL23FzhQTSNifnHx/5BDBT9lXyaserxzSQwjg6fzwy9HVFVsUUD1xQhFl6nEVQkw+meBX5RhYJSzQapoHHY6q4boHAF1pQKowaIckCyuphAck6CEFvDcQDhsJgyYW6XCufEXB2rJDY5OdnyE4NaAepFnOjxZiA1qQkzNU9qyadRzEwCOUeyiJMsjiTV3OOBH5ItTQduN8grMe/ZDj1uqgVcHcDQJmfjo0NawyeM0vtUDIT6PQO80+GfQ+J+nZAGEqhsln0nYDFbHWqmnkeITOEdcRigYp9UCx2AGYMlNYlJvuh7YhHSd/oIoren/3FT5mkqhRJSjAaI20PAuALVpEaLwpvN/ldBJw5mESTXLqw/msX2PP4/ZYP7vKPZk326+MwtVkSlmQP4YWPBlPekDcwM/yK9mQgk6mQGXbTjsskFUMW+dAYyMRS+EYNJBrlGbl2riJ2uSYGcd+CAK6EeEGlUO7xEfl6chkOEEq4ufGQZZhHXspA88k3nHIr3e4o6yNZ1oXTwlzKsta+3c1o32J6f1sa5l83FKFR6Pl7rKUpeviEOofb2kPv5ZlXhr6UFT/GJSZmVvrZ0FHbIXO0jvOsD9AWxy54HZg7CsW0tiXGVmTHXo5puRo47xr5ux9AlNuqwXVHlhNkvC7d6kFHKU0E9+z+Q7g3z0Xot4i8sS5ISm+2htmo9puIe4v6OaHUxmp6HfbXHN5j5YQmvwoOoB9pk2pLU
  template:
    metadata:
      name: ollama-api-key
      namespace: ollama