ingress:
  enabled: true
  ingressClassName: traefik
  hosts: 
  - host: ollama.rostor.cloud
    paths: 
      - path: / 
        pathType: Prefix
  # - host: ollama.rostor.cloud
  #   paths:
  #     - path: /
  #       pathType: Prefix
  tls:
    - secretName: ollama-cloud-tls
      hosts:
        - ollama.rostor.cloud
  # - secretName: ollama-cloud-tls
  #   hosts:
  #     - ollama.rostor.cloud

ollama:
  models:
    pull:
      - tinyllama

persistentVolume:
  enabled: true
  storageClass: longhorn
  size: 30Gi
