ingress:
  enabled: true
  ingressClassName: traefik
  hosts: 
  - host: ollama.rostor.cloud
    paths: 
      - path: / 
        pathType: Prefix
  tls:
    - secretName: ollama-cloud-tls
      hosts:
        - ollama.rostor.cloud

ollama:
  models:
    pull:
      - llama3.1:8b
      - mistral:7b
      - qwen2.5:32b
      - codellama:7b
      - deepseek-r1:32b
      - llama3.1:70b
      - deepseek-r1:70b
      - nomic-embed-text:v1.5

persistentVolume:
  enabled: true
  storageClass: longhorn
  size: 150Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rostor-worker-node-0

extraEnv:
  - name: OLLAMA_API_KEY
    valueFrom:
      secretKeyRef:
        name: ollama-api-key
        key: OLLAMA_API_KEY
  - name: OLLAMA_ORIGINS
    value: "https://ai.rostor.cloud,https://finance.rostor.cloud,https://ollama.rostor.cloud,app://.*,chrome-extension://*"
