ingress:
  enabled: true
  ingressClassName: traefik
  hosts: 
  - host: ollama.rostor.local
    paths: 
      - path: / 
        pathType: Prefix

ollama:
  models:
    pull:
      - tinyllama

persistentVolume:
  enabled: true
  storageClass: local-path
  size: 30Gi
