---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: prowlarr
spec:
  encryptedData:
    API_KEY: AgAODDOuvS0a3qjQIMv3y3Aoi6AnA2ZVI4w3oDkEDJrCFXRN/vYqRmmtp93SMnWzcCcqAi/K7bME0mW/i08LjZ4QgUjAliYLjJvJdK0r0K2/BNmNxI6Vfzs1H07AvohsbxnkABgU+he095hQ/R8dny93OJHbi+u6B+aGrX2PTyxe7tM5LNWx7OqLAh8gFCtb984jXNY/ZFUh5R4OGuYfqo9Q/wINapKSubd8q1OUEzGZu4mW/TEreoEI9bhjLz0DZMQ2rtmdjfPCkPguZ7ETOnYSJWNt1CoBNfklT/U6+tUIoFeyYJmgMuznmNYfVlr844U1ieul3+n28+xzAY81GCmOYw+EseKu/pGtZ1TdBQ1c5DOG2mUlBaviL3StERKKvxStS5T5TfOhPmqmizKqNrSmIvpCIuih3zEwKYz8iCrs00FwkjkCC9H25Jh0HZTQU/XsaM/rigLDdWSuZfGWZTmB7g6NwUzED6XxskNbyUplacowHervLUQFcmbeeq1aUvjIF/cdEP0qOBORKfdf83076eP90dVgln0NEdXe+cfRMMtqnq31WWj9jMfhvCfvTgrg/HCg4ohnBGoWhBnswQ8CsMrpE2ppf0pkaNbBfYR6YW9JViZqS159oE7C/MqX1iglazNxY6abbDg4fp5kjw6rOmwXY3gNB2mnhARZ8pnem3WmMYN6e43yetp/pSXHm2KtUzv2IQz9+h1gKszXseWDWj8Ybd2y/g==
  template:
    metadata:
      name: arr-api-key
      namespace: prowlarr
