---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: prowlarr
spec:
  encryptedData:
    API_KEY: AgCf5ZVS2HyfRDlf3GifpmFvkCBbIQFcFVBg2q00ygoKXzVQAkNei7a2oLTAXkQBKoa2iZxHU4Ml5kWTFUTzxLjm5EdB7s5VWbC3OAkZOzuCtbKk46s15zrKQYdMBr/HsDOUM6HI8Vb7Dze+5Rbwuz0yHiHJlBWxca5eZro72pMNqMx8jdtS19yXa0M8n5oY3jpUv61TyQzUaeUacrKcimJ6ZEcWBo7PlPE8wYf49cdcfgV/1J8tYeuvp0/5LaYOlBOseYWgK3Gg56eMS0ABoDbjUy65p2OxUg/ZCGUXC4M3BQrbsXZ+tjMaJJOvN9Lf6XRMPbrnPG0aJehdX1fT3U7EcBmB+UiAzqPr2vd9xQok7EjKsEpEaGJB5MZmLIY7Je9EA5Pz0GYdfI+HjeIGmqxF/3syU+ZvV6OtBBI5wUll1YcuedSfegt07crUjOqaSKbizPfJ7TqVHgtzNTThLfzvdPPqvkh4ILZQpQ0g9vpkDOLN4qqbFbQLX8BxUhmFvBL56C75LKo+jAUa3O5SR/ciy0gT/5QUjBZnk/2m6vAu/AWmoZDEvAOkCHQDk+24OazyZuGGtfAHMws0bFdCpZy6gBAfIcuMndPYtQzEx+CbSizQa1GCIojD/59Y77aXrL9ta2e0v/bwI2+pPXb5eq8+ocayN82C50o8uMo97/C0oogmBK0J/u/X+SkWh8WiBssAPi7w26qUgEb8IvJQeYKUZDlWOI0iB8hGm75MnUtcw7SJiNbGRYNICEKPxjaj6mH6Nn5dVLoJP2xWIUjEmr9e
  template:
    metadata:
      name: arr-api-key
      namespace: prowlarr
