---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: prowlarr
spec:
  encryptedData:
    API_KEY: AgAi6V4Nx9VvxGRX9UO9QTjGnKgQKlayyUlbB5xvOcY46111oqoxdDGK8je3o4Rrai9J0SE3/GOTIb8sUAA6/lWvukBBLyZjQGvuWJHrWkUbmwTaQIeFYFf8zgYEH+xrf4WbgP9car4QxfMUZx9/R+JzS4MfjYaaeizZcDeTHmkVUoluIQ1N38a9zDXxkUWsuxTzrjj4Oub8TXQFrFE2ZrKSlPxjmoncGCiXyPUrLYcpM1AQ3yt1TS62DHsmE/+oJgDxtz4teiRmrQJOp577XoJXAJU1WQvLInkXCShRHabxb8aTMGEOp0m5RrRGffgwDbA8BNyfx9MeJkCAFx1rJE2+tfN2cm1tUsOnbNLA4QY6hMUFfjkBiXDsrPbRQXebvpxYzpGyEmNc8AaJPh2e1H8yRcIC7JsmwrY9okd9eN3IJMGz5HnrcWaNetCVIaYTD02D2l6hLfqvRPdHGIAulQA4juYPsl7GOoGbjL7CfHgqTZ+MfAYiiIPGPex+MajQFiGJDqDBgVBHgmNNOrxeYSHTkaegt7ysx604KYqUA4tjcAp7HgR/cW++2vEaU2L4JtouTS7WXPBh7Wjyrx+ff70wgHH3/rdnNGZT9OFAX/fj+0mpUL2szwBocj2BAb5ZhExR4ufqH/wCJ1xrDl6uotdFrVFD9z1tonJBbs+KzwMwKmgJhe6JRDMx7S3NW4yz+QtwO3ba0h/lDdEL0hdSPJPuITZuT+FZyLZK4Hxxdx8V2g==
  template:
    metadata:
      name: arr-api-key
      namespace: prowlarr
