apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metallb-controller
  namespace: metallb
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
      - metallb
  endpoints:
    - port: http
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metallb-speaker
  namespace: metallb
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: speaker
  namespaceSelector:
    matchNames:
      - metallb
  endpoints:
    - port: http
      interval: 30s
