---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karakeep-oidc-secret
  namespace: karakeep
spec:
  encryptedData:
    OAUTH_CLIENT_SECRET: AgBt7jKFpjZmMmj+OXcT8+60RsZeo2fePXCihzacxa5sTOwac2U2L0CVQqf39bA6Os0JSAYAgWoXAMrTyzoBLsLIv1Tf6yYWgM+3b3FNiUNZGFROMTQHaPmPeguYjkBy5avlJXONVd3GlvfRaojQLMkHqFJ5EtnoalGvVjMaIfA3XopJn0vH3prHA0Q4X79LSsWKHleoO09RLNwJPauvVfxQE5Zf9GziLL7g2MGGb4H+AxAUogfrF8GmF7CdGVDmHkEEo+4smup4teH+rlx5S+cuGdGJvtRO/sVdHkIHDcXglzovZ77Cklqy5XZDVptocEjqpfUtz6RyAw04vysldWY25iCWcP/aOCRlA8ayxRhy9++1NG7xh/cknOtNBYS2ZfM857v27/bX3Dk2Qcwrd5FDsuXxMyJXhCMgGFqE5128ZFkJoFTYBq373ToNsZYttUkWIjlVOt0GgAbd1n9IcB0FkBM+Y6Ug2iKVTKzk9kOFUSHGBDJjCWyZTaS6XJ9ierTHFk6GrwHyzPYJuvVaRMmenswc0QdbNWwvd2/8aRQrH4CSHKho+9/UgqzxwavhdJchAf+noQcSlF09PMXO3w3h4vfAskyE2BHQ2tOG4ZewQ6RheTleHgFXUYca0lQsfIwIy4ThEZI1SjJEtGWJ2maHBzoyjS4xR08QXjEIXuvTwI7izGc6FZMX7Z9quETMpvQr8xKYkH/eIyUBrU/540HeNME6x7YBHuZZQcMvsKz1D6sg8nkAOzMLd1AEN4vi0XXEDT8CDVRdIJuj6tYmGvrea+f1Jbwk33slgjvRIoFj1lXaka/2E0Qf8dqlcgcBgwcJ8X3Cb/IwiYxEZEpC7JGKirWSrkMRL0Swy2SagkkNSQ==
  template:
    metadata:
      name: karakeep-oidc-secret
      namespace: karakeep
