apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-oidc-secrets
  namespace: outline
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgCCa860uI1k8SnwvDK3HJ8rfClY1ovJObk+4Z8y82tiG9bK9N7bz38uA14EAOaoxdBYrMshOhxJN/aL2lk9P1a2s/tL2h9oEbKQGq8kAJzfK7nGtSMY9sDmwC9xUA0w4Ja8jBP49YyLjX1rkT5Hrcd9WMNKSKBZCXNNqra+qEwkhvROjZYASCsLge1exBkaOT0bVIlXQWoNVcL0KdsxKWI47b39QTx35HxtUBaug0DuO4fDsgD55pAR9HXhn1N3b0OM4KSggaC8oDC6WInWimb5YF/2lzYs0ZuZnoxJ8XXoGSLVibVC779vxsgkr3HKmHzhCnvIclUqbhGok2IlgNyE+SlhCijBlJuZ83/EVfpmpFsOznPoPYWWmkUWcnk8ymkBLKXMsni4ivnQoNRa2tNs3gKQxYixQ3VbotT+IoJp9aoOPoEj1traI4+48sLhP7B/R39Vec23tjaStCCd48cdLwvHj45yfUzFA1uHUCzxsRVTK3bc2PIK+sOJeWZmSB63R5on7n3bAqdpRJwSFXoXJUTDCuMA2LtUUPpsi7KYj1TaXxGnNxKwI+88gI6vyoubJOcPkhGYaUhEWr02KSUzUFcK/KH1TPftxWEaVtzxbrmv2cUj5rpQhEhlWwHRql5Kg/ovGMEd5T88WC33c/7xI00ww4Tl/qnT/Xta5tvhcSAWlXEUN4LTi+Ak/Iv6fyZK/TdOIVFIAaDo6AZf+hqofRmrt7LaGIVplKxHDhiaXmsQNe4yxw7rrBW9aIin+QqvORxhUomalpCB3RZDxGsXOq3SDxWFNCZxRs9+RAaD0Ae/UATiLuhsptFDus4tlDAFhckvjT7iDU+tGCabbJ9p7Hj1OKRVMsUX5t43hvQgbA==
  template:
    metadata:
      name: outline-oidc-secrets
      namespace: outline
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-auto-generated-secret
  namespace: outline
spec:
  encryptedData:
    secret-key: AgBkAW9LtC9epKm33KJ1X+FWeiSQOCj7IALn+dNw3dac3FcXvxt1IhAPrdpFzA653A85zn+8xbmGSVlPCxJ7JWbVpnxkoh7ATD9M+3G4Tmx/DsZ1Bs1Jd42U1Wr4wt//wFbNExwpoBWKisShevCNWWidXG2Q5QS+VBAymqlA/GIEkIfqi11FwHsvQCwbQQyttTpldotnog0/nPsq6fAf6bYcBb0dwlE5mTk3TFqcfSFuWeDmP8IO9Vc57lnXAUf9tKMj4WyYynf2qcb7weDF+hoGze8DhFTUZy8xph+pHCDZ77Pwt0G7x3DfLqCC1MGnRQwOUwFEBpcOcPNfU2zF/OqkqPVhzk4WCUBNe3wwNNjU6UpMqvWk5R4rh3wmQMAoFPO7j1jQXFFjKvKgVHCnQpta0cSMs0t6dVOkV3sfcs7tH5+BXASR6MkpfwNsIvmQcFnb8jTGgN1Lox9DatBR3qbtBXKzy+zoryBia+h+BO2fRptxKo0JoOhfgt9pY00NcTarugZCdk1eShZt2zo+7SjHeBlXUVpLlQeiLwRRqpNFLt82xjddA3BveFHH3TqcTvVOuU8ngNuCNqSU2j84secDvP+t7bYBOhu/RVBt0OieZ8rKKL8c08mJ+4OyFXyhutc1CSnQZTCOEOriTlTW+WXRgyD1969r34Xyq/LoXJRAWv94BoTCiZM0iRHeuoEaKy0ROCno54GdJOP/XGwqvoYwvZiLv2DM5iunWY+xgAQYBP8M0DBJDpR6i6/aKg==
    utils-secret: AgCBCaQQROcUdD6IQjbp73PBAlGs5jjDBgYGimACn3TjAPt/JGe2NFyjDjkAtt+foPdRurRCnWVAc3XYmM3/0VZeHMqxeQ6BcIOPaNaGQuwPDiZBbt886Pwt6ipMg46ZioxzBqyqvR0zJdLz+8vK21fTo2rOK4ME7IkpsPB6ks4GyQf/ZVrT+0nHNcsUkrYtr68QklLSibPO44KVKE0AS1nyi61QkACMZ+GDsDWYjtws5/a7ilW5v4byGvpUWID1MyZuq7bNmWWVChsDfxYx6MdBfWgSQ0I+cloh0kRivBlksNA5SPBR07k9AcXG9JHLvK069lUQWU6oxyrVU5ySmm1+BHQ4dU054B5mUp2Z2zP9lhuq5PoDl/FLi1AUqAoBhNQ9HU4gACKzvzPniBprQbCaM7ZeUR0UZG8Z+KLMyDPoKEkMbPNwkpSQMaWLaTVqnydK7gJ37dglQ7QzTqxPd+d5HXFNXYNMZ559UUrwCqiG8r7Hmt3nKb424miEnVznX3T0yd3VnULuUmLx7NX5uSuxGJO3nZtJYjPRlXWA7IRtT975sA5fIYXftcVh76jA/2ucpXAA+7Var4YMixVTyFOiINoofCd/dGJlGjybCw0aS7hg8aw2ak0HUY5UCM2aKqUOeuecJnwZxcIdhBtIXt8cy5PaJpixmODGmxdX7o6jjNKAiXSMgCtXsHLSlafTXdQhrca/Mfr3EachMHERcde52b+C59jsBbJQpNHOF96zfJbNo49iKb2NZCmnkA==
  template:
    metadata:
      name: outline-auto-generated-secret
      namespace: outline
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-postgres-secrets
  namespace: outline
spec:
  encryptedData:
    password: AgABnPXi5nvZjtDDE3wKTu4yZVch4N5L5Bg0musESgEE8Y8JDoHduunFsBQTQxVho2g2jcMCc4WcBHdi84TSQmdCgvLYfgkYjuosIHo+6RWLNbHhFpT9Va5WQRHIJg2aw5v01K4iakJHG1qTAR2oDBrhn9Gj2ETcZOzS/R4FHlGmbrO1fhLqZ0XbToG2C5CNvM4OdTAYNhOzlrDXEmKd3/htx/7j6P8jmPCDOL+UI1w9iyzeMWoCi+lpbAq0yheIuDwGOUttgAkKXXpLh6xUCmagDdcyyhgFDfHqASNybkZJRs6BnSnkIs1yUi8H+MWlEIjLgllfiUrwTDYeuAYP+7AzD9KiZ0IPbYXfcv9WYNqNIUntXbxqZiL+zt55tIXvH4IOcBLMnc2TdNrOHoTXAU+vGfSH5FTBMTwRedCZA/xzGYemUg7AJZemYEncOS8fRjcKb9An824P8iVEOAs96GOvBsUYN77HE5DwkuhZe+jgSRMGmsXaSmQMkmVxcQRJwdVyxYMtetDYRLVl+chTjHuctzMy3TV/BGcntTshuuvY3nlGMRdZP7SddGosgeWrEJLVS/XcUPrwQ+aggXleouZd4aYbfv1PJS2RPrSYUXnc9AaeNto6xY5//KToCqH70/EC3ec9BJ1pKsyDY8HUUQBHuMx9xgUTMt6a7rkk1UCj4ONfhXLaxD+uM7X42Cd79A8z18853ifH8HiSA31yhacUMbbXCNHqG5nMZJdn/Sje4J9jjEUjfhvKQ6foMg==
    postgres-password: AgCRwHJXu4xbeYdeKXQYZsZFVDg4weqos0rL/tA9/W5/rAxfJoIlNxPDzffkh6+1i8GgbjglMYV4eApTkLEXNcTeJzw5TAol/OAJpg60xL0HGy2lxLt9ySKBLPn0CT/3PN+g7Is61MmSOf0Ic0GkSJzw5cDKBm8x/6nwL4qdLKMlpRy/NaOI9iy9DsI+ahSOrUcJ3UnlCNMr8mNuDsAQ1d94xEWmfwKhf7U4fH1D0otFZbFPiK42r8citLWjR1/Rn2zqi54mHh+ZE+iu56lDzJDJftz5bml1j721IGOeKAGOGYfFX6qGOaVR2OPlIHxMLjtJsnCFfS01IHNQxkeeotYI0vwCrpSzOnnEuKlWlA08u+V9055u3qIIiTDP8j8V+e1VR7zT1wFAgXUYscvV6pD7mk1SiWyo1tIFcQN7My97Z5+IDBbforPiY3XsqeK2iB3Je2LMzKoDCeh5NLahvIeiAN2CXOCGxSQ1lBF6wBiTSjZhVOjSKvY6q4eu7GShunowoB9RXzQupkEovHeSsz0/5EWCP2PXRJ/+qcoD+UgZh2dgcNN48W/D8b+18IwiYmz3i29pydSedlDIyU6fYzVx1/kZw/Krv6fsYU7pkybG3EcpCy8Rzzi4pixZ8dJpf1fQYBGXqrOjwMPhDVD4YhnDM7ALgEVwDAUh22hzm3uIo6TH3vDR7x4a6V02VrAtPSZhCsMlm5vfgmhNZ4huAJg/JY4cEPT3w8ZV8jsKZS2bgibDegnxpTSpvpy1ug==
  template:
    metadata:
      name: outline-postgres-secrets
      namespace: outline
