apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-oidc-secrets
  namespace: outline
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgCCa860uI1k8SnwvDK3HJ8rfClY1ovJObk+4Z8y82tiG9bK9N7bz38uA14EAOaoxdBYrMshOhxJN/aL2lk9P1a2s/tL2h9oEbKQGq8kAJzfK7nGtSMY9sDmwC9xUA0w4Ja8jBP49YyLjX1rkT5Hrcd9WMNKSKBZCXNNqra+qEwkhvROjZYASCsLge1exBkaOT0bVIlXQWoNVcL0KdsxKWI47b39QTx35HxtUBaug0DuO4fDsgD55pAR9HXhn1N3b0OM4KSggaC8oDC6WInWimb5YF/2lzYs0ZuZnoxJ8XXoGSLVibVC779vxsgkr3HKmHzhCnvIclUqbhGok2IlgNyE+SlhCijBlJuZ83/EVfpmpFsOznPoPYWWmkUWcnk8ymkBLKXMsni4ivnQoNRa2tNs3gKQxYixQ3VbotT+IoJp9aoOPoEj1traI4+48sLhP7B/R39Vec23tjaStCCd48cdLwvHj45yfUzFA1uHUCzxsRVTK3bc2PIK+sOJeWZmSB63R5on7n3bAqdpRJwSFXoXJUTDCuMA2LtUUPpsi7KYj1TaXxGnNxKwI+88gI6vyoubJOcPkhGYaUhEWr02KSUzUFcK/KH1TPftxWEaVtzxbrmv2cUj5rpQhEhlWwHRql5Kg/ovGMEd5T88WC33c/7xI00ww4Tl/qnT/Xta5tvhcSAWlXEUN4LTi+Ak/Iv6fyZK/TdOIVFIAaDo6AZf+hqofRmrt7LaGIVplKxHDhiaXmsQNe4yxw7rrBW9aIin+QqvORxhUomalpCB3RZDxGsXOq3SDxWFNCZxRs9+RAaD0Ae/UATiLuhsptFDus4tlDAFhckvjT7iDU+tGCabbJ9p7Hj1OKRVMsUX5t43hvQgbA==
  template:
    metadata:
      name: outline-oidc-secrets
      namespace: outline
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-auto-generated-secret
  namespace: outline
spec:
  encryptedData:
    secret-key: AgCTrvWcjEWlI6FzyK/RMC2oUQKYEQWpoWPnQ/1gBmAVdUKqz2tZPmFQm9Eeqy7Esfky/m9foofhz4OjbtKcWPO9A6jSCWq+JlD3AybAO/Bw+ydvFXbbl+3EZfKgx2Ybl5ZyC4VnxjB+JjrHVNzHpfCb4ehL+MgSlrCj3MoQGLZ6n6gmHF1HDWSH1tKcop0QNL4AVW7fYHRLaIISFoJ0zp2Gov1FYWGGwnihT9/vzmtOhXRmky+6BP1CTxU5P1/mD73xgW0OqG3rBSXcXSxYE2ELaKrI/Fcq8KqK6oRfaz/vI+56SbMkr7Svxf460j++j+x3PCMvjJ2/fYerN6l8b0zfcGczJZZGbBWTA9yjDcmjOqqk8WwxFNxq6Im/izzWPvP5GD77apT3bHcBseU0FyLOMdBmn2gJF6+dMKAU48lMjgrmrhQKR7RC/tzfyAI+tP9jzbwQBvgBXn32Jsa8RxYhfUauz7DJZ5A+54AFVIseNT4rFrq6Q38ebbSFzQ/jOyKQWjLwV3ntV1B/7ohCBjyAsCeC6GGkAIzO/s+V6bKlgYZP2M9WIl8ecm5PcmGeryLc1NYUtkYdywLVsRW6EqoCW0dhJ5RbFEt6oKj4J6gmDE4kUHAjpKTznST59bUrXCNutl5M7mitdOrNMrciz97rJP/4f8S9jEYsWcPMKLub9AUgerv6vmG+oBlvU/6jIUDPP0zI3VoeEqNPdwSfEc0JgVPTJcfazfxe3dR9fbJlIU9DR/D7GXOZSbByrps0DoBkuia28JkiZydCfNTaHAM+
    utils-secret: AgB43d8a0WDnGMczq9EHUuaNFfAypEiEC3Nl/5Ay6ftUeIqWut8ELZmVbTc8JR+Ek34oMjMbyyphZXZxw8JuFu+9s8aYxFS7lc4gyVaWirjVUx52BaTAGs1BkQrcd26piiDYCub3qNqS2sRtrmPWnKH8aFeOWPFQuRA+NfiExwtphizjhjL8fhodnxHzGo6f1xToPiXvMFwbOsSI34etgonrEZ0pbccvONnBm48zgIgzpOpAZvxaaO80c1gGNbY9H/a9/cBiB5OgQ2xjs0f5wTFxvcztNpUkMJVR+cbRc78Zj7XvbED+lR4Fh8rqXU5e2zglL6Ug0282I/f/686SVd8CQ+lwK30YjojJ+4nqBFXXN2yN72lQVM5MEi7CtaxCegK32ngJF2FimmVoeBSCVwST7tNeL2E+WR8WsCPNSSaSGOaTBmIIMm4MnI+v2wMiG06rU0djJxkxyxNkmJfrpBj0rDv2TH5ASSEVZgc7jf1VZdLAy3z4JRJJJBr59yhJwCC6mMA0Jmro+kk2rs8DEx8Mc0mSet6ns4dZbUIHPabdWk8vaMReZce7/AFzNxDNHh+mKZrb+TtoH8FmuqjF4IkokLjOhKUcDR79YKclGShN070dOU5fbecA2gUi20BdgkQX+58lzjcrcD5A1L6k6soItjfa+RpN14dyL442j0csJqV1Mouft0F5tXhfeZEBSaRPwpBLgFEasy+eQ4Pl9fLLWQFF45JDWvALlltBgdyRVb8Jw3RE479RaZJJMg==
  template:
    metadata:
      name: outline-auto-generated-secret
      namespace: outline
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-postgres-secrets
  namespace: outline
spec:
  encryptedData:
    password: AgABnPXi5nvZjtDDE3wKTu4yZVch4N5L5Bg0musESgEE8Y8JDoHduunFsBQTQxVho2g2jcMCc4WcBHdi84TSQmdCgvLYfgkYjuosIHo+6RWLNbHhFpT9Va5WQRHIJg2aw5v01K4iakJHG1qTAR2oDBrhn9Gj2ETcZOzS/R4FHlGmbrO1fhLqZ0XbToG2C5CNvM4OdTAYNhOzlrDXEmKd3/htx/7j6P8jmPCDOL+UI1w9iyzeMWoCi+lpbAq0yheIuDwGOUttgAkKXXpLh6xUCmagDdcyyhgFDfHqASNybkZJRs6BnSnkIs1yUi8H+MWlEIjLgllfiUrwTDYeuAYP+7AzD9KiZ0IPbYXfcv9WYNqNIUntXbxqZiL+zt55tIXvH4IOcBLMnc2TdNrOHoTXAU+vGfSH5FTBMTwRedCZA/xzGYemUg7AJZemYEncOS8fRjcKb9An824P8iVEOAs96GOvBsUYN77HE5DwkuhZe+jgSRMGmsXaSmQMkmVxcQRJwdVyxYMtetDYRLVl+chTjHuctzMy3TV/BGcntTshuuvY3nlGMRdZP7SddGosgeWrEJLVS/XcUPrwQ+aggXleouZd4aYbfv1PJS2RPrSYUXnc9AaeNto6xY5//KToCqH70/EC3ec9BJ1pKsyDY8HUUQBHuMx9xgUTMt6a7rkk1UCj4ONfhXLaxD+uM7X42Cd79A8z18853ifH8HiSA31yhacUMbbXCNHqG5nMZJdn/Sje4J9jjEUjfhvKQ6foMg==
    postgres-password: AgCRwHJXu4xbeYdeKXQYZsZFVDg4weqos0rL/tA9/W5/rAxfJoIlNxPDzffkh6+1i8GgbjglMYV4eApTkLEXNcTeJzw5TAol/OAJpg60xL0HGy2lxLt9ySKBLPn0CT/3PN+g7Is61MmSOf0Ic0GkSJzw5cDKBm8x/6nwL4qdLKMlpRy/NaOI9iy9DsI+ahSOrUcJ3UnlCNMr8mNuDsAQ1d94xEWmfwKhf7U4fH1D0otFZbFPiK42r8citLWjR1/Rn2zqi54mHh+ZE+iu56lDzJDJftz5bml1j721IGOeKAGOGYfFX6qGOaVR2OPlIHxMLjtJsnCFfS01IHNQxkeeotYI0vwCrpSzOnnEuKlWlA08u+V9055u3qIIiTDP8j8V+e1VR7zT1wFAgXUYscvV6pD7mk1SiWyo1tIFcQN7My97Z5+IDBbforPiY3XsqeK2iB3Je2LMzKoDCeh5NLahvIeiAN2CXOCGxSQ1lBF6wBiTSjZhVOjSKvY6q4eu7GShunowoB9RXzQupkEovHeSsz0/5EWCP2PXRJ/+qcoD+UgZh2dgcNN48W/D8b+18IwiYmz3i29pydSedlDIyU6fYzVx1/kZw/Krv6fsYU7pkybG3EcpCy8Rzzi4pixZ8dJpf1fQYBGXqrOjwMPhDVD4YhnDM7ALgEVwDAUh22hzm3uIo6TH3vDR7x4a6V02VrAtPSZhCsMlm5vfgmhNZ4huAJg/JY4cEPT3w8ZV8jsKZS2bgibDegnxpTSpvpy1ug==
  template:
    metadata:
      name: outline-postgres-secrets
      namespace: outline
