persistence:
  enabled: true
  volumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn

ingresses:
  http:
    enabled: true
    className: traefik
    hosts:
      - host: adguard.rostor.internal
        paths:
          - path: /
            pathType: Prefix

services:
  dns:
    enabled: true
    type: LoadBalancer
