---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAkZyJRAmaMmB2Z4BzLgKDF2ldRJbSEUffpcLTci+NLtAwnHuq3ZNxAMmOup9Id2L4sEKBD8Q/xuveuLtXe0zVjM+iUGOCyos2wE9VtRaVwj3gDNIKEBYnCxdZPua0Qan1E8D8ON9F+VumWkyWTxK6AKKrhm5Gm8811PbgQZ/PTjAom3YE1p6QHU1ref2kwwKAgA6w0dCGlRywUB/0WEFua9Y9t7YUHHqfOtn4IxANcf26d+XxW81qAwp9toGfnJTJYtXgDjhVzqkGJM6e+BIOsuB8+iWGLAQCmUmV9Yrhip+5pkjQ4YMMud34s/TYVPG2573CI8khcyMEZ545xe6i9NL8/ZdQEWrnV8PdtIyl0ymlwFMW6zoyTJC26R8YYadTfBWsJPJnrl+kBH1je++bF7zY5fp1iSETDOlThQ7GqRbqnjESUEqy2KjQFish9FlM0WqmVIH+DO1792LpDv1FKzDpRz2YVkDtApG2IiKlF0CqxoMs8ijZ5JEF6mG9nyC5J5H7nzmqRPLVyDXMUCb2Ftv8cDDpbJV2XqT1TYcuNYYSV0d1H1RUWz7xHWbnrcihiV4L+Z7uvLdyIhV79z5D6t43ZYt7gc36i81oWofTcalYkT58EfZywsH0pmdpxuXfW/fLuXnEbrzFVEoELX9F2DILtOCD7Jslxu/unqldIYPH/GrnkAodwbb1J/kJtjL5CzA77uVKS/fsTYLCfBsBsfQn3yma8H/kMBNP1TK6TzdBqyRAQf4lPK20DGWuwnVSmRqkc9g==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
