---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCN9Hq/NN/KNA84n0jrvxz6XKoSxThPgUTlEgexuZIEkBTucUwIeI0ra8vtrUrVH2HbSZ5PaSh7kxjl8+vHHJoPGQLa3i2zeQ7ZqD3oWhmKhBME3MHfJM7EqHzrfB8GwKR0Ge7S7Oo8rJgGOYyiLanMrHEEo0XkhngrclVbEQwhaBkyBoS2Uws1lZ4853nOMLb3Nv3zWr7ibTcBZs6HxZAlr90BfwJyuRpy9N/8Kt1W3/1oe2x7O77aVOwmitveNgvescxusY21fNzZivPCkFp+ALmlWg40+hSPL/d0oRh2ZUBWboWUkGHCLQxDoRn0Dv3f2bBXMixo6n5arjMf+VtZEHpplyddgN+cxuIhe6bMh/KWPhjpuoA6g6NH5NuUI9uHFOXtD1lh+JIMsR1dYQraOKD25meoLNdVOw3Wk/RE+ku9WEKKIKDyNRviRU9xNFOxKMlE+PZYYc1wlqQbS5Czw9/R+DdEE/2pdDh9It8mtHhhG/6BI0HUq7Fr8OSITqvKVAcGCSDavc8b5ac8ZzHv4P+pqr6alPi/lStykyV92prMZxAyUfnsQjfCR8DLvyanlN2OL7FVGb71ttCBaLtCjZXC7Z1U0aMslII3krl3ZTfd5XBzwtum0uM3PSh6SwELj9+tqZfV5Z1NJi/y5UuQTwcjF3le+oUxbnYOyVqua5vwOpvWMJEkZ0mb82w1Bo5q378HweDG2pEuYTTncoKNnVo6PBsifLeAV7h+RTAQb0x2tly9DBQEyYtZno1y07Oq9Y6Iyg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
