---
- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Create fail2ban local config
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: "0644"
  notify: Restart fail2ban

- name: Enable and start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true