apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karakeep
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://karakeep-app.github.io/helm-charts
      chart: karakeep
      targetRevision: 0.33.1
      helm:
        valueFiles:
          - $values/apps/productivity/karakeep/values.yaml
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      path: apps/productivity/karakeep
  destination:
    server: https://kubernetes.default.svc
    namespace: karakeep
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: karakeep
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jqPathExpressions:
        - .spec.finalizers