apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - outline-app.yaml
  - nextcloud-app.yaml
  - ollama-app.yaml
  - open-webui-app.yaml
  - homarr-app.yaml
  - forgejo-app.yaml
  #- ghost-app.yaml
  - sure-app.yaml
  #- stalwart-mail-app.yaml
