apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- nextcloud-app.yaml
  - wikijs-app.yaml
  #- ollama-app.yaml
  #- open-webui-app.yaml
  - wealthfolio-app.yaml
  - homarr-app.yaml
