apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - outline-app.yaml
  - nextcloud-app.yaml
  #- ollama-app.yaml
  #- open-webui-app.yaml
  - wealthfolio-app.yaml
  - homarr-app.yaml
  - gitea-app.yaml
  - ghost-app.yaml
