apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sure
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/we-promise/sure
      chart: sure
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $values/apps/productivity/sure/values.yaml
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      path: apps/productivity/sure
  destination:
    server: https://kubernetes.default.svc
    namespace: sure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
