apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sure
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      chart: sure
      targetRevision: 0.7.2-alpha.3
      helm:
        valueFiles:
          - $values/apps/productivity/sure/values.yaml
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      path: apps/productivity/sure
  destination:
    server: https://kubernetes.default.svc
    namespace: sure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
