apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- bazarr-app.yaml
  - gluetun-app.yaml
  #- lidarr-app.yaml
  #- prowlarr-app.yaml
  #- radarr-app.yaml
  #- readarr-app.yaml
  #- sonarr-app.yaml
