apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/bjw-s-labs/charts
    chart: prowlarr
    targetRevision: 5.0.1
    #helm:
    #  valueFiles:
    #    - apps/media/arr-stack/prowlarr/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prowlarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
