apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/bjw-s-labs/charts/
    chart: radarr
    helm:
      valueFiles:
        - apps/media/arr-stack/radarr/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
