apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/bjw-s-labs/helm/app-template
      chart: app-template
      targetRevision: 5.0.1
      helm:
        valueFiles:
          - $values/apps/media/arr-stack/sonarr/values.yaml
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
