apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.rustfs.com
      chart: rustfs
      targetRevision: 0.0.70
      helm:
        valueFiles:
          - $values/apps/infra/rustfs/values.yaml
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      path: apps/infra/rustfs
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
