apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: technitium
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.obeone.cloud
      chart: technitium-dnsserver
      targetRevision: 1.13.0
      helm:
        valueFiles:
          - $values/apps/infra/technitium/values.yaml
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/jacobdanielrose/homelab.git
      targetRevision: HEAD
      path: apps/infra/technitium
  destination:
    server: https://kubernetes.default.svc
    namespace: technitium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true