replicaCount: 1

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: wiki.rostor.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - wiki.rostor.local
      secretName: wikijs-tls
