apiVersion: v1
kind: ConfigMap
metadata:
  name: sitecustomize
  namespace: bookbounty
data:
  sitecustomize.py: |
    import requests as _requests
    old_init = _requests.Session.__init__
    def _patched_init(self):
        old_init(self)
        self.headers['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    _requests.Session.__init__ = _patched_init
    _requests.sessions.Session.__init__ = _patched_init
