---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: bookbounty
spec:
  encryptedData:
    API_KEY: AgBaybSDz4wOpnpjdnbJbIJEz2XQfPVnDbvA6+xUseed2IaTMlj9gEnsqX9HH3ZH+ALoer7G3QAz9Xmatvxd4jZYx++GLYRUGKona/ymUJYRtIkBYD2c/J+Vhyt7P7UzmDbcf63XoceNob4kHOw3ug+b3gUaQXt626oplgv9/P5afht+ugHsPZJdQmrGfGTNa23YT1mdN0wzZaZxJd8oKDMUGBETaDRoHQ6lRm2hvAxpPbI5MmNc4t+Zy8vtcgUPgZYgFIJJcEpZfXWkzVXDTzYtqDXMsKUbXKuPHBY7924yJ3y3xzvKXjF/bEfInyiEEU053kipsH81tu5YmN/fLs0kx40TKYscruw5pYFXIxc2O3lJocG9QTwC4rPz4ZDhJwuo07lw1jSQx6xTSw/72wtxIiQLUFXtJ6vlHcLO334UtVWSP5K2qrR001k5mq1JCzlEr0+u2R2trDv1Z1KO3Z86sBvOjJfdIECk1zwW+41msjZ6LizCvc5kvRvSvIJLtTyE/YyAWXHa5zq/ff6VBMe0PtVlomIiV13HRxi7XE+sQVgdB0pb3+pfqFMj4V8rA16Rkw8AQGnFJhiMi6jYgbtO5Kki6IUGawj4kJo/CBBBXqbgViauc89fmUrQCz3l13rfrvm1L5/M1cpWpx+eZOKz6Xzeq5EIG0Gid7sCL4QBmUMa1VGl7bD/JXTuxxy3/gtDkRwL6oDrL9U/Ek90Uiu/SW/h6A7F5rmccOexMhjXn2y4eBzab1KeSwNjFd9S+jGS+ZAwVKMcafSys1PKJx/l
  template:
    metadata:
      name: arr-api-key
      namespace: bookbounty
