---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: bookbounty
spec:
  encryptedData:
    API_KEY: AgCiiuxWnS/YGUlsDYlW2lVxVIljXI14vVmPJ/HyC8HpaEivFtRwhsgwJ8id3xv1uWGP5kGVtdh6GBZC98ScsbvJ2PR+VksQBIlhz4Okw/jXFJIGNfsRc+LotrHcpoXuxGa9kCp8Gc0ZgkMZ+17vq5Zzo+JRu7OLv5nQQqe8kHTiE3eReqHthCsRoVpYtHgH1xZ04ZeUGeC/CY4TC7nUSA4lGxKpf3ahpGfyNWMF+Rrjany/ffDznWCJCW/EmjTCxnT7BcvB38t0UvUJUDbQWt/RBr/V5Xi+OrVKBbI8uOq1Qbf6HAOtf40e89e+cONjY2gH2VxqEdX1VLzGPZMxXJjbmSBq/BS85LWh25KF4/DVqeSz/ykjMKGodKqziZZdwp1o2I0S6+qsA3qiu+c5snSieHCBtoHwjd7gOmuG+u762Bdk6RpFDbwfenLN9hjurOBrtzx+xD06viRifvQSRG29WO5axFmqdzVNH38Mya/TLlQg5fIYBDoP3vzEH5b19t139P0/aDTVdZG9GYLF8u1wpEy8Q08zF7TKgPgQyLk+OdWiaJqa7YgNCZ/6BrfFiY6MNnGF4kuWcUz0iA/f/66ge/PBFynIdDDvbpv9aNU6GW5ifq8CQ86K4r5bto3MQ8ik75oInG4RSR69dT7kPevVk/nNWTdv2bXlIL4nafz0orCsJR1uBB4KnCU/KNB94+vmjviUKmuF+TW2PhHZzpiRFAhV8wm8K1c80pCaEvwC9g==
  template:
    metadata:
      name: arr-api-key
      namespace: bookbounty
