---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lazylibrarian-tls
  namespace: lazylibrarian
spec:
  secretName: lazylibrarian-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  commonName: lazylibrarian.rostor.internal
  dnsNames:
    - lazylibrarian.rostor.internal
