ingress:
  main:
    enabled: true
    className: traefik
    hosts:
      - host: lazylibrarian.rostor.internal
        paths:
          - path: /
            pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
    tls:
      - hosts:
          - lazylibrarian.rostor.internal
        secretName: lazylibrarian-tls

controllers:
  main:
    pod:
      securityContext:
        fsGroup: 1000
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/lazylibrarian
          tag: latest
        env:
          TZ: Etc/UTC
          PUID: "1000"
          PGID: "1000"

service:
  main:
    controller: main
    ports:
      http:
        port: 5299

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: longhorn
    size: 1Gi
    globalMounts:
      - path: /config
  media:
    type: persistentVolumeClaim
    existingClaim: media-nfs-pvc
    globalMounts:
      - path: /data
