---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: lidarr
spec:
  encryptedData:
    API_KEY: AgC73KqGzzChOmrHSxJ5ECefXeXsa2LQVng9GP2eD0XngNJDolEy6ffsPryqzUTimP9UDGC+cnEfiBIaWj2UgYidSRcNvYi+r9iI8wgLejqnP2XEQ1x2NLlZgO4729O74ELOX+jCjr0VZHFsV0j9Zkzc9a6mIpbq14YKgM8/srbNtcgmGrKaKBV2zV90MyWauysZmFgOolHRYAy1/EGCPmc+WaVgus8UxixRbKhosEQG3Jf7duC3TCXNrFSqFskrvUZTsRck5w2f2G0qEaGDx779Q6ccdgEmiJIV87KfjU68PjJrBX1BTGAP+Pvj4do0hPTwJgfMFpSy5UVUrYMZ9iuvVHCWxLi0tL1tH8A4oyYXJTYpZ1esMywE9rpPh81gx10cvZYLCa+B74Qkj0L9KwTlJVxDe5WqgXCtTK0U6fGXMv1dhyPR1RBplpCqOb1J0XqO0bTV42xFOYzq1ilYUxIm5dTfGLpFGkadpm4Usr4gD1MzBFrg+0ZBcNUw+0ZV8QOSMUQO0/QnxKH2/zXoEDV/BNyrR12qtkWmig/1x49YHDcAX30WkbmGOjbCnvJb78XdYiDduaIxTfurlbpB/cUu4vdC/hvXV5+8j/kzpgcvk9sPwrsGgx+NMEtAnoi+slGWO+VnPQaWlYE+T5rhJ8aNXkv1nNL6cKAC0CWnaKYpjiA23fHV6R0scUtXz4fcEDEpw0WWWLZGlYVCc3DnaPZ6k5Edws82gTy/ikjy7h2xZA==
  template:
    metadata:
      name: arr-api-key
      namespace: lidarr
