---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: lidarr
spec:
  encryptedData:
    API_KEY: AgBVQM2/dFgkn1yO26s/0AGO5Yqz0hgAUq9CcUU791Nujy2optx9n7fcfrHBEBVbaXZ8pIx5Puch24vx/TK6seIcsESXt56Iueycg8/7DIbJJ81xxYT2+zLWPRk4vxSJlYKXpB6R3AhO1O6fWFVuH4IcqZpPQtcBkB/Y7un4WKOM0N3IUhWtg8t0oeg20YDUxuCcIjEwyKvJ2lSJlez5N8+l0KIkw88mEb44+K8XDFxRES3qX3XWWA5q/XGhmgk8G/W72c1mnpF7Cveuqt11c5b0Nca2XcPPa1K1IYQO3+XdJ0cbH5DlvzXG4Y1QC2Opn9tKuCc1lmQ4L8D8toSe24FFm0zzyhrHPVKTaB1/4nomCdEmOvHb5brWh6bomJw5H9l6DPq4/bfgGLZUItn01JlxXpBCwBqRQu3/OLAjKu6E3q3IZXi8A2os59ecvl24cw5kDyjVfcFMsmhYUYckJNdiyUXAlcGnjdwAj65kcisVrObGKKFHE9aXQguSRcKvxyv2bfJb/u6rCVVi0T+CgBY5JF3HIkS8QIwLJJjUsJdE9EYvmFjwRuwh2VhSmJtAa7d6sFd82CU26GZWNSRJJmOLJ87c3yHmqaG6mH8MtQHhEI17v2SrUPZnux2qqeRfV2p/mSp5dGcMG+N92JioDltQt0miR2E2HpFclbRgDNuBXAwXt3zqoL5ngm4g7xbzhtkYMawsqvgT01BjtkydKgZ6WeONmyZ4J4dsX7oGeTnhV0x/kpoM2NpIKNeRJOFVUIEO4jrtKHnYu7jiVXcf4Prh
  template:
    metadata:
      name: arr-api-key
      namespace: lidarr
