---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: lidarr
spec:
  encryptedData:
    API_KEY: AgABO8t3SriK9HjdY4+fMk6HuOaAppe+iEII2YBDBj0xTd4gSIcm7P4JKHkMRPXMpwt33quIiW2m9Gwrdk8nlkQLQ7CFLiz3w2ck1/KfZHFXcuGx5Rxs1qEl7IMJrABIsut2fgEvDm60Z/7bdNfUC0QaTXd8n/zDk/a3p3gSMy6EonFmZ9QTSeR+B01u4uAZl5arXmBdL/c5ZAC41J6j3+npb+W9dY5ZNvg3YDRmTNOBp71YA2M54SI9CHIwkzqIjk+nvBqgvzaNxbWjCAThJ2LUtSv7Oyy0lkN4HuJPHCjgQD6BXiDjchCt83f6r/89O/WyISKCxyNsP5DxBYiVTr0Dz+r3wFYgAr1dKHob3a2yYKAwWINx5ePsWw0yeu9m2gLbpbFLVdlsITpanGjBih77Dk5W/BmzeJiR6Z4odpAWy/CXddc+15MQ2lOMLZ1pzOIz8c4Vr8k+kTe0xa2mbFoA5kmbjhrf+g/ZnT1x5uemmFgmyRC2NrMvPDcf8ehAGxtUuw3MNmhERLgsd4Ql3Q5dU9MHhjJoBSzeUTmrmsF2bpEBSbS6bMUXriXpAhD7GQVGvcQmlnKhRHAzd1Rs9Jter4Ll/leEn/whk8kU3UTAEw6o2jWKCbXCoXyVu2K27uM7o1Ygf0GF5kHtiXU8P0wcdewRdHElKiyyP6XObddUqNOOj/hyPTK/jeMCMAGhDkBNP6teOIVLFjjxZpX3GqCp4ZX1NUdOnw==
  template:
    metadata:
      name: arr-api-key
      namespace: lidarr
