ingress:
  main:
    enabled: true
    className: traefik
    hosts:
      - host: lidarr.rostor.local
        paths:
          - path: /
            pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
    tls:
      - hosts:
          - lidarr.rostor.local
        secretName: lidarr-tls

defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/linuxserver/lidarr
          tag: latest
        env:
          TZ: Etc/UTC
          PUID: "1000"
          PGID: "1000"

service:
  main:
    controller: main
    ports:
      http:
        port: 8686

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 1Gi
    globalMounts:
      - path: /config
  media:
    type: persistentVolumeClaim
    existingClaim: media-nfs-pvc
    globalMounts:
      - path: /data
