apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
  namespace: audiobookshelf
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-backup-pvc
  namespace: audiobookshelf
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-pvc
  namespace: audiobookshelf
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
  namespace: audiobookshelf
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  volumeName: nfs-media-audiobookshelf
  resources:
    requests:
      storage: 100Gi
