ingress:
  enabled: true
  className: traefik
  hosts:
    - host: audiobooks.rostor.local
      paths:
        - path: /
          pathType: Prefix
    # - host: audiobooks.rostor.cloud
    #   paths:
    #     - path: /
    #       pathType: Prefix
  tls:
    - hosts:
        - audiobooks.rostor.local
      secretName: audiobooks-tls
    # - hosts:
    #     - audiobooks.rostor.cloud
    #   secretName: audiobooks-cloud-tls

persistence:
  config:
    enabled: true
    existingClaim: audiobookshelf-config-pvc
  audiobooks:
    enabled: true
    existingClaim: media-nfs-pvc
  metadata:
    enabled: true
    existingClaim: audiobookshelf-metadata-pvc

extraEnv:
  - name: NODE_TLS_REJECT_UNAUTHORIZED
    value: "0"