ingress:
  enabled: true
  className: traefik
  hosts:
    - host: audiobooks.home.example.com
      paths:
        - path: /
          pathType: Prefix

audiobookshelf:
  backup:
    persistence:
      existingClaim: audiobookshelf-backup-pvc
  config:
    persistence:
      existingClaim: audiobookshelf-config-pvc
  library:
    persistence:
      existingClaim: media-nfs-pvc
  metadata:
    persistence:
      existingClaim: audiobookshelf-metadata-pvc
