ingress:
  enabled: true
  className: traefik
  hosts:
    - host: audiobooks.rostor.local
      paths:
        - path: /
          pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
  tls:
    - hosts:
        - audiobooks.rostor.local
      secretName: audiobooks-tls

audiobookshelf:
  backup:
    persistence:
      existingClaim: audiobookshelf-backup-pvc
  config:
    persistence:
      existingClaim: audiobookshelf-config-pvc
  library:
    persistence:
      existingClaim: media-nfs-pvc
  metadata:
    persistence:
      existingClaim: audiobookshelf-metadata-pvc
