# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: komga-tls
#   namespace: komga
# spec:
#   secretName: komga-tls
#   dnsNames:
#     - books.rostor.local
#   issuerRef:
#     name: selfsigned
#     kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: komga-cloud-tls
  namespace: komga
spec:
  secretName: komga-cloud-tls
  dnsNames:
    - books.rostor.cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer