apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-config-pvc
  namespace: komga
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
  namespace: komga
spec:
  accessModes:
    # for actual deployment use: ReadWriteMany
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
