ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: books.rostor.cloud
      paths:
        - path: /
          pathType: Prefix
    # - host: books.rostor.cloud
    #   paths:
    #     - path: /
    #       pathType: Prefix
  tls:
    - hosts:
        - books.rostor.cloud
      secretName: komga-cloud-tls
    # - hosts:
    #     - books.rostor.cloud
    #   secretName: komga-cloud-tls

persistence:
  config:
    enabled: true
    existingClaim: komga-config-pvc
  data:
    enabled: true
    existingClaim: media-nfs-pvc

komga:
  extraEnv:
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTHENTIK_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: komga-oidc
          key: client-id
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTHENTIK_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: komga-oidc
          key: client-secret
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTHENTIK_SCOPE
      value: "openid,email,profile"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTHENTIK_AUTHORIZATION_GRANT_TYPE
      value: "authorization_code"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTHENTIK_ISSUER_URI
      value: "https://authentik.rostor.cloud/application/o/komga/"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTHENTIK_USER_NAME_ATTRIBUTE
      value: "preferred_username"
