ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: books.rostor.local
      paths:
        - path: /
          pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
  tls:
    - hosts:
        - books.rostor.local
      secretName: komga-tls

persistence:
  config:
    enabled: true
    existingClaim: komga-config-pvc
  data:
    enabled: true
    existingClaim: media-nfs-pvc
