ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: komga.home
      paths:
        - path: /
          pathType: Prefix

persistence:
  config:
    enabled: true
    existingClaim: komga-config-pvc
  data:
    enabled: true
    existingClaim: media-nfs-pvc
