# Traefik values

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    http:
      tls:
        enabled: true

ingressClass:
  enabled: true
  name: traefik
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

api:
  dashboard: true

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.home`)
    entryPoints:
      - websecure
    tls:
      secretName: traefik-tls

metrics:
  prometheus:
    addRoutersLabels: true
    addServicesLabels: true
