# Traefik values

ports:
  web:
    port: 80
    redirect:
      entryPoint: websecure
  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    tls:
      enabled: true

certificatesResolvers:
  selfsigned:
    resolver: selfsigned

ingressClass:
  enabled: true
  name: traefik
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

api:
  dashboard: true

ingressRoute:
  dashboard:
    enabled: true
    ingressClassName: traefik
    matchRule: Host(`traefik.home`)
    entryPoints:
      - websecure
    tls:
      secretName: traefik-tls
    annotations:
      cert-manager.io/cluster-issuer: selfsigned

metrics:
  prometheus:
    addRoutersLabels: true
    addServicesLabels: true
