---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-secrets
  namespace: rustfs
spec:
  encryptedData:
    access_key: AgByNsoUcuf3SR5z2JGTB8t4dA3S5eiB9adNh5CNsMoCYLN1dXmED7ZfkyZoI/noeU7rvuB8OhEVbO1jzG6CCm7Q090o/2njwk1Bj0K2CGqEcDz7vCncWeJoELxevP/V37V/wmnNTePjUm2d73q2o2pKu9G3leGx4IX5gvaWFzM2qEskbDVGrSi0f161XaxoiGYxHvu88YUCYYkvuQurY60gjTxVg4FYaw8IKzDi/OhZ6P4DiOYte4q+ztl+iVYOg2wMg7Z6zgjj3LV1gJ3eIH0T4vBl3u4Oi9IEB000TkbnrUwsHpOaBhQnPelMC9NRlpPvYYJSlqJVvQTBaGxS0W9L+ItucPJLOBXY0P41GgvZsNYk/s29/2oYxkDKqR5ePbeTT2eoVmtGJ+eHi16E4YSi7YoW+XyhSxWQOzB8UMb8bGLnorP3SGqHxDKuMNLCjWzgg70FnSWrlkkFTISvBtl2RxuqRLYeAhJ2217/TCOZBPmRv6TcoYcHVtzF9gNqzEa4ZDF0slyEBrGCdl8d8nRYSE7LVlzJX2LDd84I53m3WCRwJZlK/PY8ahFGGzwrrJRmyMcmCzPkIE6xwYYTxmY1GTyHxVTio37e6MDD49A8gZqji9vsd5roz0j8hi7dcugkatQYB/7DEELfIYtoQaMo/hA+X8MUu2EDkVVzizxeY9QN++0at+WUlFDbHeRMpkDIBSB5KVUveteF/ABPynEUSq0d7Q==
    secret-key: AgCvCcKLKUuPOjqnnWvRMalibKCLTsMbkYr+Lwe4z3F5VLMkwgud4S6Yy+rV1jpb/c7acERxy4plb+91eIC2RHTUa5SnU6oAqchdZTb6+emMKBO9U6z7fYB9+lqWcAZ/V+6QALYEVD5qaRE9HVXGD+/3g5NuqP3PiOHZ6d+fBQR7XDoAkhsZSM1XdLZJ6UR5qou63/PN1Ju4Ao4rfD0U31btu6/0IphMJVOyjjbRr/Oty6vW+o/UBYfpj8iJJUN9LQTjeVOVjEX5BHkyFgSh5asixeS/aVyIfVaZotRE+Klk1MiNdOuL/Sm5NFdz1HNizuBU3X4A7tOEyeI+Qrk2AlRwZekZ2DeQc4zrkCWf5JjYqngLHMQQUbV0IOYJAL98sELJePPQZsJWpyWppE02Pq/RNlipmPXXywz08tu03TkeiCRAJJnTKohlQSXti6b9atW7JZHW0ywR+Mdmb5V4I5yCMszqE0gQOzaFSYAOEwKhLNrsbfrFJ9Xa8dOPUe4uMNruFPxa+9jaJYLsZ82qk5b7I0nmlI58UVC7f/XYCYPrUtSu11yeDGmJg8qAJODbN/Za1AJ6Kde08xa95Zxy7eJgW3rrYcEQCLwxIeHsgELQ4iK31APFZBRGVEV2skCKEaKkOL0kLITXX/OGWnGYKOJJrKoXqmrzc3CgxZGtRON5aZJDB+YGIVQE+mbPwvrGuXbohTO/YK9s4vd7CoSoVzPsqEdLvA==
  template:
    metadata:
      name: rustfs-secrets
      namespace: rustfs
