---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mas-oidc-config
  namespace: synapse
spec:
  encryptedData:
    config.yaml: AgCVFj6WcrmWU9xA0Afy13W5lVqTnKMj6ZmY6GtOfK9IMoqEy0nHITpE8DOUisaIaqyu3fbyp+4J3ipCYDVP14CgpvmoicemwLqSu4M3GyellsRl7W7DenuUqT9TU1uqRG4Ie/YTgIo9PLR3MRCKQQyWmwxSd9Unt9lTGYpdwofnEq/GpqumUuRTT0ZbQ7WvSo+LvA03HMa6CCoGtaeYPINP+YnGbHvl5bKxkeF35t3dnvL7+xJhCbWIZmjeslLnHXtzZNyCacx/BICir90MViDCZgGZKGFAvkmSvbix7vrE45AYxDGwibgJq8XLdtOc9x7E1KRmgk8dEHDNmhq+OlbK1rjD+MxIUnoUOdUX9TmKDy3DXn7tCPeSvjKqFaA26R8HXF3erE0FO+ZoymWYowijFyhA2efemqxbThGKhovzTiU0XDZ+E+BY06F8TtPFEpHPl5A4vErP5WsoUkPmaZh7FQt02vdCuwct8OoAyd5ix8+eXA04RuvSLYRhS0KKyA8GpvseGERr7Sy05SvUwhxusPEd4gTZFWUG05T2c0x7Jja+2CvceaRHzRM31dgxwWxnr7wek8crjo5SIEC9YRADNE9QcJcx2m6XYpKZHhu1puMgceIMF1xonpS3gB3RR75v18UnLhkOJs+nQhCHF9hzMqfiyHyR8N289Z2hTYxdVeT8dBj+4UxHBr1SE5Fe5jWwBfn17Cv8lu+1D7KUrUNyrY6f0uBuQlgW2omncBXRxMDQwAgiofDovhPtc5hN2RM5Dss+zsSZ/vbJcHc0/6Lj/CMWF9WUCU6Ht7iD/lerc0ylzOoJtCEbY9xtqZz1ZDCAG/zEc6arjf1XHzsP2YXxhaoNn8QiSaCw34h/HuEIiaCk0avA2RpGWEuGIUBQgMztREpV+rvt+An1IdHkiH6noxS8Yta/ea0Jzao3II02tSlL/umtwIfEn69VQwT+nFuUaixetHSYrrcbX3SQqUYk+jySPJxqvUY9Iy/Yn2BShASu5gNRYi0rAfJ7xsL4dvjTbxZ80MIDeHJQpT0hn//iV6BtP3gqrwQljKHYQ0ETA59hc+QX8cBnoqK9cMF5CV5yW8z3pcSxvDpU70emvaCDj09/q5SthDK39Kq19kjykRWuKnWOO2Pla7wba8EnYN8WzvmWM910nZSC2GvockrquikOBRGmgQeA3S9cOeDHO6zYmswpymvL1g0RZLRlm3bETrhN7K3vOeEAp5/XOHsPW5/974yu77ojogV74cfaEvpP1C56OvkwsxidHr10ajbfWh2SUJ8/TAl/a0YY6GMkEXqm2ztZKmnTj43P3HjaH8xn6wW6XK6OE2aByVoWA/WlkLFb+Ig+LPUxbly37UtZf2uedk4=
  template:
    metadata:
      name: mas-oidc-config
      namespace: synapse
