---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mas-oidc-secret
  namespace: synapse
spec:
  encryptedData:
    client_secret: AgA1m6O2FN7CpKWGgfJm8Eo/3O76xwDywyscZwIeBL6epRs/m2JZEwVMNnkKwGUE+sVpDV/uOGTPSbcjTrIqey0wOJymRQuZ3bcuj8nP95gLAM2OJgxCWiTQAfbuh0nMPBygGe/vDffCmPwIBxBy7/QsvYrwWkQtSCy/QCXNPK1alcM5GBTtdHYYNkjBkkzIitSOEE2Ye9vbA3tFuUzoE2DASngLe4Oer6ITNv6KLESB1qslO4JrZ4Tu6ZfQ7Z6/yngVyJgLyEOqLjqFTXqxZ3WoMCV5f7+z5jKQvBi+90r5rkrRYnpCAomwoCIgi2gIh6gdtE7uDU+bjlaLEhHzhbuKitViEjs0Pc5tiEGTxPvStry+n6UHMi1PXxUvvOaeOXfqQLQJ5fdoeGq7H9/Ez+O6Fyv+MrLhxMqufI5aI7EEOMWXWxEoTKAdDiljMM2sPKaXDNxooJAHKlDRNVws/Cp1P8f73AXKI/T6o4fJP96lG2cZTX/sNlShRrdjKfx2ebwVjEClyGUy9c8zFn97f0+PHNIyvqCu6/Ln0/qUhm6wE8rLIfIsRZk8T2C5NpcZQVh+dDnQqnUDZ6tswktGRWEImYmL6oiQ2ub41LH3o97DNRa9q5pLL1Y/0K91WyySdnkgSpPAgjKYRi13Rwg8s0eR++/VglL7KaSXRJzTN0aBfa5LFrB9V4CmNDRWKMGVSy34J0Pci+SmXv1UdbJZvAYonrWWzs94ZNhBuA3LUOvFmx+h4MsvluLUzsg5x+/8sgzRQ8YKvH7DYoeLgthB1q/BkgGLYZFyeDvnfV6bOBRXlakH5TzK/P80j5nWlbj4jvxhl0MrVSJtm4pL+ImLBLHPV7Cau9ydZU3XMfSFTIvrkg==
  template:
    metadata:
      name: mas-oidc-secret
      namespace: synapse
