---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mas-oidc-config
  namespace: synapse
spec:
  encryptedData:
    config.yaml: AgAeJUCtVnEk+YLGyJzPm7Boh9aw5GIdUPb4mXXpBIAW/QgQOuppj9vvNtmOTlkpLI4JKEszrww0am8Vx0vjsRQJMc8jq6IL7j0zCCBygcx+Vw99/+bMu9A+sZM5yONVda7A0IZFe/NS8B4oY3+QHcPKTnKgur95XbO5VHtQ2tJlfE0HNzik65osM2xAsy7PBZZ1vk0lJh+HkMi3nLGyoSa0XreThUutqbu8zVKHxadlOMs+o8PVxOKj8LwKMrpTZRhAfFlmX/3GH30WEnfPdKrPlLeNRbTQ2/BkrhdAafpjd6cPkubaaIILCAXG4hhS06d5FypbooQ64IZT97kQg9FOZcAMFXSSGE0zzj3PZd+u4maAuZowJ+gg13Xq6iqwuTMDNXHuT7nMauqKSA8OJr85whFB/VK94U3k64nz/19RdZYKT0xldgJfhEkmuHCVQdj/Oe5GZbau+lFuUPelVOUnPVtZ/qmUDQN6jLg30uGxvrztBmRtczXzZNg5JyrFLdQQRe1E9LXDfOgfK2oEs1W6RBY9ncdkIXpawIyYk8nenrNqyXVH0tFP3PFdwaYpwafuZMPYrBuzJK/TOMVVxbnI3KMGE0YagiT03uwVaM0BSxUiI27HbEhu1ECJ+yc/ymJSH3mTRgYF+Oe3D8+mTr94xKqqq9MKL5SGT5uaG+LGNxf1DJc8TKkXyEgkpRN3ZoSH9rb0IeC43dfnDkS4dAgBM43mrKVR5OD9wOaTEp6WgFB7+aAj5WTPci6tnlt4QA00TEooyy/RDHEewZjd/uQyW2F0AWIQCYUqXKv2IUzK2deKomyXoYdMqy+Zbtr9HfyI3WTZm5j80pkaze0QMb6SNuT3q35XfKN/M846lZMnz670s0Pq+ofjM0Um00VH6iwkpu7NBrKoXVTscK8bNjtmcMc30rrPkBCZW3D1/PS94udFvobO35VqiRhKmvP2GpkyijluYWM5phPSrz4LxpSIR+Dky3IdT5MwGz6Ue0+BsWEb3/fW4UZB8K7Re/JWEl9xExnmfMfcGRAFdqsftmss5YUuXJ1vnijsM0JysXIr1XaMzvLw0nwcSVsYJcJQFRjlD0GLPiHCR6ctkNIdchaknu1Qooi7i5HGKYYIry5aEPYeeP2gzisMlhvFAgAs6C6mQGIx8Qq0Fm+b+yrG205sK3nirAMQLVAYCiazk9sZxYOZppXpLYUHdPAJvkpRvlHli1A2hJZ4nGtp7aeRiArylHLHZe8k6GCCRi98RV2+qd43SmGPlzxrhlPma/Xd8LFGvzHXTjH7hSWWRD2lTiZNqSI1NdBIbfJ+6vs0/pAb1pCs2788QapBolBCcSNTYc+zYHs/K5nlhCwsDT68LVziAFJum5U+2ePdC2pZBO25D+MI9DwrdfbW+QRcVXsV4wtkba2m
  template:
    metadata:
      name: mas-oidc-config
      namespace: synapse
