---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mas-oidc-config
  namespace: synapse
spec:
  encryptedData:
    config.yaml: AgCFIrquxG5IsK+UNEipqG5cpWUWjNEMNHO11vTChRM7/pCvvzQ/0tX7FokMuJqWTfROtB/kGtoJkxvLps0XbeHXmpc4sQG6cOvwcWals+NJDkXT5ELuWApNEtxHIeSWPz1KKgKChTA2ubiSaRoCzd2xwpflyKUmbHmu6rGuuceHZbBbN8Jjas/cbrXZLatcmLD6LsMF7JLoDNizO7H1GRSxl2pmx81bWZVtJD9osh/ztAqbcHTv5sM2LeBa/bgHg19Asdp0M/EegEiF6Ji54KUUuP9s9A4LA0NUqa4+hjU3k5ek0GvjvbQtLSvqRzVs3anfvp7/rbKpJwoVQYkE+GfL98olDyye4MdpyI6xTVyZ6tBAv/ZL5bjL1YtHjEdpoe9DX9ln3nVntpyUwTSncpQAbNoC75/762h0a33F/embqKjTsVt/2IQ3b7hT9tdzS22QRd+c1c+J9qgA/T0snsH69UZAwULtZG6Me+agVK9gCMPdKn4T9LIbMtF6ZTF0ISOfHtLXXjC+AY6Yq23PLs5+cZ8qQ6iN5hn1UGK5UWK4JGwZGiJevnptdD12mz6EyyCNZfCoPxsR50lFiBd5CMJWX1BdavUAU1SZqKPxAVhBDLZJU2RQMsJYn7UG/qWDyO0Oyu/Ku8EPR9jg3LoPcLlPiU/tVWmHNTWXXSaw88W5Ub0cWqR71DgJxO6l+CsHdBgNLklXS1YDrGSe/8brMBWmDBWFVQFufGLmDMxMyrFGnYsaAyt5ewz3XrYEmN/O28GRQMY8h+xdYfTHnTyA+NxPaDQwoldf3u/oDS+MZgFqAXd3Y0GN/7UK0ydGt2eK3X0PyqsMIi5cucKEbfIKzSEIXdwdBCxEDRqPe2GG0gwt/9sHHsIe/UuSztUHh9Qd1OdZ2V0h2dzi9e7cRMvyeKGBtQPs2SF29IraVe7VaiWewYyRzdxA5HvfaWQXlyefIiVHzNhcac1CfelvyYVXfof/FvLULBSXFxojZQRkKnXroQcNo3wRNec14hL/VTUcN1NTw9xAsIjdBt8wGX1VfeKsNCRKKE55sBRCcdNUCTVRJ4btmI8OkDuXcVbzHHbVU3J9jY+z7RJ0y+7nmzriyTbJa/YUyN8uRgfIDzdtjF2TjRnowmeiKywq20bN6AkEbwKqczobjY9FduP90+pFoiXPMESU+uaq/s95UpfTRajkmdo+9cjgZDYd+0f7efLySJA/vfDtcgh0JsFVEewF+1HVGNTnbDYWft+WwJcMXa6++2endLJ8eLRwEUnGRAy7OTs4AzG+d/6VMauTirYT2qLK8jOeYoUNripg41K4J93Of0PEis6+6Wvld058Sxz7LjqGIrjLJGb/pJ8JdS5OFb9F2a9Bhw==
  template:
    metadata:
      name: mas-oidc-config
      namespace: synapse
