serverName: rostor.cloud

certManager:
  clusterIssuer: letsencrypt-staging

ingress:
  className: traefik
  tlsEnabled: true

storage:
  storageClassName: longhorn
  resourcePolicy: keep

affinity: {}

networking:
  ipFamily: ipv4

synapse:
  enabled: true
  ingress:
    host: element.rostor.cloud
  media:
    storage:
      size: 10Gi
    maxUploadSize: 100M
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

elementWeb:
  enabled: true
  ingress:
    host: element.rostor.cloud

wellKnownDelegation:
  enabled: false

postgres:
  enabled: true
  storage:
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

redis:
  maxMemory: 40mb
  maxMemoryPolicy: allkeys-lru
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi

matrixAuthenticationService:
  enabled: true
  ingress:
    host: mas.element.rostor.cloud
  extraVolumes:
    - name: oidc-secret
      secret:
        secretName: mas-oidc-secret
  extraVolumeMounts:
    - name: oidc-secret
      mountPath: /secrets/mas-oidc-secret
      readOnly: true
  additional:
    0-authentik:
      config: |
        upstream_oauth2:
          providers:
            - id: 01HFRQFT5QFMJFGF01P7JAV2ME
              human_name: Authentik
              issuer: "https://authentik.rostor.cloud/application/o/element/"
              client_id: "f7GUxUBYNDhb49dosT3WRLeavsKviyDz3A6BhFJ3"
              client_secret_file: /secrets/mas-oidc-secret/client_secret
              token_endpoint_auth_method: client_secret_basic
              scope: "openid profile email"
              claims_imports:
                localpart:
                  action: require
                  template: "{{ user.preferred_username }}"
                displayname:
                  action: suggest
                  template: "{{ user.name }}"
                email:
                  action: suggest
                  template: "{{ user.email }}"

hookshot:
  enabled: false

matrixRTC:
  enabled: false

elementAdmin:
  enabled: false

haproxy:
  replicas: 1
