---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgejo-cloud-tls
  namespace: forgejo
spec:
  secretName: forgejo-cloud-tls
  dnsNames:
    - git.rostor.cloud
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
