gitea:
  admin:
    username: forgejo_admin
    email: 'admin@rostor.cloud'
    passwordMode: keepUpdated
  config:
    APP_NAME: "Forgejo: Beyond coding. We forge."
    server:
      DOMAIN: git.rostor.cloud
      ROOT_URL: "https://git.rostor.cloud/"
      SSH_DOMAIN: git.rostor.cloud
      SSH_PORT: 22
    repository:
      ROOT: "~/gitea-repositories"
    repository.pull-request:
      WORK_IN_PROGRESS_PREFIXES: "WIP:,[WIP]:"
  oauth:
    - name: "Authentik"
      provider: "openidConnect"
      existingSecret: forgejo-oauth-secret
      autoDiscoverUrl: "https://authentik.rostor.cloud/application/o/forgejo/.well-known/openid-configuration"

ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: git.rostor.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - git.rostor.cloud
      secretName: forgejo-cloud-tls

service:
  ssh:
    type: LoadBalancer
    port: 22
    annotations:
      metallb.universe.tf/allow-shared-ip: forgejo-ssh
    loadBalancerIP: 192.168.3.25

persistence:
  enabled: true
  storageClass: longhorn
