apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: navidrome-auth
  namespace: navidrome
spec:
  forwardAuth:
    address: http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - X-Authentik-Username
      - X-Authentik-Groups
      - X-Authentik-Email
      - X-Authentik-Name
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: navidrome-headers
  namespace: navidrome
spec:
  headers:
    customRequestHeaders:
      X-Authentik-Username: ""
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: navidrome-auth-chain
  namespace: navidrome
spec:
  chain:
    middlewares:
      - name: navidrome-headers
      - name: navidrome-auth
