apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data-pvc
  namespace: navidrome
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
  namespace: navidrome
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  accessModes:
    # for actual deployment use: ReadWriteMany
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
