ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: navidrome.home
        paths:
          - path: /
            pathType: Prefix

persistence:
  data:
    enabled: true
    existingClaim: navidrome-data-pvc
  music:
    enabled: true
    existingClaim: media-nfs-pvc
