ingress:
  main:
    enabled: false

persistence:
  data:
    enabled: true
    existingClaim: navidrome-data-pvc
  music:
    enabled: true
    existingClaim: media-nfs-pvc

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ND_EXTAUTH_TRUSTEDSOURCES: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
            ND_EXTAUTH_USERHEADER: X-Authentik-Username
            ND_ENABLEUSEREDITING: true
