ingress:
  main:
    enabled: true
    className: traefik
    hosts:
      - host: music.rostor.cloud
        paths:
          - path: /
            pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      # TODO: uncomment for Authentik ForwardAuth
      # traefik.ingress.kubernetes.io/router.middlewares: navidrome-auth-chain@kubernetescrd
    tls:
      - hosts:
          - music.rostor.cloud
        secretName: navidrome-cloud-tls

persistence:
  data:
    enabled: true
    existingClaim: navidrome-data-pvc
  music:
    enabled: true
    existingClaim: media-nfs-pvc

# TODO: uncomment for Authentik external auth
# workload:
#   main:
#     podSpec:
#       containers:
#         main:
#           env:
#             ND_EXTAUTH_TRUSTEDSOURCES: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
#             ND_EXTAUTH_USERHEADER: X-Authentik-Username
#             ND_ENABLEUSEREDITING: false
