apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-tls
  namespace: radarr
spec:
  secretName: radarr-tls
  dnsNames:
    - radarr.rostor.home
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
