---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: radarr
spec:
  encryptedData:
    API_KEY: AgBGUrey7E5FAHgyPwHCgPzW9TMTRDj81+FNI4cWGIxlgLMtDfjHP1ZvJtkz6Fm2kcdP+KfWqB2yvxaVCEAntBe2xJEdZkewjgcQSy7ynV+DUNk35iBUZtzmQ+nDC7BNGgslFGIuBLYKVi8FxK64P+SNhSAFU6USS4KlXWexgCCNoWdbonYJHgvohbjp8WuAK/NFUZRnIuhGEIZyKyhpvIaKvP1+JY0/VfFFjRyH0Lt4e3eGT+Q20Mr7j/Bgb8KWo3p0BhLh69+0yRPPKh/Mm/5AadnInxQTdXiBcYwDb9/Bwdd4YN/uExB/BYlOUXj0mjpoU4s29BrVusLRVNTxUwcYPvJ+rJUrfsCXJe0jelM45GjywBXBp+ZFFLnNw09ye34BdOSMBWUr52HRUYpnyEBogspEFEhCSVJvinaAC3fjtKwqdO2hLBBO7UNxPLk2CPLkcfcIgdZUOxZvxLACPoDvFsdhZvBtPu/o2DgagX16OaB04sFSDTWrv1KH5auOHegjr1diVJFpdi1mBinWwY4WYdff3/VAZU71meRItgfEtgCTElJhghYI7G4Sg43hzbn0ZYaaFp17+V2t/UoetQMWr7kS/8dFoVLGEi45GMcn+GJoHLdq3aSMWRjevaHK5laSZeUYdRv5SYlf56HyWoNEVSThtj6hAbcIUuBBxXwceJnYZWg4zcCSyIRHPP4iQAyw6IJ0as50UOxM/oD2WA+pZX36l1NK4A==
  template:
    metadata:
      name: arr-api-key
      namespace: radarr
