---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: radarr
spec:
  encryptedData:
    API_KEY: AgAGxqFkDASXYoq/gEEzWk9QUgf+KAVOw8YWcaRjIP73NHDT71emDjjRz5UFjuNlrtLneDtetkVkCOeyo4L29HPCU2I2S2cTlByW5S/SLa0liYwe0D19RNb5ef3P55heRKgIvCk9U5EhniwTsVu8nUNrcrhYhPXtLzBtSPSexl4VbLGBeYRTvOR7KKBlVO54Wjc6vBZ5fFhP9GwZOqQfNxD2eSyHpNrjJOpfPj823NSn0CvQqh28bloStkQM3BkLabJQBwtgvaNkXbVNREhEsNNUB0mVaNgZeryJW+be9wTUiGWeXkozvTeF4JdNMQ6mSaS/BVyUlOacUsn/Rib9U5o7g2iIrMEZAEK1oEJpgEKCZzORtxcLCK14E5Ok+Vxkx94wjDa4ICaflu7SY55FzvQL3F4moqm27jBF3VDMC79eiH5YWr+djYIiKqB0xyaWR64Mt55nT1yp4EVV5+XN1N9PdHot9n2cgXSoMmGeTPb9jWEnP2ldifb9fs2KVwV0QLMPimydQRXRj/ZogosrOTuOsMrVyAULf6DZxMyPimdfn5x/GY/n1wWPC+t+qJ9mKyDrhEtQrwddm/IOngdNHqM764OIQoKrK19S0Davx3YiYxnPNMNLE9xgFys7M0wKVyG2r7eULlU4xqlXJhtgQeMB/4YOBfRJNE6/B5yEiiFeJCkWA2taxP02GwYylVRQ3/zqCV1fU72c7m1v+5D/+TzVq7bgG87uxcDT4GSc9623Zg==
  template:
    metadata:
      name: arr-api-key
      namespace: radarr
