---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arr-api-key
  namespace: radarr
spec:
  encryptedData:
    API_KEY: AgCa4JfqiSd6AYv9qWm1WBrePzKI+DGj3BuBKFgg6sBQ1P46witUOlZjxppRXHSepGI9qpcUllA1xywMF8BXWMIynBPHKVukip4naT9R3Zdf56YvHXUCO5Xv4b87iVQuhYFvGxWN+ji+brox1O/qe1aRbJ0AthAb7Nc0YN+GptdxCrBpWX2S43ID4PjIwGiEdUlr34LLeT5empn8hAkR5Vas/cyx/IG10e6YzdfqqmFivDvSRtA5mLgxNwCgn+ckzvVeDoHSa2wu0ui7a6HUKNTOg1ArhI/UEErNNjbz2upp6F58wNhXnQzxTH5id+aUSeaa+VaG90wHzkQ5bVtn9a6YXoXQVDD3PfBEsEkurT/HAWoWjTRdbSXtn9EZpg1iyKzFhQLln4aXetWf3kNvGLM2wgKMKyYM1FaJSRLrYAzYmXdQsgHRL6cuTl3U0UeqTW3pLlE+01dEwRFLBrR8vRmwsDs2H8mDYG+JECKCRdyXPLo0XOzggap7di1R95hL59/AurQD+oE8VmsrurLptaguvqpS3ArQHIEL4XEpTju36bWnhOlpygL6fzQ+bVVpYrWv7tcFA5M2I6s9RVJXIv8Bu1x/ZMe8uQE0fwSMQJozqwj7MWv1YIbfSvLzWY6X3M49priWg1SUq5fTzpzx/zXjDmEqqiYcsaNO88tyarouVowx/YwrfWznRxxpJaqHGpXcwuoc+bS+k2hbQFgss0pWZYkej5WVLzn1jKDyGm1N0N5+ZP5cHV+io75I9YbHd92fuNTHI0+VZWZSmg5zbFU+
  template:
    metadata:
      name: arr-api-key
      namespace: radarr
