ingress:
  main:
    enabled: true
    className: traefik
    hosts:
      - host: radarr.rostor.internal
        paths:
          - path: /
            pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
    tls:
      - hosts:
          - radarr.rostor.internal
        secretName: radarr-tls

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/linuxserver/radarr
          tag: latest
        env:
          TZ: Etc/UTC
          PUID: "1000"
          PGID: "1000"
          RADARR__API_KEY:
            valueFrom:
              secretKeyRef:
                name: arr-api-key
                key: API_KEY

service:
  main:
    controller: main
    ports:
      http:
        port: 7878

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: longhorn
    size: 1Gi
    globalMounts:
      - path: /config
  media:
    type: persistentVolumeClaim
    existingClaim: media-nfs-pvc
    globalMounts:
      - path: /data
