---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3-credentials
  namespace: loki
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgA6cRWJDIK/2VOnbwTZM0u5nIx3R022D9rjfiX+OC9ajLO4glpj0ASWBmne0AP9O0Fd+/K2BJrfWaVmtlHI/mj62oXrCMZ0ytPZFaqF3FwUM+N8B5000+d5WcOVf+CrzxSde8dayarfGHA/ONRQJnFLq1bMbjBG7WBf8TikZYlvYRRJUplZ1FvhVSaKo+U98g1UR0YtJl5UxYAer/FCs+sWgxL63Mx0Z3hAbpFs6b9BOoSLKOcpN4hKCPwSQowzGFF7kIqfkPHFWI+Od9Y1ALAcu30tYFeFtMkB2MSKIY/u7rbsDLT8YUpWn97OcrfjpKn4r7VpsfNCGOhUHMslFsoSrThpo5+IgeQtY/o4wc2e4wln5lQx51ToHtcH7/cdxGT5aTHc45bhglTAb6DIgFXa29H2mFyAkTxTtfrlZ+Lchna9ZYxWZ6m/PJlEHFhSmKG3jwqu2B5nwV1SE5g5q+t0siAuA/fyAMT3gsFOjNRrU+FgUIKW0upKi571qE/H+T3nArGavy/N2e/TtuSPdelPoXl2hZBLhu9D2im0DkKulbFZba3EtSTO8dDR+dfDGUkV0KVvlFWweN+9k0kOu2iKS+J11Qq0p55zPLL4LV+0QjtGGxnvV3TA0bm7lL3F3Dw2RbWyA8LxVkDKJTtHVphc8PWYUhf1X3PXXPvvUgN9yKIVINL/GGv5GF+pgg4Jms0hguncK/oV+pEZGyWSHuswpckOt9f48cXtOiouz90JHg==
    RUSTFS_SECRET_KEY: AgCdi3U3+yKcUV68JHygyTgE6Q4tJZp6FGO0w5yjMB22kaiBIsIQ62u2+yQnYHxE8iemjYMMUqNtuulhINGoZykzKIlU+VNBOS5iduBp9vfYSnyL0cA/He+XUklSDXHdhEQxZ/bAMW+uVe/wLjSU9+jgiV2c/DqGW7sYUTBO1WMULp6dZeDw2PdNMaxNuFicQ9NB2Dx5TLEB0POI6pgdueZhDuwNHJ3p71p6l16DiJS9F8trO0v20gly5nN3j75bYSpD7FuekTqfyUDWbs3IsnkHTmu6nMtVp28NXAAQ8+8zR0BGbiQiS8Z3Xgshq80Aq6rdlswJNHqyMqadN0Eml0pwNr6JqiLCTuDm0yiRxTFXv4/4SIS+RezrwPFvuhlTh+0vPwPwsaLP0qqMyjhQmRtLtmz6Z2hyeqf27xvKLCx9+TydjLR75RnVxr4GByrXNdvGsRvt4gHN3+WivVJpXsV7qnF+f/OkYeENVtzXpmQ1qYh4rvct712ct1TBeWlg8RrUK357eGZyFCBOSXBXLIh1WTqLHR7yObg7QwpLLvjDrpMOuOJz2UyF3KDCyicTO/5rWTYvBhrppTlPRZ0Zn6j8bOkiPRiYD3J6CVpWfLWKcsDhA49ekX9y41sCKin0ihHaJpJ+RFlwCf/jskzT2hej2cx/82kg9BmCbNvu+kfneHaCWr7DnNg70UG2jdqezeXcVwIyiRMbNKNanTamFR+jOysSnaEEivrAeJgS5K8KSbMdMSSyNUvaDZOVCg==
  template:
    metadata:
      name: loki-s3-credentials
      namespace: loki
