---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3-secret
  namespace: loki
spec:
  encryptedData:
    access_key_id: AgB4CXEgqcaydiy4q5LVqMo4aa+ztEgVkFM8FQ/W+72zvmpYtj9rnRopVnXKgwWCucJsaDpRKKCBdw01eZZxo/iI/LZXMl+Ro1n4JeupraSLA3lc8hpHZRuNZ1rnVQaUJ296DouyjNek3rHDk/OyWMkEzyAp6FpKZMAkEt1Wi7Ks/HdLgMnB4et3R6RXgoIpZaL2GYTeZLz6p+1YuWquoUw3cu2RYd5NS2KIm4w/a4x2rtWcSLg8imxsPDZqpzcuRebJY4JC4SLdIYXYyFQ9TJYxghRl8m2+N8jsuWpl84URZWgl6e8kkG1gfrtOQJD1EyzPZmrTIofuPDkUAjOLM47x3LGeINcm8+hkdrwzIo6/NOBLIwIpRG/Jfck9bWxQfunkBiOnoulT0XjuRXDupzy57pB9Wb0HC9rg+cFtbaMyNBRAo/IH6lAePGqi+F4suraVGqbl4mmm0+pVc6bqcTqSlgQW4u06GAQbsLrKjQX/+qwQkr359GabwgVs5MtXma+sFK+6D2gQJxyT+I/qLybNXF1RLbvyCOac16c3lvxwVXCStQeHhKlp2gdv+yrfy0PjirGjGpT5If/zDfuU9wI+s2ZY4mzI8o0YA7CYNq++HBEaFsgY+Hl0se/vMPA48bmeXdlsuLO53CcrLTxcH9Kl5ey8d0EXnOBN4w+hwWHJCS0S3Fd8OldUaTQ8QA5RPSRSnjlxCaxr+OksJHPdHlIEFHlwpP/fsdzN3hB66ORZKw==
    secret_access_key: AgBzTbjOVCL147Bi2LgaNIfgsZBFNc/iRUaxp/9V0yUEJgwyBdEi7qW6QIb8RuGZkby+4J+DpbhESEGNYagXjjZJXBkcCGMqWvo27Bi4k1yZfKCgwX9fLbjiCulGiTXwuaujlr8mzrteMYkiDULqtm9VVOizJQR68nQOtRsDVScf4k9xyrjSqrOIbs4YXltHnQM0AYMndclpm+QtrmCaA2axogKLqn6UyKuFiit9znepZOtu7ZWdnlu+dQrKprCXAUuPpbTe+wgX47lkjmiAecdk/3xvJxQ8woWUgRXBdxQ8HRMxxE69szjvEqAMrRiLqA/auz41pcjHWQ2Q8jaqRi3JBpjJqt32qsTGN+a1ZrL5Vu/hMiv1dBKZT0W4p39BK14yv1uC2TYRvNnO9kXooB0IO67ZhvJvs51sU0A6peaTFXSUwVax75bbVpbulkpAXXKb2Bd9kYPIoTTsVFZGvJqCD7+NhnRwhC3BRsdtAQDFZZJi0WM45ux2ep68aVTKDVqneniYNUQlXr4CdlNt10Ed1gukCIThnZCkuw+2LkNNIzhN2pAW8LW5WLdfN9oMgfa8u2kKupNUb9MQg/kA3rgq40GKvK29JGXHQmVJMhT37laA3BmoikxhocFo4gPY3MN/bKqE6tAGOTaoMTBoReEw2j+wv5E4976TCdNgTMg3+j3aBMSE2iFDDS8jzKx12L4ZM87nM0swQavliY5Vrn2STqaFPH+DbSUUDOl+8xY1o5WtKZr+2vbVk0kWzQ==
  template:
    metadata:
      name: loki-s3-secret
      namespace: loki
