---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3-secret
  namespace: loki
spec:
  encryptedData:
    access_key_id: AgBDeOzbCcabVH3opNK4+P2YEOZuVZOuaXvkVtHf1bhpdG9wXM910l9NxCfFZfy6f9c6Uy53D/oiGurOtSgWiOna5/EJ1ou6ZuRJpExUxu4efYbRfST6+JdSJume1LbeTzgZ6f4mo1+gEXWjWbVrWnKl9BJ4osulKM/OcOAtuljRdmZQx/Hflm4doE94lbBR4y+en8JsI5i64/ignygvb988qI+F085epWT/+x7FAI9NUagoXTYPgNjvilpEigDwL25C6aggDUXs2t+f4uhgC4LeCdA5RkLuoUK8n62KfL3Eei9tIwiOpIyofvxUHeafnpgyXw2iB0TuMkGILShZV5MUHM+yvlu8YmxweoBlzKIxmS3FjY3cBihV028+naosqx/3vY3N0LPw+M7Qb0xs2KWFq+ri5ODK+4PhW6x1Qblu7TyR95Z6Tdtl4MdDEOwvXHT5g+712htSTEYXi8AUv3xB4u54bYokJ/jQ4G5E9HH/jipyKCayedy+Z8arN/AbHYImZaBkOeEW2rCrzy8+53sct5Ty8LrK3eq2aGx8+LHxsUhFK9Mpc1vsYkpNiLBXamK6jlB21UsD4VN0ZwzYt1bQUXMQqKzyL4dB7NS9iZpF8cp4VvR4YplnQbFmB5wooo7+n3ivwmSAlgSA6ijW9AdLaaWe85O3ninJCjDNm/hnsD0B4CUBfjZ3pH1t/GEZqKzLxGt3/48GTvjiogngdtuDCj+HJkkNjRoQKyTEoYqCPw==
    secret_access_key: AgBxvgp7VcBZNeRY183zcuYCjFEICAcYzqcoyn9KGZh55gLm3SvzO5U+hwZcHDWlUpxIAMJzEl5IY+UjJUdxmDuux9IkhEEP7XSKf9ulePHBKZhZlG9+E1UqZItZ00II+L4QvirS5niwPuyY4o6/ZdYjwgz/qrDSpp9D2wVN0JDzlxaGCBSY2kyKY2ff+c+Jb03l5dFWkLZ4nE5l/D4Tgo90DL0vzOdDOM9ntTcKt9kUmeGTb9i9t/yxyr/ds96fCXFX/B1MHMowwuChnHTCBQ8gS+E9ZW4ObSw5AZQXhxt3miunE+u3IycDVTIXDtf8FyBjzvtX3KHU+RocnMM4cQW35zn39wjvJObv1SwA6oOWSaRGvIUahbygrgFVT1c1hJmRS76mqDS5cTyPpg69yETOU2idKRzVGQ9J1gSiGBiKck25Zhof8mXhynsqF34sUG0Bda+gNqforSZHpNhsvhydFWIRbr1cykFPZFN23nogWNyPWlNqCmc+NO0ZFKrxq8rKC/DtGUnSNEvEIE+Jk0kH3FFqtUkwvoFlNwi4nB4TWj+tBEtW+VMxrCF5aMVqMIaQ6exud9fpAG2iCXPYDkOEkoVjBirLt2xQbYKwp+U4Fp75GD2+qs0yvl3QcObXRO5HG1fI4zVdDtY2RmwdAffO3fXPQ0kUxcoKIEkuWFJfAAa1AL7Ebn1NmNEfQBP1o/cw16WWjVPd0GK9g+potfiKpKdiE70ThGrTto6UQPMqVS1uVZLG+6OOOQpcgg==
  template:
    metadata:
      name: loki-s3-secret
      namespace: loki
