apiVersion: ENC[AES256_GCM,data:FQ8=,iv:ZUxG5Pl3aDR/HvA7KupDerDk5eGKl0qVJ6I+ZG4NurQ=,tag:oKAt+FPqfiFOfu1HECEOVA==,type:str]
kind: ENC[AES256_GCM,data:Dut/Ye3P,iv:4zuiBkrYDBEoqs3dTYIuCnDZUcwTJh56DimLEbca5uQ=,tag:5RLtwm/6e665vaT7mQewbA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aDsnlR6F+uhuK3PLc2w=,iv:rQE/Raq6scKG72gMxclg2PUmZ/6MWa+lZl2/tyTSP8Y=,tag:GOFi7s24v/SSF+FLmqkYjw==,type:str]
    namespace: ENC[AES256_GCM,data:MqV2Sw==,iv:OqzQ+YK32RQHK+5qELKbqNZ4Sywv6eqyGFtBpmxcIW8=,tag:HsTfTCDcP2bnNHnGvw5Y4g==,type:str]
type: ENC[AES256_GCM,data:O62JNhcA,iv:kO+P9UokfoQXy/4CxATVpaaUPDMwdCIo0bYCNKYTjok=,tag:GM4kqM7oNob/mloK5NHl7w==,type:str]
stringData:
    access_key_id: ENC[AES256_GCM,data:ZQDSMQ==,iv:/avzZm9QVvNsN9oIYNXtmNhNjQuFPY4pIRibEpJOo9s=,tag:l9q4TV5Bu27PMcHiWuiriA==,type:str]
    secret_access_key: ENC[AES256_GCM,data:fBFDybvd9O55yoCCErUCWoLeesQ=,iv:Wenp/BaWHhSaP+dEClQHsZ27rPwrRpmH54KFpuMmD1k=,tag:3wOCmUgp6eQDPe0E2YBupg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VmJJQ1B3UHMxTFpsRTU1
            cllWa2srUjJEQm1GcWlncW1paTJXWTlJYmpFCjlFVFlyRnZMSEpSbTNndjFNeUs0
            VHcyQzZ3N2o1VkpIbVlBQTVuaFRVMjgKLS0tIEhLRU5NNENnY1BwMTFZR0pVMXdW
            VWVZQ0lmOHNxMmpUQndjZyttSlpLOG8Kf9gHs1vtIz8xgrHuxDrTWUUtpkfVbQhV
            sXgrse0GfBSSqxXZciG+xo9zITW4b+FbB+o7O1p8L0YcvlNt+pb34A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrmavzfl5aarr7hs9y5yzvxn80szfjhs4xk63d6wsz8v88fcudaqsrpnnj
    lastmodified: "2026-06-09T21:34:27Z"
    mac: ENC[AES256_GCM,data:GloMYetczdP5idZWIcvULoQKWfZ9DPScj8D1W/aD6H3kIxUQgT03RF1WXa7tIb5EVKDWa7jtoBvGAPt0h604M8i2o6TKyt1un7cWq0+Iu3DEfxpCL8eEpbTC5k3g/5H2tNb6EIVrh+ROMazCjVqzSxtVaRuUzFnBOJkDHAAqHlU=,iv:+dO1yKnlKpyI5KwRI5eRDF+P/qNaQYgYESkgx9xCxLQ=,tag:xcE9RqgCQ2xoza1Wo4Jqeg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
