apiVersion: ENC[AES256_GCM,data:TAg=,iv:Er5ypIq/SIMz+JSE605o1pY53slEKvqfKmJjyNXYUFw=,tag:qbszPp49NWAY15caJ8251Q==,type:str]
kind: ENC[AES256_GCM,data:7rflw/6J,iv:DFow2w82rJy9GIsAAEV26I1T+qrXBDhAgH48ta5fnyE=,tag:UJsu+G52e1t5cEwz9d57uQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KGYoBGnXnwVaHZ+VPR4=,iv:YPP1gqmZo8+FBe0jFYeINzJ8oidR2U+6j+iK8ULUTvE=,tag:fHya+RRo5Cs6B6uXAcz9Fg==,type:str]
    namespace: ENC[AES256_GCM,data:I6C2Pg==,iv:UZALlS5uDqW//ea8LYV4++T4Wc84oZ2qkmks+7ESQQw=,tag:VyrYE03lxB50j5b9kGeIkQ==,type:str]
type: ENC[AES256_GCM,data:8wGicg/E,iv:qiTcZkC5xQtVBRM96K3Hf9esLSplLBUNBvtDvkH20vw=,tag:JxyJjUusLA15VNmajHB3ig==,type:str]
stringData:
    access_key_id: ENC[AES256_GCM,data:ASiJvg==,iv:HPZOWalGMhRVFK3xZyKrCOY5dVbSkL3KgPqj0iaq6WM=,tag:FsEqw6Idx0xO4ca3lFHIHw==,type:str]
    secret_access_key: ENC[AES256_GCM,data:ygTrsen+gkrohnYBeAvJVuNXMruWNvo=,iv:TWgaXazVndBo5pOl/enMJlMo/Pqmr16L1IdnpNGkAn0=,tag:rfFiNBUccYGMaloppEADow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeHNONEJtNjdHR3N1OGEy
            MUs1dm94bnd3d3JINnU2bTROZHdZcXZucW1vCmk4THprNWNDNlJSbHF5OEhtN2Mv
            TFdPdXg3OUVjNTM1NitEVzJQQXcxWjgKLS0tIHpsMElrNzZZZnJXVzJseUI2aUM4
            QlZuTDAyVjQ0UCs2VFdiYi9YeC9wWkEKpMaGaso/h9BPf35RIC8jDGns+S+E4Vwk
            MzMeZx+2QIQ8cb15sSewl3aROdmK+F5XwcrZUxadgld+OlSmii/Wcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrmavzfl5aarr7hs9y5yzvxn80szfjhs4xk63d6wsz8v88fcudaqsrpnnj
    lastmodified: "2026-06-09T21:02:58Z"
    mac: ENC[AES256_GCM,data:Nrl6IucFk5O0eq20qKsOlDXSIgXTiqXCMvIc3QwcqVi2kZGRl4g3e25CJeMGQa2plkTO9ITcXiDkH0Z/+xQdWj7M516qfAntmTopl7ZUjddKW6DweW9e5gg447Z16R8HZSi/zJURU53bSa1L3QMaF6MZDPQ4iHNxbIFgxpvy4hI=,iv:sgJHkQDCOBsTsV2qtCj0bMYK6fywlsmNcW7nmgJTYuI=,tag:3SGDmZlKPE5QRbHYn2JZyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
