---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgA8Cfmni8Xjz+vU2fy1Wd/vqnlhi17myCG2rOAzJ8+f8SGIVR2AGAETA8Taf9Kl96tAjmi21QjHeRVCgFQoCbRgsQ2T7xiIjXq9rG9NZIZ/vJxHVLSHB/MWT05Ko+aoiFjmX01GkeLthEjNVOo6jtUbaV6/l+CLTUGfTFfyHr7zFJUxwXM58CFn2otOGpSHPkLvnDzYCqKDX7yCky0FYJwOm7Aae44tzpuPqbqG0znPxbDk29tQ4sC5tnrIW48qbzZUPWpt06/uPrMGImAhK/F8UTSvi8GgWbbA6aBvzRFnZFsgRTVYszjjk7hOlk6O5QiBy1lUmj97OybMRemD3x/eeb4St9MX2MzPNOI3Wi2DxAKZ5HlcvMsCpve+hhpDuEsf12iIs7nw9fs8144ezuIh7jFEyHVmMfmp+JF3WMw1I8tSviRChiTMqO+sXU2kpiNorA41FFa70ezdGgqkDdfIcIBPwmOfxhaJ+Dr5JFbaMkFv5FLxHONveK9Krot1fj0SH/fzLo7m7AXrahnpNjDc3L0a02kecFY4icnhUrFkuLJlOB5Fh8vKMJrlnIiBPR6VTAyzRjh/iUT7dHhz2E1ovLD6NfxTdwEnXtgWptCAhIaK06j4Fmzvaet2i2etEliALSqGxeksOrFbZ5cjJYsuWJYhhdscbTXioQ2oEZ334dzQEoIdl5BNvF/wPJJmnaPP5Qx0vsiYqXKdvMIzXRfGVwUapl3n/7y/qTtMoGcXif2sGNaCd/aeIi101MczG8JWLWU7GlYg+h+uM1JONLSKaoWSwr776YlTxOoLNzPxEqjtEl/VYVqtHFRF+LbLA+WnoemH47TNspvEC5nvegWrk65uk6RRZ9v3enmLL1RQX3tUog==
  template:
    metadata:
      name: client-info-secret
      namespace: synology-csi
