---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgBJOs3+vM+C3E2sBTBPhyHHmOohqd0312VVQe6o1VLX4nkgH3QQ7nFgrK4hKF7LvOI+Cy+Iwx1PjMxyuMx4YOHDGGanyXLFW7Pm5rn/yrz//6PZpH6LkfyQWNeiAvdZd9LGr9a9y1eOHy3MjiCK+f/gLsnOznV/pd3oY8AqFmQruAh/Mejd4HePROynnzxmXcynz4/nY+luYda+Q9AwJTVBCz+DV1mN2/jl5XqHEv92NdU+ExQyXZ/wNHRUQmCRk9fJoEljb38u0GI3U/7eyS6+Oj+5UGSiH6RDCPcGib+xqcHdu7W+QRbsH2arlUC2YAux+F+IQozdOj+ctPLOnNa79USvTTPvgB0SlroFYFFC+pZexk87cs1d+H4nZZ+DQ0qTu3MZinq+3UkJ6USSjK0zWHHJ35PShfDlq8V2NJPugLWCBOfrWiVpP7zizyFjle+vQIkGXZKEyHTdLZhXhHFpcerOrIhgS4Q+Zij4q1LFCjwm+mcMV11adfqnvpo6WeWsXmffnLWeCFJrYf/PMzlv6Wjov4q2K429iA/o5S+8sX6kmGg299BNkNLkCYA/0B7w3mX3LIU91BP0czzH8R+J5Bo2SWKAcSoe5tVXkV+JeQcRvo9/F357FtCJ5KzTemB0gf2jgw9HgIZs5bVIaOLZwFNMEH7E96zctD9+eC10z49sEMk/TAezBlTliY5myBfjKYS1rRCF/jPopA8ak0Fdy0Vh+jdrn/k00jFOfbTwUxsh5rm5Cb0NS1fYd2VabVn5RPoEH5HoaKKuKqmEmrIEjxmXejW2Rq0OArAPw1X/19IePefSP3BNDjp0ZfoIWP2kPKqHic0IxOsURYXOkWfFzveM+XZODAzGWNmLHYofUT8HixstmA==
  template:
    metadata:
      name: client-info-secret
      namespace: synology-csi
