apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - controller.yaml
  - node.yaml
  - csi-driver.yaml
  - client-info-secret.yaml
  - smb-volume1-storage-class.yaml
  - smb-volume2-storage-class.yaml
