apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
  namespace: gluetun
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  volumeName: nfs-media-gluetun
  resources:
    requests:
      storage: 4500Gi