---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-secrets
  namespace: gluetun
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgBTItZdgY5Q9Th7f9tqQh4P4kOAVXrlyW14Y8pwvl6GOnmyiJHBdrphDrYsCSGhL1oaffPVASpz9eDnTZTLP9uGumd8LlKdCbmLzWa7Y6oaLFzoQYnuxnY0qCxiiH8zsxPqY3djZLRKycQ395l9XtHSdIHZSfNDbhkVKucnqijOFVzPwlov6F6mkFt9Uqd0qj09zOfCTcpI4EW6r0/jPeCs4/UItmHjTwT8En/fJYCNALkSEfPOZZQpmTcasPQeNSeZHTGCDWiDJbCXLBNyu9mPOw2leX6Hvs4XtjHkjqWX5YyEf/HYsojUYwCZKW0/p/OblsQS1iBzMQDUowOdPLpEG892GwWdyBkVygcn2VOcYajH1iBuUMxjmKNmEKVbuugXBrzIrtvzIE87CeSrFrxkiwMQ/utXE/o1N1BouH/LoEEamn+M8pefoBgCa+GepCk/CAJc/PCkbqYjzcGI0il1cg6ek8T4UBdBin6qzlkEbfrRaKqeEkI/vGrAGGehvQ96mOdf3XdDyBu1Vm3hroKiU3bt0ZoJwlCIE+wTmVQphLG6f9J9IIbb5mKMWWySOcrz1KrjqdeQIpCyTV1ewH4jWh73C1IP4vNpyu64Zq4bl2X3MbcCtZkhzxJfnpeRSejtin+UUEBots9sNOwbGfimYS5krUagd52Vdbo6Tr/PGgBcUlKRPIRDgRKxZh2ecH3pLjlihOHENXWGEOLJZ+jcH8lJCREBbt8DCjpDLMteAA==
    OPENVPN_USER: AgAIQio7Nmo/fdvoZ30jOSwtyuHxVhIxmPpKg+/DnR2U9FQqy0uizb1lrucVCe0hwJy+yFLnsosyYB5AxVAIeCAfaDWv3Lq5VQVWq7DoYeZX8stVxC1ydX9fDcLSgPPiOQy83xN0zXvrMVn27UKf2EiEYoQ0jNHOqTtPixiC/lhfwxovxiDaWRetD79lVEbR90UITj71nGSP8gt2y8tnp1/jgGmhkF/Aw73ixi4+TRLfgm4Jw6zHeqqrVSkxtBT675LBLZBF9kc2bPo3xy/wXsPG/Vt6wUgPh20uKg9fEJiFOVuj//fZmo9BRfWTyo8wNaUXMxP/+m3Xhhdac23AdnaQnOcbJu3/Q8knWziT4S5qIuDcHDcgl455cAy/SAt6yMVdLyR0g5cNu8Mjmp3z9MW++ebPSVT7x5zUA0HT6aCd29QxlQJbuSn/U+nw6elBwIyU0xMYy97/YOKHEw21QO14EvVyycfE3UXswH/0R6I574JdEeCdngUY5NOBslKlAK48vy8uTHUQRm+sp50D1CLa08ZzTxSwtgqCNCAdk/vY4UEKQQeTw9gbw5BuhcR4xCpup9e+OeeryoUOp4fwiJIRYarcwRHR8dBaT+5xH60xadrAmZP1U483d2kH5XEtgZVZsYfs+2MIFHYfkzwo3Grgdag8InmZj5v14fZAxhJToRyVg/Pb3KE/9dhQsv+i48/v4Kk5M75YIqgyobWJykoqSEfsIq3Pbx8396rnDAXplQ==
  template:
    metadata:
      name: gluetun-secrets
      namespace: gluetun
