---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-secrets
  namespace: gluetun
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgBFJ6dvuQfT/rwwcAepp9hT9PWmVVXrbhkymNWwhNO7Rohp6B2MrlEQ0iOEXfqB5vVK76kgG5sRthtBwjs40kwapkaKrs7kkqh3ZZMASyUmn+uweHRxKONVQqpNH6Jr1/+UWhXEpkd1ZE737UbBezPEa874g6N2b7L9ZBbS3g8Kuwuvor8D6eHbYCV2l6/wjIj8OJ6/5sTrpVCnsuMLVKV3Q1kpovRdRA05XMvfoUsnSfAfcuL91VwlOUVJ4dYdao6QgRhq0TQRsnpBRgMuLUTzkCrSDjmtisPdGtUF2T37gQfriXONUne/wwAYse5Ro10rpY4HjL5TlDVnMEg5KUYVUG3UIQw5KkeTn26EqlhjeIVW/KhCf/ek7HhmrQ7sEXkShrObzh7Wi+Nt3jYXb3XU78YbKJbbEHmZiBpG43bAzUsDwmLkntlnlaKV4CbTsTdG/3jK3IxAJ+Nl7bT/Zh1JCvwyPRP2zF4hpNfLcnGS6VoFAJ3aknD7qC8e1KpAgqlrtWxnthrcNLEPkHaaXaXJZYJLKsnTrJrlC+nUYFWDh+Gw9qhk+usPCehxtqv8kkE4y3qoSy/PUcMButmewmD/mtk1vpvXXC6vl6V2JAjSSzY375xPbBr0bx+vZSv3K3BEuX6okOw4mUDCorp07cvEIHd2wgOPecGDYDyTvzGCDYpgfLswd8QyR3VAO96TjxoXtirsyVJAYgv619QBX3HRPqdDxzKx3IrccUTlJyyyPRpt3mpJ+onFRq/XNg==
  template:
    metadata:
      name: gluetun-secrets
      namespace: gluetun
