---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-secrets
  namespace: gluetun
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgChx9B8bIhHo4CKi0SufWRtUUNb9kbpD7hc4sF+RDYsSYkmSgqBs92mHoWa3EQnDvy6Z5RBHDUVd9ZGepbGVvCYw7bgJRlZp6BXnOuTI6fGZrASZoW1YfySVGCHhdrVu7FPNssADvOPI+lDmcjmjOE7SWePfAfGsxSzAcbushY7APguqulgcOjqy1Upmwihi4Y4sqBSNOUYsfboh4sa040FFanRcfDUj17vn3vgtSsHytE7EiJbmLm0J11JNkdMUqtPYiL6P9osITGScQRuQzm7V6R0plhbg2LvGk0+NMPFuZ65+YqKt+WDnFsP2ja+Ytm2iORoeALA1UP1f+ooC1BbqAqrG1K7Nofi6uzbMhWH2vFn7JlNbk/VM+Fg54/YE0ueXBWCQwmEiIQ+HMP4jVWKqb05ZEQr+WWtg1ssMJCq2dWEB9Im5sfcrFN2ErgmpA2zAr2g+kcnzRJWHtqaLm/Pwr+mPO0kG1uB1NkcgGviiG3LItXf7PBUZ6T0fJ3uyvDApb1dM8aRPvOSiDH6f5hfWn9IDLOtqD6xy+Iq1bqAwowzFMxXdPBEfsGN3/d4eNnhytrZMstJTC+TagAwC9D9TuoSRaVA5NTO0tQDMnYyb0rL+blq1GgDukKItDdLWWHJqAUtgZNjMcLR8YUplAGIJzXR+WLvbyiOPAvVDMPt8gl7WJ39JkvYSwwqOZmZfFZoJTVvx4jFiKNB5G4qYpSBazqBK6+qW20nQQlTbcJgkKOq3ETZC0ayL0/FZg==
  template:
    metadata:
      name: gluetun-secrets
      namespace: gluetun
