controllers:
  main:
    containers:
      main:
        image:
          repository: qmcgaw/gluetun
          tag: latest
        env:
          TZ: Etc/UTC
          VPN_SERVICE_PROVIDER: custom
          VPN_TYPE: wireguard
          FIREWALL_INPUT_PORTS: "8888,8388,8388/udp"
        envFrom:
          - secretRef:
              name: gluetun-secrets
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

service:
  main:
    controller: main
    ports:
      http:
        port: 8888
      shadowsocks-tcp:
        port: 8388
        protocol: TCP
      shadowsocks-udp:
        port: 8388
        protocol: UDP

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 1Gi
    globalMounts:
      - path: /gluetun
