apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-immich
spec:
  capacity:
    storage: 4500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - intr
  nfs:
    server: 192.168.3.164
    path: /volume1/k8s/immich
