apiVersion: ENC[AES256_GCM,data:s8s=,iv:YY5OGVaDXjkVAq1mqj5a9IdWKAmT1RJi0QFiHzqpyLQ=,tag:h63rx5bvBniK/3KV/3uRjw==,type:str]
kind: ENC[AES256_GCM,data:Res8a2B4,iv:ekgC+dHp5A0i0gdo3JMpnbLPag5BEY7JQcbmFTFRjoQ=,tag:7Odrr+pZ9hrMPXaz/syFag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lo4eYfDNAQxOx27hYRFZazHp4F0Fmg==,iv:qC1lxs7rPSTl6OCwCClIKPwqPEn23othZJiTAjXGiFc=,tag:cz3HSOLp5rOHsdDIHkOjQA==,type:str]
    namespace: ENC[AES256_GCM,data:NZAImYhn,iv:Ecszo44d0waRj3oWtU/qRs6e5TOl0hzb4FYr5+MOoJY=,tag:WYiZ8ZEJokEgCU/jATATcA==,type:str]
type: ENC[AES256_GCM,data:lc4RK2YV,iv:RYn7ZqgLxysQ57P6xQVcFW8cMItlx0h4ZzQCMkvckHg=,tag:dTU4vX15VkDl7qDxy83/Hg==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:1nelnVkm,iv:YarD9W1S35Xmj0dU8mjKhE7hg1wA7DH4UpBk3oTZ2AA=,tag:oJzve3ZvnDU+Y44dlx6B3w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:grQ3rr605MEJycqYF4m2r7IDHVo=,iv:y7/CzCZuR/jcqyTEFI/KW6hF49b3MnxoDFwyNd7RCag=,tag:CSAp2Kvd6CrjzSGW9lnepg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:DQUhuX4Z,iv:I1HEQx1wsRPIItFBNwqseKYY7cesieinnyUewcOKv6k=,tag:APpoSyovwBb4G6i2Fum6jA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWGUzYnhSRWlUZ1VYbVQ2
            M3hnZEVuT0pVTzc2UCt3bkhJNVNrUnpuMENjCmpDcFpucC9LTmNPTUx4R1laT0pM
            SGlRbU5FQmZLME1UV2dlOURxZXJJemcKLS0tIDVnaXZwQVBsQXUrdFZ5ZHNqU3BL
            Skx4TkZkLzYxUlloU29iSXc3dlNwR2sKee4A5Uo2ebCR5Tsg719UxUlcMi4bw2+J
            AqNYlJEI6wVouLz6NC0NKtLlOfAEWN6chf3HVGMk2rFNVy8yyViwjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrmavzfl5aarr7hs9y5yzvxn80szfjhs4xk63d6wsz8v88fcudaqsrpnnj
    lastmodified: "2026-06-09T21:35:07Z"
    mac: ENC[AES256_GCM,data:hLO0HI7mGlPEELRbErB4dci9tqI02JPCfhtnCgco7m8+zCLIjP/nI5uryD1HcXz0/BkQnqN1PDb/9NI/gy0NpEPMz0LeT+zdZkuWvDNKE+8Glxb3sMTZwtt5HrBjX8cXlCAwpQPq6V8ctf6kDVws70LqQCm49XoqYxBBzrpgVog=,iv:cmgoyO1kLO68a/67wzRFohAJpNDag/xesTONpZmuFY4=,tag:qAaXI72n9kgKBVhWRQNrng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
