apiVersion: ENC[AES256_GCM,data:Db8=,iv:B8+affZDC3jQob2Zikd53huG1i2dR3aJcF229h73o6M=,tag:0NjAiRMewuwNR/uYQUnOjg==,type:str]
kind: ENC[AES256_GCM,data:dq37toga,iv:htZg7gUjntfDfaFyUdvDPrZR8Gt0NArFQAQyYQ1tdwk=,tag:ZspZ3SV2nc7LIYLmTq4Lcg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:j3OyWuJaxTXxb0kUjfzagjLXolOR8g==,iv:Sse/57IqzVkRMvBmZd+LMNUKl4tOxHY18siGW2v6p5U=,tag:A7eusy7gPqtzttkVduQ68w==,type:str]
    namespace: ENC[AES256_GCM,data:l0vRGxy0,iv:7L9ji9uOPkYFLG/SuoVbpmzmaQ6ClIzpxY3XdBZ+dVk=,tag:alYtTDjuJsrqaCQpzOLKJQ==,type:str]
type: ENC[AES256_GCM,data:iVAFfygi,iv:sLI13unVeM3cJLcyHFyfodynQW8u+EZHtrbp1uV/ISc=,tag:AfEAG4aLsskekzjC+oq9Qg==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:BNvlLisM,iv:hxtIVM4pY8hWhPejMSLlzfA7Xo0UOhqOeWYUCdtJZkg=,tag:6jtGkc52ljxbTApkJ+9dqA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VjtiIQKv,iv:PJM6/EpcphEqB5dMQSC35/VsEqwx2NAv1USSf1iqPds=,tag:1ddj2haQZ3EmvlrGV10oMA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Tar3HSYs,iv:LLwOlD2FzsZ7hZCA1hfT6o+GrLguHKxKRH8jlyKhCu8=,tag:PzsFwVzvdi+Z3m9J+mK3Xg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc0pqY2VTdjhJN2x2cFE0
            d1BVQUJQUDY4WEdPTTRlTGpPRkZ5MjBJclJBCkVkMHF2Y05Na0ZPa05Kalg0WTgx
            L0h1ZFgxQzU0czdScElaWEgxWlFwakkKLS0tIHkwRTNINmQwL1p3aXk2U09tTmlT
            c3YyZTd6SW9USGhOUllHUll4M2QyTEUKvCxKOrLE7kmXeh9MZpW5RQlPk3x5vSn5
            tQWYM77904oxYhM37gYPzXJPJe9UCxtim2uFBfYY/R38pWnW/yHQRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrmavzfl5aarr7hs9y5yzvxn80szfjhs4xk63d6wsz8v88fcudaqsrpnnj
    lastmodified: "2026-06-09T21:02:58Z"
    mac: ENC[AES256_GCM,data:Ikqz4vjgl3rL2/A139NIp0qzxt6oE+8mUnCc9iLSMnQABkger6l6D8IMQCowUiuy6s/0lV3PgCiwodfj0MkXe80SQB4oKkuMUILW+ZAyKbFRhhQYw2WkrjjT/jnv+9fb69TpjGv7GhcrVa6pLcRPnvNVQyf0yXJBH24JrC38/e4=,iv:tWZNzUtyf3rYJmAdFN4jmmrTKtd0dqtbnFlRjqbqQjs=,tag:fYqmPedWFgNmWzo+q1oKJg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
