server:
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: immich.home
          paths:
            - path: /
              pathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
      tls:
        - hosts:
            - immich.home
          secretName: immich-tls

machine-learning:
  ingress:
    main:
      enabled: false

controllers:
  main:
    containers:
      main:
        env:
          DB_HOSTNAME: immich-postgres
          DB_USERNAME: immich
          DB_DATABASE_NAME: immich
          REDIS_HOSTNAME: immich-valkey
        envFrom:
          - secretRef:
              name: immich-postgres-secret

immich:
  persistence:
    library:
      existingClaim: immich-library

valkey:
  enabled: true
  ingress:
    main:
      enabled: false
