server:
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        # TODO: Remove after large file uploads complete
        traefik.ingress.kubernetes.io/router.middlewares: immich-upload-buffering@kubernetescrd
      hosts:
        - host: photos.rostor.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - photos.rostor.cloud
          secretName: immich-cloud-tls

machine-learning:
  ingress:
    main:
      enabled: false

controllers:
  main:
    pod:
      hostAliases:
        - ip: "10.107.160.137"
          hostnames:
            - "authentik.rostor.home"
    containers:
      main:
        env:
          DB_HOSTNAME: immich-postgres
          DB_USERNAME: immich
          DB_DATABASE_NAME: immich
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-postgres-secret
                key: POSTGRES_PASSWORD
          REDIS_HOSTNAME: immich-valkey
          NODE_TLS_REJECT_UNAUTHORIZED: "0"
        envFrom:
          - secretRef:
              name: immich-postgres-secret

immich:
  persistence:
    library:
      existingClaim: immich-library

valkey:
  enabled: true
  ingress:
    main:
      enabled: false
