server:
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: photos.rostor.local
          paths:
            - path: /
              pathType: Prefix
        # - host: photos.rostor.cloud
        #   paths:
        #     - path: /
        #       pathType: Prefix
      tls:
        - hosts:
            - photos.rostor.local
          secretName: immich-tls
        # - hosts:
        #     - photos.rostor.cloud
        #   secretName: immich-cloud-tls

machine-learning:
  ingress:
    main:
      enabled: false

controllers:
  main:
    containers:
      main:
        env:
          DB_HOSTNAME: immich-postgres
          DB_USERNAME: immich
          DB_DATABASE_NAME: immich
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-postgres-secret
                key: POSTGRES_PASSWORD
          REDIS_HOSTNAME: immich-valkey
        envFrom:
          - secretRef:
              name: immich-postgres-secret

immich:
  persistence:
    library:
      existingClaim: immich-library

valkey:
  enabled: true
  ingress:
    main:
      enabled: false
