defaultSettings:
  defaultReplicaCount: 2
  createDefaultDiskLabeledNodes: true
  storageReservedPercentageForDefaultDisk: 5

persistence:
  defaultClassReplicaCount: 2

# Disable pre-upgrade checker job for ArgoCD compatibility
preUpgradeChecker:
  jobEnabled: false