---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: technitium-secrets
  namespace: technitium
spec:
  encryptedData:
    DNS_SERVER_ADMIN_PASSWORD: AgCCMCm2NjuCyws/5yHyOOFVVkQfiHtzyiXQf1NmNVD9WJUtmJAstgErcmBONJg42p/IFSjhDuUp+cytAzVUkUQom7GB6zYvd8g2FeTN6g2k/TmQ8lw6gUKxlux6rRDI+kel2IJuFenFwnR9wezRVfs2PVvIDYnGT9+nSciykTdzagffBrPwZgPwHOs5bJ5YSAa3IcO9DdEzbWfXI7oPSYsqocqun3PoFbftoYnr3vDVrL+bMQzuZU/qo3o45W1aEz8E5KrQeR4pfUqlgMl7YZgFJCWNb+q74zjnC594lj8No1K5laTotDCqJWw00uSUSxkGIH6lcU7+SPx5E9bYXqmhPxXreJG3bIt0dAnReLIfU/ef+n0wuaRIWBYWmaHObmGTpAtIPIgRpfcBaMUvNNX3FG47tEJY0SgNjbkqrApqUHvb4dgC/XXOlXo0XGprqpEs+3igUyxbQttp3qhnZon86r+aAKMOrvUMplLRmRsRBNaY5+kdPVFYxoyKRklf2g84+B+YawUrYRveoqwKE3+Etq9LtwEiMwSg3WRv++V0mTJ/wDL/yBMl9s4aleSuovzN3bEtDRxQPUd5HQqNnDkSys7r7X2vwmyF8u7gdYwkP1U+jPIqI24n4xBbv+Fo0i94UtbDGUD8XJ+Mc/W0WjioATXCz7USBO0ZOHo+rYt6dbbihz931QUHryRX2Q7iaqocdI7UOOdzkbKOOMbgWdLOS/6nlWZ01kyUvs3z+XBWna9vZG64gdYSC0M9pQ==
  template:
    metadata:
      name: technitium-secrets
      namespace: technitium
