ingress:
  main:
    enabled: true
    className: traefik
    hosts:
      - host: technitium.rostor.lab
        paths:
          - path: /
            pathType: Prefix

service:
  dns:
    enabled: true
    type: LoadBalancer

persistence:
  config:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteMany
    size: 1Gi

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DNS_SERVER_ADMIN_PASSWORD: "password"
            DNS_SERVER_RECURSION: "AllowOnlyForPrivateNetworks"
            DNS_SERVER_RECURSION_ALLOWED_NETWORKS: "127.0.0.1, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
            DNS_SERVER_FORWARDERS: "1.1.1.1,8.8.8.8"
            DNS_SERVER_FORWARDER_PROTOCOL: "Tcp"
            DNS_SERVER_ENABLE_BLOCKING: true
            DNS_SERVER_ALLOW_TXT_BLOCKING_REPORT: true