apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homarr-cloud-tls
  namespace: homarr
spec:
  secretName: homarr-cloud-tls
  dnsNames:
    - homarr.rostor.cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
