---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homarr-secrets
  namespace: homarr
spec:
  encryptedData:
    db-encryption-key: AgAxVjvO5V4HWMia9jT9ytYCAPZ84VGsb39VK+JnqVBs45xl3B4PKvUapKuXjAxykfYZfBm3FcaEjUiuGTTO17whKDnth/nP+bdcOwDCuYNMpUuk7FnxWD3RXvi7YG94XIajQfTMTY1B2U8RwZKLsBEtl6T7xjhygH+9S7xC+IOnnkWnmP8v+5IYlxfcuBNYC3eQIEh3muvAFGSy0YV7/BpFYlVhZDOA1roED/nCP8NSLStesat+T7SB+A6auvguhitK0fBlX1uEJSKEQ/rEuLgvaX9ubL7oCaiC9RJOzAj+TX2VVsVG90A8bKhrxoO3S40ZOIlNlTV/yxj3ieNDEIYI6el4Yqb5cRT+Q8DLuZdYVfm64L8LDyklxIq7pJA3GMqtzfCegdXzbAGdeRRqTaUXaN06SXCnhEnhP0GY2GG75N7grA6Vk9yJzpFHieqfXI+A860cuAgFAhSfqOPMQ7mH90WqEnIfp/PI3e61+GgXiAUiqHoaIUqfxSbMXyquKyzFOVL7aecbPj9Mx5TaC8ccPKEHgps1mwkQJOa/cwA7t8uo9tIRR+O3HPG45vw7JIvBWOFRkXhUo4onNa1fmozpSBb8G44Vl0oQh7pzkh0wDPxhnwjUT/uv25XeV1gBgNnu86DOWTKjCPNWk47fq1FukLeX7z4lg9ScYOmoEcQ92e2VCeE5Vd6SJFhf3NNIikZ5P1uR2yvaRkiHqf0cvqK+I/pouxYHiIcZIeL8j9PviqUgc4TWT6kxIly3Jqjwqyl1N7rGRIOE0q8iGFZxA3qO
  template:
    metadata:
      name: homarr-secrets
      namespace: homarr
