replicaCount: 1

# hostAliases:
# - ip: "10.107.160.137"
#   hostnames:
#     - "authentik.rostor.cloud"

env:
  TZ: "Europe/Zurich"
  AUTH_PROVIDERS: "credentials,oidc"
  AUTH_OIDC_ISSUER: "https://authentik.rostor.cloud/application/o/homarr/"
  AUTH_OIDC_CLIENT_NAME: "Authentik"
  AUTH_OIDC_SCOPE_OVERWRITE: "openid email profile"
  AUTH_OIDC_GROUPS_ATTRIBUTE: "groups"
  AUTH_OIDC_AUTO_LOGIN: "false"
  AUTH_LOGOUT_REDIRECT_URL: "https://authentik.rostor.cloud/application/o/homarr/end-session/"

service:
  enabled: true
  type: ClusterIP

ingress:
  enabled: false

persistence:
  homarrDatabase:
    enabled: true
    storageClassName: longhorn
    size: 1Gi

envSecrets:
  dbEncryption:
    existingSecret: homarr-secrets
    key: db-encryption-key
  authOidcCredentials:
    existingSecret: homarr-secrets
    oidcClientId: oidc-client-id
    oidcClientSecret: oidc-client-secret
