# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: authentik-tls
#   namespace: authentik
# spec:
#   secretName: authentik-tls
#   dnsNames:
#     - authentik.rostor.local
#   issuerRef:
#     name: selfsigned
#     kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-cloud-tls
  namespace: authentik
spec:
  secretName: authentik-cloud-tls
  dnsNames:
    - authentik.rostor.cloud
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
