apiVersion: ENC[AES256_GCM,data:a/s=,iv:ypvJhq0QoKz8k9ybXxFdnFVmiymr9v5odVMzAnuJbRk=,tag:8dlurlL/gMkG24ZFnoHMyg==,type:str]
kind: ENC[AES256_GCM,data:HK4nNSsj,iv:Fo/zE4TGXciBXKout5W/ntKJC89Ao31TcFPZhfDH1oo=,tag:g4QXKCJNs6hVQn6tnR88fQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tiv4cyZu2tY+z8rpBvu1RsQ=,iv:dVa8QaO3OvPCnu0H0ZO8MjgQqWmSEg/A/2fdQcDK1YE=,tag:WzER9RESB+t70OS0XvAYhQ==,type:str]
    namespace: ENC[AES256_GCM,data:vIe+CWGr++XB,iv:18+xIjqIyvFv/WNMWPA0L0XxQpDT6QsMsX7ehiVyYaw=,tag:Dawbyi239TnmK5K7HQT/OA==,type:str]
type: ENC[AES256_GCM,data:yTLJqxHl,iv:Tak7hlmfKEjZBgMhIZRTLb+Cb4gBE6MkjOv/ste7Pko=,tag:Vp/lblVA60OcPF2KgN1VaQ==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:qwRZH5PPrT+bTO/svonuwpl/AyfZa6bZTgyHW7QB9pc=,iv:4pG0Q0+5+Ow65KB4sT2bd6xcLauPplDZekQdAkvO1rQ=,tag:IIxKUBDkUlh64V3jvdMmjQ==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:EWTCcaDm7jrNPBCqt6xSr4he/PE=,iv:KP1RyngvSeJUT5QI2k2DqYSwMmkMSlMATqWkBqYh/oM=,tag:7IwmPSYM7dgHnyub23ihqw==,type:str]
    bootstrap-token: ENC[AES256_GCM,data:z2bRBbQVaWTofKj2/NjmPFFRWZWF9vF4TRZBE6WLux8=,iv:OEZwOexy+Yj7IhGkCw/glQQwe6aWINGS+V4N8k/VZPw=,tag:Uk4gx/iXIb2xO/l2jMtt7A==,type:str]
    postgres-password: ENC[AES256_GCM,data:JZvXmpTsliprjvampMHELB9o0kE=,iv:9axwS9WybhdHwRRlvhKrgfHX3Qdj3g2AFQ13fQ2ABGM=,tag:5vha7tkWNRJPpuINz/XBCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcWJuSk5mQWI3Mnp0aXp4
            MlE0dTl1WGNRT0FXSXlJK0pMaG5WbGE4WWhRCit3bVdpaDk2T2JNNm5QdlZIN29h
            T3hZUkNOZG5mMmVtZUdDY3NHZ2V0YkkKLS0tIFlramx1RXI5OHhTYW9KYmlpUkVt
            azB5ZXFCS1hXUE9ka0JIUUJQbjBBQkUKufNYW7eTFDaFKjbCwlqjaYHcQI8U29vO
            +9xkgcKr1bg89fQJr7P3VeNk+/xWIuL3qF3U18kYbr56lDdOqD1dtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrmavzfl5aarr7hs9y5yzvxn80szfjhs4xk63d6wsz8v88fcudaqsrpnnj
    lastmodified: "2026-06-09T21:34:36Z"
    mac: ENC[AES256_GCM,data:AaqaKozcsETNqeZCUCC+7OnUDQqkORkzx3rxbUzqclAh9CEpEGJYfbkmHkyxs3uYM6VwQX9Qjc2WNu6u7BpIRiBxpfSPsQ8h23ik9uGGfuiJRCwHfV9O188gqrO8MLC7G3jqhrDkUtgo24EVdlBbnoRB8jx7G3ePEcCkaavUb2A=,iv:FRrcx8gNXcyio73rHDNZ/EI0ApjNnIpvNidA2MBcU8k=,tag:PxYbfQ7Z1HKn8ja0F//XxA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
