apiVersion: ENC[AES256_GCM,data:/LI=,iv:LI6nS8hjID2i1Sa94I9DOjJk6WUbLc0BLOgEz5zuCx8=,tag:Tj9wFa3m0P58bLjTWyqL/A==,type:str]
kind: ENC[AES256_GCM,data:7kIxpip5,iv:xGXp4p1WIUIV55H8F+zHC2K6clIvkH1OdELus0ZRx+Y=,tag:pHwMcPuP7hONvD/LgNUf8Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RAgIlYDxy5GoGk8G3/jGYB4=,iv:C67ozwtkif0v4mV13Lpi7Gzyf37i4EFVBzxoWuZH2Ls=,tag:EhwJzQcY8tZzMt1+1ta77Q==,type:str]
    namespace: ENC[AES256_GCM,data:PYLJ4yoU7Cuo,iv:aVPZUecQMG0sKjmt/+UZDFjxg9QrBudJlHp4JfGwItg=,tag:jTHFyPsoPk3Pcj8neq9Wqw==,type:str]
type: ENC[AES256_GCM,data:0ZvjhySS,iv:zITe5D0Dm2D71St73beq6OBhHmI1t7CxQ0+S6pjjrQw=,tag:JQatIf9JL5n9cow/lsq69g==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:K4nMxHCK4no4hAw5PyLze4A55knZxS9s,iv:uelxbpDNZu+7vNxkQC2PdIbm3KZE+GvqWElnzXS61xw=,tag:dkXPQGiPV15MF/QD1GPLxw==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:zHB09rfh4Bw=,iv:iCtKO7Yfx817XDqzeIjOXM61cq0YIjwKZuNhu6I3LsU=,tag:i2XNd9G/ffIyqKKOzURN7w==,type:str]
    bootstrap-token: ENC[AES256_GCM,data:BpjMA39VqwJ5yISikjNGjvH/87o=,iv:HiuYDL+eTrjdpbLd00OvU6AYGBoq75QXD6khzYgHJsU=,tag:4UKQt+Ciliphy9gQYtu2fw==,type:str]
    postgres-password: ENC[AES256_GCM,data:RiI9/mtqvF30tOHC8aD9IzAi+Wwm1WmS,iv:ko9M28+kezJ+YDMGWUtHMx8wWSm1ywwV7bPE+JewyWY=,tag:nA217PT9+ELJ1gzU+0Rh3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQ2ZoZWNtT2I1eU4wVVFM
            YXc0VjBPMDdrTGNYWHlqMUtOTlV2SllhMGhjCi9WaXpscmFhWjRWV0dHTy9Cb3hk
            WW5iZFB4RTF5YllENHpqNUFNQUtBdUUKLS0tIGVhbndqTFNJTE1Kdi93VjAzZVZz
            c3lHc3Uza1hUNDdRL1VvL2tFbGtOQmcKvXn8x9EUlKONNv8E1fd1iWpE1ha/QPXZ
            ZPVeOspPkL6dswqd0NNLJw7k9tPzwKMbReGXZDdmU/I294HIF5IIjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrmavzfl5aarr7hs9y5yzvxn80szfjhs4xk63d6wsz8v88fcudaqsrpnnj
    lastmodified: "2026-06-09T21:02:58Z"
    mac: ENC[AES256_GCM,data:4pgi1F0ixPPCiCxlx9/HR6o8WaoGRIVhDQDuivhhzGBsgzkrTKMsfxFZXCwWvnp5cFqhpL1EO7vzlppvS93/jUB78NCc464hl81Xkr9ykVMc3L6unaOnnXKDJML6dccL5uQz4cnLOW0cksJJt/LpnDMGKb78n+0ahffUXme/Guw=,iv:00laHWe/t7m+McRGmtArR6lA9ffgLoIXHmvqnB9rbko=,tag:HCfz63b0Gkelcrzqtj0+dQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
