authentik:
  error_reporting:
    enabled: true
  postgresql:
    host: authentik-postgresql
    name: authentik
    user: authentik

global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: secret-key

blueprints:
  configMaps:
    - authentik-blueprints

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
    hosts:
      - authentik.rostor.local
    tls:
      - secretName: authentik-tls
        hosts:
          - authentik.rostor.local

postgresql:
  enabled: true
  auth:
    database: authentik
    username: authentik
    existingSecret: authentik-secrets
    existingSecretPasswordKey: postgres-password
  primary:
    pgHbaConfiguration: |
      host all all all md5
      local all all md5
    persistence:
      existingClaim: authentik-postgresql-pvc
