authentik:
  error_reporting:
    enabled: true
  postgresql:
    host: authentik-postgresql
    name: authentik
    user: authentik

global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: secret-key
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: password
    - name: AUTHENTIK_TRUSTED_PROXIES
      value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - authentik.rostor.cloud
    tls:
      - secretName: authentik-cloud-tls
        hosts:
          - authentik.rostor.cloud
  metrics:
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s

postgresql:
  enabled: true
  auth:
    database: authentik
    username: authentik
    existingSecret: authentik-secrets
    existingSecretPasswordKey: postgres-password
  primary:
    pgHbaConfiguration: |
      host all all all md5
      local all all md5
    persistence:
      existingClaim: authentik-postgresql-pvc
