authentik:
  existingSecret: authentik-secrets
  bootstrap_email: "admin@home.local"
  error_reporting:
    enabled: true
  postgresql:
    host: authentik-postgresql
    name: authentik
    user: authentik

blueprints:
  configMaps:
    - authentik-blueprints

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
    hosts:
      - authentik.home
    tls:
      - secretName: authentik-tls
        hosts:
          - authentik.home

postgresql:
  enabled: true
  auth:
    database: authentik
    username: authentik
    existingSecret: authentik-secrets
    existingSecretPasswordKey: postgres-password
  primary:
    pgHbaConfiguration: |
      host all all all md5
      local all all md5
    persistence:
      existingClaim: authentik-postgresql-pvc
